spacedriveapp/spacedrive

.github/workflows/lint.yml
=> Add a lint-checker script

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md
=> Added 2 Issue Templates

core/src/file/indexer/scan.rs
=> Add file/directory check to scanner

.cargo/config.toml, CONTRIBUTING.md
=> Fix M1 builds

.cargo/config.toml, CONTRIBUTING.md, README.md, apps/desktop/package.json, apps/desktop/tsconfig.json, apps/desktop/vite.config.ts, apps/landing/package.json, apps/landing/tsconfig.json, apps/landing/vite.config.ts, apps/web/package.json, apps/web/vite.config.ts, packages/vite/.prettierrc, packages/vite/client.d.ts, packages/vite/package.json, packages/vite/src/index.ts, packages/vite/tsconfig.json, pnpm-lock.yaml
=> fix: icon colors in file explorer

docs/product/roadmap.md
Fixed inconsistency according to new roadmap on README.md
=> Updated roadmap.md statistics

core/src/file/indexer/scan.rs, core/src/sys/locations.rs, packages/interface/src/components/jobs/RunningJobsWidget.tsx, pnpm-lock.yaml
Fixes invalid permission checks on Windows systems and improves the progress UI by truncating by the center as seen below.
=> Fixed windows scanning + improved progress UI

.github/scripts/setup-system.sh
Added ffmpeg dependencies for fedora as requested.
Fedora still requires nodejs to be installed seperately.
=> Added ffmpeg dependencies for fedora

apps/desktop/src/index.tsx, packages/interface/src/App.tsx, packages/interface/src/screens/Debug.tsx
=> Made "Open data folder" button work

apps/desktop/src-tauri/src/main.rs
This should fix issue #79 by allowing for the minimize, restore, and close buttons to appear on Windows.
=> fix issue #79

.github/pull_request_template.md
Provides an initial scaffold for creating pull requests, prompting for an issue to be linked.
=> Basic pull request template

CONTRIBUTING.md
- Fixes the issue of the "issue form" hyperlink not redirecting correctly
- Fixes the issue of the "Labels" hyperlink not redirecting correctly
Closes #119
=> fix issue form link and Labels link

core/src/file/indexer/scan.rs
=> make directories not have extensions

.github/workflows/org-readme.yml, README.md, docs/product/roadmap.md
Corrected the link.
spacedrive.app -> spacedrive.com
=> Fixed website hyperlink

apps/desktop/src-tauri/src/window.rs
This PR fixes the desktop build for macOS on x86.
Closes #140
=> Fix macOS x86 build

docs/product/faq.md
We won't be supporting GitHub Sponsors for the time being and will take Open Collective donations; this also adds a link to Jamie's Twitch channel but I am happy to revert that upon @jamiepine's request
Closes #150
=> Update donation language to Open Collective

apps/desktop/package.json, apps/mobile/package.json, apps/server/package.json, core/package.json, packages/config/package.json, packages/interface/package.json, packages/ui/package.json
Solves issue brought forward in discussion #182.
=> update licence field to be GPL-3.0-only

README.md, apps/landing/src/pages/index.tsx, core/prisma/schema.prisma, docs/architecture/distributed-data-sync.md, docs/architecture/virtual-filesystem.md
Compilation of various other PRs and issues as well as items from the "Found a typo?" discussion.
=> various grammar and typo fixes.

packages/interface/src/screens/Overview.tsx
No issue, was talked about in Discord VC.
This PR will make it so the stats don't count up every single time, only on the first load. It also makes the StatItem hidden if the amount is 0.
=> Only countup on first load.

packages/interface/src/components/settings/SettingsContainer.tsx, packages/interface/src/components/settings/SettingsHeader.tsx, packages/interface/src/screens/Overview.tsx, packages/interface/src/screens/Settings.tsx, packages/interface/src/screens/settings/ExperimentalSettings.tsx, packages/interface/src/screens/settings/GeneralSettings.tsx, packages/interface/src/screens/settings/LibrarySettings.tsx, packages/interface/src/screens/settings/LocationSettings.tsx, packages/interface/src/screens/settings/SecuritySettings.tsx
This includes containerizing a lot of the settings page, fixing the sidebar being moved on width change, add settings headers to pages that don't have it.
=> Random frontend changes.

packages/interface/src/components/file/FileItem.tsx
Removes joke items from the context menu that I forgot to remove before merging #193
Closes ENG-82
=> Remove joke items from context menu

core/src/encode/thumb.rs
Thumbnails generate again. That is all.
=> fixed thumbnailer

packages/interface/src/App.tsx, packages/interface/src/screens/settings/ContactsSettings.tsx
=> Fix contacts tab in settings.

apps/landing/index.html
=> Fix Discord Embed

apps/landing/src/components/HomeCTA.tsx
=> remove waitlist

packages/interface/scripts/generateSvgImports.mjs, packages/interface/src/assets/icons/index.ts
Fixes missing file icons due to Haden's broken changes.
=> Fix missing file icons

packages/interface/src/components/device/Stores.tsx
=> Fix debug mode on by default.

apps/landing/src/components/NavBar.tsx
Removes jobs tab from landing as it is currently 404ing.
=> Remove jobs tab from landing.

apps/landing/src/components/Footer.tsx
=> fix blog link in footer

core/src/lib.rs
=> Crud for locations.

core/src/file/cas/identifier.rs
A little refactor of the identifier job to remove memory leak and improve performance.
Closes #268
=> Identifier Exponential Lag

core/src/file/cas/identifier.rs, core/src/file/indexer/scan.rs
Indexing files shows correct file creation date
Closes #261
=> Fixed file creation date

apps/landing/src/App.tsx
Fix the horizontal scrolling that's caused by the scaled bloom images.
Closes #221
=> fix(landing): hide horizontal scroll

packages/interface/src/components/file/Inspector.tsx
@jamiepine here, it's my birthday, fill this out for me
Happy Birthday Bryan!!!
This PR makes notes work consistently :D
Closes #285
=> fix: track last file and force note saving on file change

packages/ui/src/Input.tsx
- Fixing the Line Height Issue ENG-144
Closes #(270) ENG-144
=> Fixing Input.tsx ENG-144

apps/landing/src/components/AppEmbed.tsx, apps/landing/src/components/NavBar.tsx, apps/landing/src/pages/careers.page.tsx, packages/ui/tailwind.config.js
AppEmbed.tsx
- Reduce the Height of the Image Container to make it look better on mobile.
- Reduce the padding from px-5 to px-1
- Delete the fixed Image Width.
Navbar.tsx
- Changed the Badge in the NavBar to be automatically refreshed when new Jobs added, or Jobs opportunities removed.
- Changed the z-index for the footer, so the footer cannot longer disappears behind the NavBar.
careers.page.tsx
- Just add the export feature to make the data available in the Navbar.tsx File.
tailwind.config.js
- Extend the Tailwind config. 
- Add a new z-index for the NavBar.
Closes #(271) ENG-140
Closes #(291) ENG-186
=> Fix LandingPage ENG-140, ENG-186

packages/interface/src/components/layout/TopBar.tsx, packages/ui/src/Dropdown.tsx
I cherry-picked @KAJdev's changes into this branch, to make it easier for maintainers to review.
Supersedes #244 
Closes #243
=> feat: Allow Dropdown component to have alignment

LICENSE
Unlike GPL, the AGPL triggers when software is accessed over a network. This would stop Spacedrive and its libraries from being forked, modified and served as a SaaS platform without the modifications being made public. This does not prevent Spacedrive and its libraries from being used inside commercial projects, but it does extend the boundary of the original GPL license.
For all of Spacedrive's code to be relicensed we must get consent from all contributors. If you are a contributor, please comment on this PR indicating that you accept the license change. If you do not accept this change or fail to accept it by 27 June 8:00PM PST then your changes will be removed.
No external contributions should be accepted into this repository until this pull request has been merged, which will not …
=> Switch license to AGPL

apps/landing/src/pages/careers.page.tsx
In this PR, I refactor the `/careers` page to fit the following criteria:
- has no open postings
- properly displays a "no open postings" message
- uses accessible tags & heading structure while keeping the same styling
=> Refactor careers for no open positions

.github/scripts/setup-system.sh
Forces `brew` to install `ffmpeg@5.0.1` on macOS.
=> install custom ffmpeg version

.github/workflows/clippy.yml, .gitignore, Cargo.lock, Cargo.toml, apps/desktop/dist/.gitignore, core/Cargo.toml, core/prisma/Cargo.toml, core/src/api/files.rs, core/src/api/locations.rs, core/src/api/tags.rs, core/src/file/cas/identifier.rs, core/src/file/indexer.rs, core/src/job/job_manager.rs, core/src/job/mod.rs, core/src/library/library_manager.rs, core/src/sys/locations.rs, core/src/sys/volumes.rs, core/src/util/db.rs
Bleeding edge or you're cringe
=> Update Prisma Client Rust

apps/landing/src/components/NewBanner.tsx
NewBanner has a z-index conflict with the blooms. This aims to solve that issue
Closes #408
=> ui/ux: fix z index issue on NewBanner

Cargo.lock, Cargo.toml, apps/mobile/rust/Cargo.toml, core/Cargo.toml
shot in the dark but this may fix windows ci
=> remove openssl from core

.github/scripts/setup-system.sh, CONTRIBUTING.md, apps/landing/src/pages/roadmap.page.tsx, crates/ffmpeg/README.md, crates/ffmpeg/src/error.rs, docs/developers/prerequisites/environment-setup.md
The lack of output and clarity about what was happening in the setup script, as well as some general bad practices, led me to change some things in docs (changing FFMPEG to the correct FFmpeg capitalization) and the script itself.
=> Improve setup script

apps/landing/src/components/AppEmbed.tsx, apps/landing/src/components/Footer.tsx, docs/company/about/credits.md
Original PR #496
Also fixes #460
=> update year in copyright year + fix #460

packages/client/package.json, packages/interface/package.json, packages/interface/src/AppLayout.tsx, packages/interface/src/components/explorer/FileThumb.tsx, packages/interface/src/screens/Debug.tsx, packages/interface/src/screens/LocationExplorer.tsx, packages/interface/src/screens/Overview.tsx, packages/interface/src/screens/TagExplorer.tsx, packages/interface/src/screens/settings/Settings.tsx, packages/interface/src/screens/settings/client/AppearanceSettings.tsx, packages/interface/src/screens/settings/client/ExtensionsSettings.tsx, packages/interface/src/screens/settings/client/GeneralSettings.tsx, packages/interface/src/screens/settings/client/KeybindingSettings.tsx, packages/interface/src/screens/settings/client/PrivacySettings.tsx, packages/interface/src/screens/settings/library/BackupsSettings.tsx, packages/interface/src/screens/settings/library/ContactsSettings.tsx, packages/interface/src/screens/settings/library/KeysSetting.tsx, packages/interface/src/screens/settings/library/LibraryGeneralSettings.tsx, packages/interface/src/screens/settings/library/LocationSettings.tsx, packages/interface/src/screens/settings/library/NodesSettings.tsx, packages/interface/src/screens/settings/library/SecuritySettings.tsx, packages/interface/src/screens/settings/library/SharingSettings.tsx, packages/interface/src/screens/settings/library/SyncSettings.tsx, packages/interface/src/screens/settings/library/TagsSettings.tsx, packages/interface/src/screens/settings/node/ExperimentalSettings.tsx, packages/interface/src/screens/settings/node/LibrariesSettings.tsx, packages/interface/src/screens/settings/node/P2PSettings.tsx, packages/ui/package.json, turbo.json
Adds on from #504 to use import aliases in a bunch of places, and updates some build scripts to play nice with turbo + caching
=> Use import aliases

Cargo.lock, core/Cargo.toml, core/src/location/manager/watcher/macos.rs, core/src/location/manager/watcher/mod.rs
Changing the backend used on `notify-rs` from Kqueue to FSEvents, trying to avoid the #https://github.com/notify-rs/notify/issues/455 
With FSEvents we also receive a better set of events, avoiding some weird hacks due to bad events with Kqueue.
Still need to test with bigger directories to check the issue is 100% solved.
=> [ENG-304] "Too many files" macOS unhappy with prod!

apps/landing/server/tsconfig.json
=> make separate tsconfig for landing server

core/src/job/mod.rs, core/src/lib.rs, core/src/location/manager/helpers.rs, core/src/location/manager/mod.rs, core/src/location/manager/watcher/mod.rs, core/src/location/manager/watcher/utils.rs, core/src/object/fs/encrypt.rs
Introducing methods to temporarily stops and reinit watching over a location
=> [ENG-342] Block location watcher for files that are being actively modified

packages/ui/src/Dropdown.tsx
Wraps custom dropdown menu item with the radix-ui one.
Closes #545
=> Closable dropdown menu

packages/ui/src/Switch.tsx
Adds additional `thumbClassName` prop to style the thumb.
Closes #543
=> Separate thumb class name

.cargo/config.toml, apps/desktop/src-tauri/native/macos/Package.resolved, apps/desktop/src-tauri/native/macos/Package.swift, apps/desktop/src-tauri/src/main.rs, packages/macos/Package.swift
=> update to latest swift-rs

CONTRIBUTING.md, core/Cargo.toml, docs/developers/prerequisites/environment-setup.md
=> update msrv to 1.67

packages/interface/src/components/explorer/VirtualizedList.tsx
Hey!
While using the application it was kinda frustrating that you can't remove the highlight of a file once you clicked it. As it's the behavior of the native explorers, I implemented it
https://user-images.githubusercontent.com/36401048/217800481-325341ca-8895-4853-8e29-ccdf909e7bd9.mov
=> [Fix] File unhighlightning

apps/landing/src/components/HomeCTA.tsx, apps/landing/src/components/NavBar.tsx, apps/landing/src/components/NewBanner.tsx, apps/landing/src/pages/careers.page.tsx, apps/landing/src/pages/index.page.tsx, apps/mobile/src/components/drawer/DrawerLocations.tsx, packages/client/src/hooks/useCurrentLibrary.tsx, packages/interface/src/components/jobs/JobManager.tsx, packages/interface/src/components/layout/Modal.tsx, packages/interface/src/components/layout/Sidebar.tsx, packages/interface/src/components/primitive/Listbox.tsx, packages/interface/src/components/primitive/Slider.tsx, packages/interface/src/components/primitive/Toasts.tsx, packages/interface/src/screens/settings/info/Dependencies.tsx, packages/ui/src/Button.tsx, packages/ui/src/Dialog.tsx
Fixed the mobile issue I posted on our Slack channel + On my `tailwind-prettier` pr I introduced the opacity/xx bug and noticed it today when mobile complained about the syntax. Thankfully it wasn't used much and the fix was easy.
=> Fix Mobile & opacity/x syntax

apps/desktop/crates/macos/build.rs, apps/desktop/crates/macos/src/lib.rs, crates/macos/build.rs, crates/macos/src/lib.rs
=> restrict all swift stuff to macos only

.github/actions/generate-prisma-client/action.yaml, .github/actions/publish-artifacts/action.yaml, .github/actions/setup/action.yml, .github/scripts/setup-system.ps1, .github/scripts/setup-system.sh, .github/workflows/cache-factory.yaml, .github/workflows/ci.yml, Cargo.lock, apps/mobile/crates/android/Cargo.toml, apps/mobile/crates/core/Cargo.toml, core/Cargo.toml, core/src/lib.rs
=> CI Cache Factory

apps/landing/src/components/NavBar.tsx
Adds available positions to mobile nav
=> add available positions to mobile nav

.github/scripts/setup-system.sh, Cargo.lock, apps/desktop/src-tauri/Cargo.toml, apps/desktop/src-tauri/src/app_linux.rs, apps/desktop/src/App.tsx
Hello,
This PR addresses the thumbnail and file preview issues on Linux that I reported in #634. As I explained in my comment on the issue, the problem stemmed from the `auth_middleware` receiving a partial URI and `Url::parse` failing as a result. To fix this, I replaced `Url::parse` with primitives from Axum, specifically the `Query` and `TypedHeader` extractors:
https://docs.rs/axum/0.6.4/axum/extract/struct.Query.html
https://docs.rs/axum/0.6.4/axum/extract/index.html#running-extractors-from-middleware
By using `TypedHeader` to extract the `Authorization` header, I had to slightly modify the original logic to follow the syntax described in the spec for the value of this header type, which expect  `<auth-scheme> <authorization-parameters>`  instead of just a token value. However, I …
=> Fix thumbnails and file previews on Linux

interface/app/$libraryId/settings/library/tags/CreateDialog.tsx, interface/app/$libraryId/settings/library/tags/EditForm.tsx, interface/app/style.scss, interface/components/ColorPicker.tsx, packages/ui/src/Input.tsx
=> [Desktop] Fix color picker ref forwarding, add hex input and styles

interface/app/$libraryId/Layout/Sidebar/DebugPopover.tsx, packages/ui/src/Popover.tsx
=> [Desktop] Fix popover props

interface/app/$libraryId/settings/node/libraries/index.tsx
=> [Desktop] Fix current library label

interface/app/$libraryId/settings/node/libraries/ListItem.tsx
=> [Desktop] Fix edit library navigation

interface/app/$libraryId/settings/library/keys/KeyViewerDialog.tsx, interface/app/$libraryId/settings/library/locations/$id.tsx, interface/app/$libraryId/settings/library/locations/AddLocationDialog.tsx, interface/app/$libraryId/settings/library/tags/EditForm.tsx, interface/app/$libraryId/settings/node/libraries/CreateDialog.tsx, packages/ui/src/Input.tsx, packages/ui/src/forms/FormField.tsx, packages/ui/src/forms/Input.tsx
Added label and error message to form fields as mentioned in #640, also replaced current labels with the new form field one. 
Example:
=> [Desktop] Add label & error to form field

CONTRIBUTING.md, apps/mobile/ios/Podfile, apps/mobile/src/App.tsx, apps/mobile/src/components/dialog/CreateLibraryDialog.tsx, apps/mobile/src/components/modal/confirm-modals/DeleteLibraryModal.tsx, apps/mobile/src/components/modal/confirm-modals/DeleteLocationModal.tsx, apps/mobile/src/components/modal/confirm-modals/DeleteTagModal.tsx, apps/mobile/src/components/modal/tag/CreateTagModal.tsx, apps/mobile/src/navigation/DrawerNavigator.tsx, apps/mobile/src/navigation/OnboardingNavigator.tsx, apps/mobile/src/navigation/SettingsNavigator.tsx, apps/mobile/src/navigation/TabNavigator.tsx, apps/mobile/src/screens/onboarding/CreatingLibrary.tsx, docs/developers/prerequisites/environment-setup.md, interface/app/$libraryId/Explorer/AssignTagMenuItems.tsx, interface/app/$libraryId/Layout/index.tsx, interface/app/$libraryId/settings/library/locations/DeleteDialog.tsx, interface/app/$libraryId/settings/library/tags/CreateDialog.tsx, interface/app/$libraryId/settings/library/tags/DeleteDialog.tsx, interface/app/$libraryId/settings/node/libraries/CreateDialog.tsx, interface/app/$libraryId/settings/node/libraries/DeleteDialog.tsx, interface/app/onboarding/creating-library.tsx, packages/client/src/hooks/usePlausible.tsx, packages/client/src/stores/telemetryState.tsx
Not tested it yet, but pretty sure it will work.
=> Mobile Analytics and some changes

core/src/location/file_path_helper.rs, core/src/location/manager/watcher/utils.rs, core/src/sync/manager.rs
=> some more sync impls

interface/app/$libraryId/location/$id.tsx
=> fix quick rescan loop

interface/app/$libraryId/Explorer/QuickPreview.tsx
Hi,
As I reported in #681, this PR probably fixes the PDF rendering problem on macOS (I don't have access to a macOS machine, so if someone with one could kindly test this, it would be greatly appreciated). Additionally, I fixed some rendering bugs with large portrait image previews that I found while testing this in the Web version with Firefox.
Closes #681
=> Fix QuickPreview not displaying PDFs on macOS

.github/CODEOWNERS
This PR simply adds myself to the core's codeowners.
=> add `brxken128` to codeowners

interface/app/$libraryId/Layout/index.tsx
=> [ENG-463] QuickPreview fails to render when showing a thumbnail

apps/desktop/src-tauri/tauri.conf.json
I have the private key atm, will add to gh actions as `TAURI_PRIVATE_KEY`
=> add updater pub key

core/src/job/job_manager.rs, core/src/location/file_path_helper.rs, core/src/util/db.rs
fixes job parent assignment so that locations can be added again
=> job parent id fix

interface/app/$libraryId/Explorer/ListView.tsx
This PR fixes the scroller behavior in the explorer list view
=> [ENG-475] Fix list view scroller

apps/mobile/src/screens/Location.tsx, core/src/api/locations.rs, core/src/lib.rs, interface/app/$libraryId/Explorer/File/Thumb.tsx, interface/app/$libraryId/Explorer/Inspector/index.tsx, interface/app/$libraryId/Explorer/MediaView.tsx, interface/app/$libraryId/Explorer/OptionsPanel.tsx, interface/app/$libraryId/Explorer/View.tsx, interface/app/$libraryId/Explorer/index.tsx, interface/app/$libraryId/TopBar/useToolBarOptions.tsx, interface/app/$libraryId/location/$id.tsx, interface/hooks/useExplorerStore.tsx, packages/client/src/core.ts
Changes made:
- Added media view
- Added resizing and toggle aspect ratio options
- Hide file thumb in inspector when in the media view
- Double-clicking a media file previews it
https://user-images.githubusercontent.com/43032218/233512482-b456a1d7-ec54-439f-b395-10596815c9bc.mov
=> [ENG-295] Explorer media view

interface/app/$libraryId/Explorer/index.tsx, interface/app/$libraryId/Layout/index.tsx, interface/app/$libraryId/PageLayout.tsx, interface/app/$libraryId/TopBar/Layout.tsx, interface/app/$libraryId/TopBar/SearchBar.tsx, interface/app/$libraryId/TopBar/TopBarChildren.tsx, interface/app/$libraryId/TopBar/index.tsx, interface/app/$libraryId/index.tsx, interface/app/$libraryId/location/$id.tsx
This just cleans up some TopBar context stuff, with a separate router layout for anything that needs the top bar and some nicer handling of the required padding. It's needed in preparation for my upcoming explorer search PR.
=> Cleanup TopBar

interface/app/$libraryId/Explorer/OptionsPanel.tsx, interface/app/$libraryId/Explorer/SearchBar.tsx, interface/app/$libraryId/settings/library/locations/AddLocationDialog.tsx, interface/components/AlertDialog.tsx, package.json, packages/ui/src/Select.tsx, pnpm-lock.yaml
This is a PR with simple fixes for some UI problems I found while working on #723:
- Fix for the unused title prop in `AlertDialog` (allowing it to now show the given title).
- ~Fix for a runtime React warning about a `forwardRef` not using the given ref.~
- Remove `console.log` from `OptionsPanel.tsx`
- Replace `invalidateQuery` with refresh for `locations.list` in `AddLocationDialog`
- Lint:fix Select.tsx
- Update turbo to fix https://github.com/vercel/turbo/issues/3598
=> Misc UI fixes

interface/app/$libraryId/Layout/Sidebar/Link.tsx
This PR disables "disabled links" as they currently aren't.
=> [ENG-506] Disable links

interface/app/$libraryId/settings/node/libraries/ListItem.tsx
This PR adds the database icon to the list item and comments out the unused button and dots.
=> [ENG-509] Update libraries settings

interface/app/$libraryId/settings/library/locations/index.tsx
This PR adds location filtering in the locations settings.
=> [ENG-508] Filter locations

.github/actions/cache-rust-deps/action.yaml, .github/actions/setup/action.yml, .github/workflows/cache-factory.yaml, .github/workflows/release.yml
=> Fix cache workflow

interface/app/$libraryId/Explorer/MediaView.tsx, interface/app/$libraryId/Explorer/index.tsx
=> [ENG-519] Add additional selected index reset

apps/landing/package.json, apps/mobile/package.json, core/src/api/locations.rs, core/src/location/indexer/rules.rs, core/src/util/seeder.rs, interface/app/$libraryId/settings/library/locations/$id.tsx, interface/app/$libraryId/settings/library/locations/AddLocationDialog.tsx, interface/app/$libraryId/settings/library/locations/IndexerRuleEditor.tsx, interface/package.json, packages/client/package.json, packages/client/src/core.ts, packages/client/src/rspc.ts, packages/client/src/utils/index.ts, packages/ui/package.json, packages/ui/src/Input.tsx, packages/ui/src/forms/Form.tsx, packages/ui/src/forms/FormField.tsx, pnpm-lock.yaml
[Screencast from 2023-04-20 05-30-10.webm](https://user-images.githubusercontent.com/9082460/233309053-7726ebe5-c782-498d-9e85-5b5258da8173.webm)
*The small delay for the indexer rule to take effect in the video is due to the indexer job still running.*
This PR introduces the ability for the user to create and delete custom indexer rules, either in allow or deny lists mode, based on glob patterns. Besides the `IndexerRuleEditor` UI and some backend changes to fix part of the indexer_rule API, the following changes were made:
- Updated dependencies (`zod`, `react-hook-form`, `@hookform/resolvers`).
- Added Windows reserved files to the `No OS Protected` default indexer rule.
- Added a specialized `ErrorMessage` component to the `@sd/ui` library.
- Updated `AddLocationDialog` and …
=> [ENG-384] Indexer rules editor

interface/app/$libraryId/Layout/Sidebar/JobManager.tsx
Removed filters as a is_background filter will be coming from the backend.
=> Job manager: remove filters

.github/actions/publish-artifacts/action.yaml, .github/workflows/release.yml
Adds an 'updater' artifact to release build artifacts, which includes both updater artifacts and their signatures
=> Releases with signatures

interface/app/$libraryId/Explorer/DismissibleNotice.tsx, interface/app/$libraryId/Explorer/ListView.tsx, interface/app/$libraryId/Explorer/MediaView.tsx, interface/app/$libraryId/Explorer/View.tsx, interface/app/$libraryId/KeyManager/index.tsx, interface/components/DismissibleNotice.tsx, interface/hooks/useDismissibleNoticeStore.tsx
WIP: needs to actually be dismissable + not affect the virtualized list rendering (try scrolling on media view, items unload because of the offset created by the notice)
also needs to be on most screens
=> [ENG-524] Dismissible notices

interface/app/$libraryId/TopBar/TopBarButton.tsx
This PR solves the checkIcon prop being passed to button
=> [ENG-550] Fix checkIcon error

Cargo.lock, Cargo.toml, crates/sync-generator/src/attribute/mod.rs, crates/sync-generator/src/lib.rs
Upgrade to bleeding edge Prisma to test new Prisma Client Rust
=> Upgrade Prisma

interface/app/$libraryId/Explorer/index.tsx
This PR introduces a simple change:
- Pressing delete on keyboard allows file deletion.
=> [ENG-573] - Delete on keyboard deletes file

interface/app/$libraryId/Explorer/ContextMenu.tsx, interface/app/$libraryId/Explorer/File/ContextMenu.tsx, interface/app/$libraryId/Explorer/index.tsx, interface/app/$libraryId/Explorer/util.ts, interface/app/$libraryId/Layout/index.tsx, interface/app/$libraryId/location/$id.tsx, interface/app/$libraryId/settings/library/locations/$id.tsx, interface/app/$libraryId/tag/$id.tsx, interface/hooks/index.ts, interface/hooks/useZodRouteParams.tsx, interface/package.json, packages/client/src/core.ts, pnpm-lock.yaml
=> fix recursive imports and explorer params

interface/app/$libraryId/Explorer/ContextMenu.tsx, interface/app/$libraryId/Explorer/File/ContextMenu.tsx, interface/app/$libraryId/Explorer/index.tsx, interface/app/$libraryId/Explorer/util.ts, interface/app/$libraryId/Layout/Sidebar/index.tsx, interface/app/$libraryId/TopBar/SearchBar.tsx, interface/app/$libraryId/location/$id.tsx, interface/app/$libraryId/search.tsx, interface/app/$libraryId/settings/library/locations/index.tsx, interface/hooks/index.ts, interface/hooks/useZodRouteParams.ts, interface/hooks/useZodSearchParams.ts
=> zod-powered search params

interface/app/$libraryId/TopBar/TopBarButton.tsx, packages/ui/src/DropdownMenu.tsx
Quick fix for the lib dropdown not being aligned with the trigger and the top bar button not showing active state.
=> Fix dropdown & topbar button

interface/app/$libraryId/Explorer/GridView.tsx, interface/app/$libraryId/Explorer/ListView.tsx, interface/app/$libraryId/Explorer/MediaView.tsx, interface/app/$libraryId/Explorer/View.tsx, interface/app/$libraryId/Explorer/ViewContext.ts
fixes more hot reload problems
=> put ViewContext into its own file

interface/app/$libraryId/overview.tsx, pnpm-lock.yaml
=> hide toolbar when there is no recents & eng-464

interface/app/$libraryId/settings/library/locations/index.tsx
location search in settings was apparently broken but it's just got a really long debounce time
=> reduce location search debounce time

apps/landing/src/pages/blog/index.page.tsx, apps/landing/src/renderer/_default.page.server.tsx, interface/app/$libraryId/Explorer/QuickPreview.tsx, interface/app/$libraryId/KeyManager/Key.tsx, interface/app/$libraryId/settings/library/keys/index.tsx, package.json, packages/ui/package.json, packages/ui/src/Dialog.tsx, pnpm-lock.yaml
`@react-spring/web`'s latest version has a broken esm export :)
=> fix landing deploys

interface/app/$libraryId/Explorer/File/ContextMenu.tsx, interface/app/$libraryId/Explorer/File/Thumb.tsx, interface/app/$libraryId/Explorer/util.ts, interface/app/$libraryId/overview/index.tsx, interface/app/$libraryId/settings/library/locations/$id.tsx, interface/app/onboarding/alpha.tsx
=> [FIX] Thumbnail flicker

interface/app/$libraryId/Layout/Sidebar/JobManager/Job.scss, interface/app/$libraryId/Layout/Sidebar/JobManager/Job.tsx
This is a quick job manager UI fix. Indentation was off.
=> [ENG-643] - Job indentation style fix

apps/landing/src/app/api/waitlist/route.ts
=> [ENG-656] waitlist has read 516.9k rows in 2 days

apps/landing/src/app/api/feedback/route.ts, apps/landing/src/env.ts, interface/app/$libraryId/Layout/Sidebar/FeedbackDialog.tsx, interface/app/$libraryId/Layout/Sidebar/Footer.tsx, packages/ui/src/Dialog.tsx, packages/ui/src/Input.tsx
- Added dialog for feedback
- Landing page has a new endpoint that triggers a slack webhook which sends feedback to a channel in our slack.
- Fixed a bug, added e.stopPropagation to inputs. **The 'Space' shortcut being used in explorer was reacting to existing event bubbling that wasn't being properly prevented, which caused our inputs not to support spacing.**
**Screenshot**:
=> [ENG-626] - Feedback

apps/landing/src/app/api/feedback/route.ts, interface/app/$libraryId/Layout/Sidebar/FeedbackDialog.tsx
=> feedback fixes

apps/mobile/ios/Podfile.lock, apps/mobile/metro.config.js, pnpm-lock.yaml
=> [MOB-22] Fix mobile dev build

.github/actions/setup-rust/action.yaml
forgot to update how ci caches the prisma client
=> update prisma cache

apps/mobile/src/components/overview/OverviewStats.tsx, core/src/api/libraries.rs, core/src/volume.rs, interface/app/$libraryId/overview/Statistics.tsx, packages/client/src/core.ts
Mounts in `/System` were being included as volumes on macOS. This fixes that.
=> [ENG-588] Fix total capacity on macOS

core/src/object/preview/thumbnail/mod.rs
quick fix to avoid a hard crash
=> skip thumbnailing *ts video extensions

interface/ErrorFallback.tsx
Quick styling change
**Screenshot**:
=> [ENG-677] Error button tweak for reset lib

interface/ErrorFallback.tsx
Why can't I just commit to the branch from GH UI? Idk
=> remove log

interface/app/$libraryId/Layout/Sidebar/LibrarySection.tsx
Left these here by accident, oops. They look cool though, will be great once they actually work.
=> [HOTFIX] Remove placeholder nodes

interface/app/$libraryId/settings/resources/about.tsx, interface/app/onboarding/alpha.tsx
**Updated with useful info and links**:
=> [ENG-719] About page updated

packages/client/src/hooks/useLibraryContext.tsx, packages/client/src/hooks/useOnboardingStore.ts, packages/client/src/hooks/useP2PEvents.tsx, packages/client/src/hooks/usePlausible.tsx, packages/client/src/hooks/useTelemetryState.tsx, packages/client/src/hooks/useThemeStore.ts
=> Metro is metro

core/prisma/schema.prisma, packages/client/src/core.ts
=> Optional Tag fields

core/src/location/file_path_helper/isolated_file_path_data.rs, core/src/location/file_path_helper/mod.rs, core/src/location/manager/watcher/utils.rs
Found out that we were having problems when a file was in the location root directory, it failed to fetch its parent directory from DB, as we don't store the location root directory
=> [ENG-645] Location watcher doesn't always work

apps/mobile/src/App.tsx
=> [MOB-27] - Fix deleting library putting you to onboarding 

interface/app/$libraryId/overview/Categories.tsx
Padding is more to my liking on the category view, small af pr.
=> [ENG-746] Overview padding fix

core/src/location/indexer/rules.rs, interface/app/$libraryId/Explorer/File/Thumb.tsx, interface/hooks/useExplorerStore.tsx
added photo library indexer rule + memorized video playback volume
=> [ENG-747] Indexer rule for Apple Photos .photoslibrary

core/src/library/manager.rs
Doing breaking changes is hard.
=> ordering for create library is wrong

.github/scripts/ffmpeg-windows/Dockerfile, CONTRIBUTING.md
=> Improvements to CONTRIBUTING.md + Change `ffmpeg-windows` base container

core/src/api/search.rs, core/src/api/tags.rs, core/src/library/config.rs, core/src/sync/manager.rs, packages/client/src/core.ts
The search API was messed up bc we weren't checking `hidden` properly, causing non-hidden records to be filtered out
=> Fix categories queries

interface/ErrorFallback.tsx, interface/tsconfig.json
For dev env, i added a message for the reset db button.
=> Quick message for reset spacedrive button

core/src/location/file_path_helper/isolated_file_path_data.rs, core/src/location/file_path_helper/mod.rs, core/src/location/manager/watcher/utils.rs, core/src/location/mod.rs, core/src/object/fs/copy.rs, core/src/object/fs/cut.rs, core/src/object/fs/delete.rs, core/src/sync/manager.rs
Aside from the aforementioned Linear issues, this PR also fixes some other bugs related to file system operations that I found in the watcher, like when the watcher deletes a directory.
=> [ENG-743 / ENG-744] Duplicate item / Delete explorer item

core/src/api/tags.rs
=> Better tag unassign

interface/app/$libraryId/overview/index.tsx, interface/hooks/useExplorerTopBarOptions.tsx
- Hide list view on categories bcs it lags
- hide columns view bcs it doesn't exist
=> [ENG-786] Hide List view on categories and hide columns view

apps/desktop/src-tauri/Cargo.toml
=> Enable updater by default

core/src/api/utils/invalidate.rs, core/src/lib.rs, core/src/library/manager.rs, core/src/location/manager/mod.rs, interface/app/$libraryId/settings/client/general.tsx, interface/app/$libraryId/settings/resources/about.tsx
Message parsing with a response is cringe
Deadocks are such a pain to debug
You can clikc the Spacedrive logo on the about page 5 times in prod to enable the debug menu.
=> [ENG-792] App no starty

.github/actions/publish-artifacts/action.yaml
=> fix action

Cargo.lock, Cargo.toml, core/src/api/jobs.rs, core/src/job/manager.rs, core/src/job/mod.rs, core/src/lib.rs, core/src/library/manager.rs, core/src/location/file_path_helper/isolated_file_path_data.rs, core/src/location/file_path_helper/mod.rs, core/src/location/indexer/indexer_job.rs, core/src/location/indexer/mod.rs, core/src/location/indexer/walk.rs, core/src/location/mod.rs, core/src/object/file_identifier/mod.rs, interface/app/$libraryId/Layout/Sidebar/JobManager/JobGroup.tsx, interface/app/$libraryId/Layout/Sidebar/JobManager/index.tsx, packages/client/src/core.ts
=> [ENG-823] Fix some stuff

crates/ffmpeg/src/movie_decoder.rs
=> [ENG-828-FIX-2] Actually generate thumbnails

.github/workflows/ci.yml, CONTRIBUTING.md
This adds info on how to fix a **very** common issue that we keep having in the Discord.
=> [ENG-856] Additional debugging into contribution guidelines

.github/workflows/ci.yml, core/src/location/file_path_helper/isolated_file_path_data.rs
Found out that directories with dots in its name were being incorrectly handled.
=> [ENG-823] Fixing bad handling of dots in directory name

interface/app/$libraryId/Layout/index.tsx, interface/app/$libraryId/settings/library/locations/AddLocationDialog.tsx, interface/app/RootContext.tsx, interface/app/index.tsx, packages/client/src/hooks/usePlausible.tsx
=> [ENG-858] Source analytics paths from router rather than regex replacement

apps/desktop/src/App.tsx
=> Allow desktop to work offline

apps/landing/src/app/api/feedback/route.ts
=> Append emoji to feedback properly

interface/app/$libraryId/overview/Categories.tsx, interface/package.json, packages/ui/package.json, packages/ui/src/Button.stories.tsx, packages/ui/src/Dropdown.stories.tsx, packages/ui/src/Input.stories.tsx, packages/ui/src/Select.stories.tsx, pnpm-lock.yaml
https://github.com/spacedriveapp/spacedrive/assets/33054370/a88a39a9-e578-42ea-b78a-8bce4f3ef15d
=> [ENG-760] Overview draggable categories

interface/app/$libraryId/Layout/index.tsx, interface/app/$libraryId/overview/Categories.tsx
=> Refactor category scroll handlers

apps/landing/src/utils/util.ts
https://github.com/spacedriveapp/spacedrive/assets/9082460/2cf2490d-a3dc-4531-b95d-9852d57006a9
Closes #1025
=> Fix Brave `Aggressively block fingerprinting` mode

core/src/library/cat.rs, crates/file-ext/src/kind.rs
Adds Functionality to some Categories
Closes #1089
=> Add functionality to some Overview Catrgories

.github/workflows/server.yml
Replace Docker buildx and raw docker build script in Server CI with [redhat-actions/buildah-build](https://github.com/redhat-actions/buildah-build) and [redhat-actions/push-to-registry](https://github.com/redhat-actions/push-to-registry) actions
=> Fix server CI

apps/landing/posts/june-alpha-release.mdx
improving clarity by adding punctuation / rearranging sentences
These are only suggestions...
=> release blog post: clarifying punctuation & rearrange some sentences

core/src/library/manager.rs
Hopefully this will stop the `Connection timed out during query execution` error
=> SQLite connection limit

core/src/api/locations.rs, core/src/location/mod.rs, interface/app/$libraryId/Explorer/ParentContextMenu.tsx, interface/app/$libraryId/location/LocationOptions.tsx, packages/client/src/core.ts
Introducing a new rspc route to use expose the feature of scaning a location recursively given a sub path of that location as a starting point.
=> [ENG-875] Re-index & Re-thumb should be smart

crates/sync-generator/Cargo.toml
Compile error:
```
rror[E0635]: unknown feature `proc_macro_span_shrink`
--> /Users/xus/.cargo/registry/src/rsproxy.cn-8f6827c7555bfaf8/proc-macro2-1.0.59/src/lib.rs:92:30
|
92 |     feature(proc_macro_span, proc_macro_span_shrink)
|                              ^^^^^^^^^^^^^^^^^^^^^^
```
Reated iuuses: https://github.com/rust-lang/rust/issues/113152 and https://github.com/dtolnay/proc-macro2/pull/391
=> fix: unknown feature `proc_macro_span_shrink`

interface/app/$libraryId/Explorer/ContextMenu/FilePath/index.tsx, interface/app/$libraryId/Explorer/ContextMenu/Location/index.tsx, interface/app/$libraryId/Explorer/ContextMenu/Object/index.tsx, interface/app/$libraryId/Explorer/ContextMenu/index.tsx, interface/app/$libraryId/Explorer/index.tsx, interface/app/$libraryId/location/$id.tsx, interface/app/$libraryId/overview/index.tsx, packages/config/eslint/base.js
Introduces an `extra` render prop for customising the context menu, and injects the RemoveFromRecents option via it.
=> Fix remove from recents

.gitmodules
I recently added a lot more test files to the `test-files` repository (in order to test our media data extraction), and I've updated them wthin the core.
~~I may keep this as a draft and add more, as I recently collected a pretty decent dataset of images that are available on GDrive, but would be good for testing here too.~~ It turns out that that's 1.4GB while also being _heavily_ compressed.
=> Update `test-files` submodule within the `core`

apps/server/docker/Dockerfile
=> Update server Dockerfile due to crate name change

apps/desktop/src/App.tsx, interface/ErrorFallback.tsx, interface/components/AlertDialog.tsx, packages/ui/src/Dialog.tsx
=> [ENG-967] Reset confirmation for db sd reset

core/src/api/search.rs, packages/client/src/core.ts
=> [ENG-876] Show folders first in explorer

interface/ErrorFallback.tsx
=> [ENG-986] - Reset confirm dialog

Cargo.lock
Just updates to a newer commit of PCR that makes sure to format every file
=> Fix PCR formatting

apps/desktop/crates/linux/src/app_info.rs, apps/desktop/src-tauri/src/file.rs, apps/mobile/tests/onboarding.yml, core/src/api/backups.rs, core/src/api/jobs.rs, core/src/job/report.rs, core/src/library/manager/mod.rs, core/src/location/indexer/shallow.rs, core/src/location/indexer/walk.rs, core/src/location/manager/helpers.rs, core/src/location/manager/watcher/utils.rs, core/src/location/mod.rs, core/src/location/non_indexed.rs, core/src/object/orphan_remover.rs, core/src/object/preview/thumbnail/thumbnailer_job.rs, core/src/p2p/identity_or_remote_identity.rs, core/src/p2p/p2p_manager.rs, core/src/p2p/pairing/mod.rs, core/src/p2p/sync/mod.rs, core/src/volume/mod.rs, crates/file-ext/src/magic.rs, interface/app/$libraryId/Explorer/FilePath/LayeredFileIcon.tsx, interface/app/$libraryId/settings/library/tags/EditForm.tsx, interface/app/$libraryId/settings/library/tags/index.tsx, interface/components/AlertDialog.tsx, interface/components/TEXTViewer.tsx, packages/ui/src/Dialog.tsx, packages/ui/src/Input.tsx
Automatic formatting rust code due to new rules in rust fmt 1.72 + some Typescript format fixes from eslint/prettier
=> Formatting (Prettier + Rustfmt 1.72)

apps/desktop/src-tauri/Cargo.toml, apps/desktop/src-tauri/src/main.rs, core/src/preferences/library.rs, core/src/preferences/mod.rs, core/src/volume/mod.rs, crates/crypto/src/keys/keymanager.rs
Fix recent build errors due to Tauri build script not identifying that the updater features is enabled
=> Always enable tauri update + Misc Clippy warns fix

apps/desktop/src-tauri/Cargo.toml, core/src/api/search.rs, core/src/lib.rs, interface/app/$libraryId/Explorer/View/GridList.tsx, interface/app/$libraryId/Explorer/View/ListView.tsx, interface/app/$libraryId/Explorer/useExplorer.ts, interface/app/$libraryId/location/$id.tsx, interface/app/$libraryId/overview/data.ts, interface/app/$libraryId/overview/index.tsx, packages/client/src/core.ts
This PR doesn't alter pagination behaviours, but just fetches the number of items in a particular search and passes it along to the explorer accordingly. How we want to handle pagination can be figured out later.
=> [ENG-1009] Fetch item count to increase scrollbar size in explorer

interface/app/$libraryId/Layout/Sidebar/JobManager/JobContainer.tsx
=> [ENG-1016] Job name overflow

CONTRIBUTING.md, apps/desktop/package.json, pnpm-lock.yaml
`pnpm dlx` can do the job, no need for installing it as a dev dependency
=> Remove react devtools dependency

packages/client/src/utils/jobs/useJobInfo.tsx
=> Fix media processor job text

apps/desktop/src-tauri/Cargo.toml, apps/desktop/src-tauri/scripts/tauri.js, apps/desktop/src-tauri/src/main.rs, apps/desktop/src-tauri/tauri.conf.json
Hopefully resolves the release build issues
https://github.com/spacedriveapp/spacedrive/actions/runs/6015255188
=> Disable updater + add feature gate

interface/app/$libraryId/Layout/Sidebar/JobManager/index.tsx
- Confirmation dialog replaced with a nicer UI 
- Toast component on success or on error
https://github.com/spacedriveapp/spacedrive/assets/33054370/18dfa937-b16c-44c9-8488-5c1203cf3f78
=> [ENG-775] Jobs clearing improvement

.github/actions/publish-artifacts/action.yaml, .github/workflows/release.yml
=> Fixes release action

core/src/api/locations.rs, core/src/custom_uri.rs, core/src/job/mod.rs, core/src/location/indexer/mod.rs, core/src/location/manager/watcher/utils.rs, core/src/object/file_identifier/mod.rs, core/src/object/media/media_processor/mod.rs, core/src/object/media/media_processor/shallow.rs, crates/p2p/src/spaceblock/mod.rs
We were generating a bogus `cas_id` for empty files, sometimes it messed things up for empty files, like assigning the same thumbnail or messing the file object kind.
Closes #1172
=> [ENG-953] Zero-byte files occasionally receive a random thumbnail

interface/app/$libraryId/Explorer/FilePath/RenameTextBox.tsx, interface/app/$libraryId/Layout/Sidebar/FeedbackDialog.tsx, interface/app/$libraryId/Layout/Sidebar/JobManager/index.tsx, interface/app/$libraryId/Layout/Sidebar/TagsContextMenu.tsx, interface/app/$libraryId/settings/library/tags/CreateDialog.tsx, packages/ui/src/Dialog.tsx
- Enter key submits the form within the dialog.
- Dialog only closes if form is valid and successful.
=> [ENG-809] Enter key submits dialog

apps/desktop/src/index.html, apps/landing/src/utils/contentlayer.ts, apps/storybook/index.html, apps/web/src/index.html, core/src/api/files.rs, core/src/location/mod.rs, core/src/object/media/thumbnail/mod.rs, crates/media-metadata/src/error.rs, crates/media-metadata/src/image/reader.rs, crates/sync/example/web/index.html, interface/app/$libraryId/Explorer/FilePath/Thumb.tsx, interface/app/$libraryId/Explorer/Inspector/index.tsx, interface/app/$libraryId/Explorer/View/GridList.tsx, interface/app/$libraryId/Explorer/store.ts, interface/app/$libraryId/Layout/Sidebar/JobManager/JobContainer.tsx, interface/app/$libraryId/settings/library/locations/AddLocationDialog.tsx, interface/app/$libraryId/settings/library/locations/index.tsx, interface/app/$libraryId/sync.tsx, interface/components/Accordion.tsx, packages/assets/scripts/generate.mjs, packages/client/src/core.ts, packages/config/vite/index.ts, packages/ui/src/Dropdown.tsx
New rspc route to extract media data from a non-indexed file on demand
Fixing some minor stuff
Running pnpm format
=> [ENG-1028] Media data for ephemeral locations

.gitignore, apps/desktop/package.json, apps/desktop/vite.config.ts, packages/config/vite/index.ts, pnpm-lock.yaml
Enables sourcemaps for web & desktop builds and automatically publishes them.
=> [ENG-1072] Connect sentry with sourcemaps

.github/workflows/release.yml, .npmrc
not enough ram? give more ram :)
=> [ENG-1073] Fix Vite running out of memory in release builds

apps/storybook/package.json, apps/storybook/postcss.config.js, packages/ui/src/Button.stories.tsx, packages/ui/src/Button.tsx, packages/ui/src/Dialog.tsx, pnpm-lock.yaml
- Improved styling of focus buttons feat.Brendans opinion on styling.
- Added buttons to storybook.
- Added a new plugin for postcss of storybook.
=> [ENG-1044] Focus buttons styling + storybook

apps/desktop/src-tauri/src/file.rs, core/src/api/backups.rs, core/src/api/libraries.rs, core/src/api/nodes.rs, core/src/library/library.rs, core/src/library/manager/mod.rs, core/src/location/manager/helpers.rs, core/src/location/manager/mod.rs, core/src/location/mod.rs, core/src/p2p/pairing/mod.rs, core/src/util/debug_initializer.rs, interface/app/$libraryId/settings/Layout.tsx, interface/app/$libraryId/settings/library/general.tsx
Imagine trying to mutate an `Arc<Library>` and wondering why it's not working 🤦
=> [ENG-1036] Fix library rename

Cargo.lock, apps/desktop/src-tauri/src/tauri_plugins.rs, core/Cargo.toml, core/src/custom_uri.rs
Proper streaming from file on disk to the network so WebKit's viewer doesn't crash on large video files.
=> [ENG-1055] Fix previewing large files

apps/mobile/src/components/drawer/DrawerContent.tsx, apps/mobile/src/components/modal/job/JobManagerModal.tsx, apps/mobile/src/screens/onboarding/context.tsx, interface/app/$libraryId/Layout/Sidebar/JobManager/index.tsx
gotta use memo, related to #1306
=> Fix mobile by using memo

interface/app/$libraryId/Explorer/Inspector/MediaData.tsx, interface/app/$libraryId/Explorer/Inspector/index.tsx, packages/ui/src/Tooltip.tsx
https://github.com/spacedriveapp/spacedrive/assets/21004798/916d0f04-3479-4fbc-95fb-49c61bd3db0b
=> Improve Location Formatting in UI

interface/package.json, pnpm-lock.yaml
We had an outdated SDK version 🤦
=> Fix Sentry sourcemaps

interface/app/$libraryId/Explorer/View/index.tsx, interface/app/$libraryId/Explorer/useExplorer.ts, interface/app/$libraryId/location/$id.tsx, interface/components/Loader.tsx, interface/components/index.ts
This is quite a useful PR
- We show a loading indicator if loading time is greater than 100ms. Has been tested and fits the job well. **We don't want to show a loading indicator if the loading is too fast.**
This is useful for when you scroll 10+ pages using the scrollbar.
=> [ENG-1020] Explorer loading indicator

.vscode/extensions.json
=> Update recommended VS Code extensions

crates/media-metadata/src/image/geographic/pluscodes.rs
=> Fix builds and make `String` -> `PlusCode` validation more generic (Google support)

interface/app/style.scss, packages/ui/style/colors.scss, packages/ui/style/tailwind.js
Added colors for the scrollbar within the theme.
- Now the color is better, and more visible.
=> [ENG-1021] Explorer Scrollbar color

interface/app/style.scss
=> [ENG-1085] Text view rounded scrollbar

apps/landing/src/components/NavBar.tsx
Reorder mobile navbar links to match web navbar.
Closes #(issue)
=> Reorder navbar

interface/app/$libraryId/settings/Sidebar.tsx, interface/app/$libraryId/settings/client/keybindings.tsx
Credit goes to @PineappleRind for doing the work.
All I did was modify the styling abit and add more shortcuts. This is subject to updates once I work on a new hook for dealing with symbols.
=> [ENG-815] Shortcuts page

interface/app/$libraryId/Explorer/TopBarOptions.tsx, interface/app/$libraryId/Explorer/View/index.tsx, interface/app/$libraryId/Layout/Sidebar/Footer.tsx, interface/app/$libraryId/TopBar/NavigationButtons.tsx, interface/app/$libraryId/TopBar/TopBarOptions.tsx, interface/hooks/index.ts, interface/hooks/useKeyMatcher.ts
Instead of importing same imports in different places and matching symbols/keys based on OS, i created a hook to handle this.
It returns an object with the icon and key, which means it's flexible to also support using with creating shortcuts.
=> [ENG-1126] Key matcher hook

core/prisma/migrations/20230921203938_add_size_bytes_in_location_table/migration.sql, core/prisma/schema.prisma, core/src/location/indexer/indexer_job.rs, core/src/location/indexer/shallow.rs, core/src/location/manager/watcher/utils.rs, core/src/location/mod.rs, interface/app/$libraryId/settings/library/locations/ListItem.tsx, packages/client/src/core.ts
Now that we have accurate directories calculation for an entire location, it's pretty easy to have a full location size.
=> [ENG-1135] Locations: Total size query and return to Frontend

interface/app/$libraryId/Explorer/FilePath/RenameTextBox.tsx, packages/ui/src/Tooltip.tsx
=> [ENG-1133] Tooltip overflow fix - take up y-axis space

.vscode/settings.json, interface/app/$libraryId/Explorer/View/ExplorerPath.tsx, interface/app/$libraryId/Explorer/View/index.tsx
- Supports both Ephemeral and Indexed locations
- Directory navigation
=> [ENG-1112] Explorer Path Component

core/prisma/migrations/20230926180932_remove_device_from_file_path_table/migration.sql, core/prisma/schema.prisma, core/src/location/file_path_helper/mod.rs, core/src/location/indexer/mod.rs, core/src/location/indexer/walk.rs, core/src/location/manager/watcher/macos.rs, core/src/location/manager/watcher/mod.rs, core/src/location/manager/watcher/utils.rs, core/src/location/manager/watcher/windows.rs, core/src/util/db.rs, packages/client/src/core.ts
Removing device data from file_path as it can change overtime for a location mounted over SMB for example
=> [ENG-1140] Bind an entire location to a single device number

interface/app/$libraryId/TopBar/NavigationButtons.tsx
=> [ENG-1148] Fix inputs

interface/app/$libraryId/Explorer/FilePath/Thumb.tsx, interface/app/$libraryId/Explorer/OptionsPanel.tsx, interface/app/$libraryId/Explorer/View/ExplorerPath.tsx, interface/app/$libraryId/Explorer/View/GridList.tsx, interface/app/$libraryId/Explorer/View/ListView/index.tsx, interface/app/$libraryId/Explorer/View/index.tsx, interface/app/$libraryId/Explorer/View/util.ts, interface/app/$libraryId/Explorer/ViewContext.ts, interface/app/$libraryId/Explorer/index.tsx, interface/app/$libraryId/settings/client/keybindings.tsx, interface/app/style.scss, interface/components/GridList.tsx, packages/client/src/hooks/index.ts, packages/client/src/hooks/useExplorerLayoutStore.ts
- Keyboard shortcut to toggle path bar. **[Meta + P]** MacOS, Windows and other **[CTRL + P]**
- New explorer layout store to manage this, as we make explorer layout more customizable now and in the future.
- Added this shortcut to keybinds page.
=> [ENG-1142] Path bar shortcut

interface/app/$libraryId/Explorer/Inspector/MediaData.tsx, interface/app/$libraryId/Explorer/Inspector/index.tsx, interface/app/$libraryId/Explorer/TopBarOptions.tsx, interface/app/$libraryId/Explorer/store.ts, interface/components/Accordion.tsx
This keeps 'More Info' open if it is toggled.
=> [ENG-1145] Keep more info open if it is

interface/app/$libraryId/settings/OverviewLayout.tsx, interface/app/$libraryId/settings/library/general.tsx, interface/app/$libraryId/settings/resources/about.tsx
- Add consistent bottom padding to each settings page (make bottom padding block div unshrinkable)
- Remove extra padding on Library -> General page
- Remove extra bottom padding on Resources -> About page
=> settings pages: consistent padding on every side

package.json
=> Fix nodejs supported version in engine field

interface/app/$libraryId/overview/Statistics.tsx, interface/app/$libraryId/settings/client/SpacedriveAccount.tsx
They don't count up in the first render.
=> [ENG-1147] Fix overview stats

.github/actions/setup-pnpm/action.yml, .github/workflows/release.yml, CONTRIBUTING.md, docs/developers/prerequisites/environment-setup.mdx, package.json, packages/client/src/hooks/useExplorerLayoutStore.ts, packages/ui/src/Button.tsx, packages/ui/src/ContextMenu.tsx, packages/ui/src/Switch.tsx, scripts/deps.mjs, scripts/github.mjs
- Fix documentation and some scripts to use the new tauri subcommand following https://github.com/spacedriveapp/spacedrive/pull/1411 changes
- Document new environment variable that lauchs devtools alongside the desktop app
- Format/Lint some files
=> Change docs and CI scripts to use `pnpm tauri` command

interface/app/$libraryId/Explorer/useExplorer.ts, interface/app/$libraryId/location/$id.tsx
This PR fixes the bug in the following video:
https://github.com/spacedriveapp/spacedrive/assets/33054370/9059dce6-4ede-436e-9a82-25f8e6b9a9a2
=> [ENG-989] Switch explorer views bug

interface/app/$libraryId/settings/library/locations/AddLocationDialog.tsx, interface/components/Accordion.tsx
=> Fix accordion

core/src/api/search.rs, core/src/preferences/library.rs, interface/app/$libraryId/Explorer/OptionsPanel.tsx, interface/app/$libraryId/Explorer/store.ts, interface/app/$libraryId/location/$id.tsx, packages/client/src/core.ts
=> [ENG-888] Media view should show current folder downward

interface/index.tsx, packages/ui/src/Tooltip.tsx
Makes tooltips open instantly if another tooltip was open just before
=> Move tooltip provider to app root instead of component root

interface/app/$libraryId/settings/library/locations/AddLocationDialog.tsx, interface/components/Accordion.tsx, packages/ui/src/Dialog.tsx
- Adjusted accordian container color back to what it was previously.
- Width of location dialog adjusted so that the transition isn't weird when you toggle.
**Before**:
https://github.com/spacedriveapp/spacedrive/assets/33054370/a5c91725-9d12-41ed-b6fe-00c15434394c
**After**:
https://github.com/spacedriveapp/spacedrive/assets/33054370/75047a7e-2744-40af-8bcb-eb7b76cedcf4
=> [ENG-1202] Location dialog visual improvements

apps/landing/src/pages/careers.tsx
This PR conditionally displays "If any open positions suit you, apply now!" so that it is only shown when there are open positions.
I was browsing the careers page and noticed that I was encouraged to apply even when there weren't open positions! 🥲
=> chore: conditionally encourage applications based on open positions

interface/app/$libraryId/Layout/Sidebar/FeedbackDialog.tsx
This is a quick fix to the issue where you click cancel and the form error appears.
=> [ENG-1216] Feedback dialog form bug

interface/app/$libraryId/Explorer/useExplorer.ts
This makes sure preferences/settings update correctly, this was done for layoutMode, but now applies to all.
=> [ENG-1217] Fix update delay and debouncing settings

apps/desktop/src/commands.ts, interface/app/$libraryId/location/$id.tsx, interface/app/$libraryId/overview/data.ts, interface/app/$libraryId/tag/$id.tsx
unifies the search logic for tag route so we can have proper pagination and stuff ya know
=> useObjectsInfiniteQuery in tag route

apps/desktop/src/index.html, core/src/custom_uri/mod.rs, core/src/custom_uri/utils.rs, interface/app/$libraryId/Explorer/FilePath/Thumb.tsx, interface/app/$libraryId/Explorer/OptionsPanel.tsx, interface/app/$libraryId/Explorer/QuickPreview/index.tsx, interface/app/$libraryId/Explorer/View/GridView.tsx, interface/app/$libraryId/Explorer/useExplorer.ts, interface/app/$libraryId/Layout/Sidebar/EphemeralSection.tsx, interface/app/$libraryId/Layout/Sidebar/FeedbackDialog.tsx, interface/app/$libraryId/location/$id.tsx, interface/app/$libraryId/settings/library/locations/AddLocationDialog.tsx, packages/client/src/utils/explorerItem.ts, packages/ui/src/Toast.tsx
Show toast when Original file fails loading in QuickPreview
https://github.com/spacedriveapp/spacedrive/assets/9082460/7ebf4379-d3c5-4922-ac56-4e4ed65718f1
=> [ENG-1086, ENG-1087] Add error and loading indicator to thumbnail

Cargo.lock, apps/desktop/src-tauri/Cargo.toml
should be the final PR for 0.1.0
=> sd-desktop@0.1.0

interface/app/$libraryId/Explorer/store.ts
=> big bad bug fix moment

apps/landing/posts/october-alpha-release.mdx, apps/landing/src/pages/index.tsx, apps/landing/src/pages/roadmap.tsx, docs/changelog/alpha/0.1.0.mdx
=> Landing page links

apps/landing/src/pages/index.tsx
Just https://github.com/spacedriveapp/spacedrive/pull/1076 again
=> Fix landing page not working without WebGL

apps/mobile/src/screens/onboarding/GetStarted.tsx, interface/app/onboarding/Layout.tsx
=> Fix copyright text

apps/landing/src/components/Footer.tsx
@utkubakir sorry about that had forgot to enable the links.
=> enabled footerlinks

apps/landing/src/app/api/releases/desktop/[version]/[target]/[arch]/route.ts, apps/landing/src/pages/index.tsx
- Improve how landing chooses the download link
- Fix Linux download text
- Add deb download button
=> Minor landing changes (Fix linux download text)

interface/hooks/useKeyboardHandler.ts
Closes https://github.com/spacedriveapp/spacedrive/issues/1483
=> fix: setting item in menu bar

apps/landing/src/app/api/releases/desktop/[version]/[target]/[arch]/route.ts, apps/landing/src/pages/index.tsx
=> AppImage only + clickable OSes

interface/app/$libraryId/overview/Statistics.tsx
Will PR a collection of fixes in a separate PR.
=> [ENG-1245] Fix stats tooltip color

interface/app/$libraryId/Explorer/FilePath/RenameTextBox.tsx, interface/app/$libraryId/Explorer/View/ListView/index.tsx, interface/hooks/useIsTextTruncated.ts, packages/ui/src/Tooltip.tsx
=> [ENG-1236] fix mac tooltips on truncated folder names is inconsistent

apps/landing/src/components/CyclingImage.tsx, apps/landing/src/components/Space.tsx, apps/landing/src/pages/index.tsx
- Only happes on chrome, but not Safari, or Arc.
=> [ENG-1242] Landing page lag

apps/landing/posts/october-alpha-release.mdx
=> Blog tweak

interface/app/onboarding/alpha.tsx, interface/app/onboarding/index.tsx
It just scares people and we don't even have a cloud yet, so let's get rid of it.
=> Remove login from onboarding

interface/app/$libraryId/Explorer/View/ExplorerPath.tsx
This fixes explorer path bar for windows.
Has been tested on Windows and Mac.
=> [ENG-1254] Fix explorer path bar for windows

interface/app/$libraryId/Layout/Sidebar/Footer.tsx, interface/app/$libraryId/settings/client/keybindings.tsx
In windows, shift ctrl s takes a screenshot, decided to replace S with T to address this.
=> [ENG-1257] Replace S with T for settings page shortcut

interface/app/$libraryId/Explorer/View/GridList.tsx
=> [ENG-1259] windows ephemeral locations keyboard nav fix

interface/app/$libraryId/ephemeral.tsx
=> [ENG-1261] Fix AddLocationButton on ephemeral locations

docs/company/branding/typeography.mdx, docs/company/branding/typography.mdx
=> Update and rename typeography.mdx to typography.mdx

interface/app/$libraryId/Explorer/FilePath/RenameTextBox.tsx, interface/app/$libraryId/Explorer/View/GridList.tsx, interface/app/$libraryId/Explorer/View/GridView.tsx, interface/app/$libraryId/Explorer/View/ListView/index.tsx, interface/app/$libraryId/Explorer/View/RenamableItemText.tsx, interface/package.json, pnpm-lock.yaml
=> [ENG-1264] Improve file name truncating

interface/app/$libraryId/Explorer/TopBarOptions.tsx, interface/app/$libraryId/Explorer/View/ExplorerPath.tsx, interface/app/$libraryId/TopBar/TopBarOptions.tsx, interface/app/$libraryId/settings/client/keybindings.tsx
This changes explorer views shortcuts to ctrl/meta 1,2, and 3.
=> [ENG-1273] Update explorer views shortcut

interface/app/$libraryId/Explorer/ContextMenu/SharedItems.tsx
=> [ENG-1277] Windows open context menu key correction

interface/app/$libraryId/Layout/Sidebar/JobManager/index.tsx, interface/app/$libraryId/TopBar/TopBarOptions.tsx
Before:
https://github.com/spacedriveapp/spacedrive/assets/65303441/1d445ed4-2795-49bd-bbfe-3986b1894af8
After:
https://github.com/spacedriveapp/spacedrive/assets/65303441/dc61b8b3-7dfe-45a0-9293-d62c90f2ef06
Before:
After:
=> some light mode fixes

interface/app/$libraryId/Explorer/View/index.tsx, interface/hooks/index.ts, interface/hooks/useKeyCopyCutPaste.ts, interface/hooks/useKeyCopyPaste.ts
This pr adds copy, pasting, and cutting shortcuts.
=> [ENG-1288] Copy, cut, and paste shortcuts

apps/landing/src/app/Downloads.tsx
This PR update the release version on website.
Closes #1598
=> fix: update release version

interface/app/$libraryId/Explorer/Inspector/index.tsx
In inspector, the location of an object is now clickable to take you to that location.
=> [ENG-1226] Link locations button in inspector

scripts/setup.sh
added a single missing g for one of the `dnf` packages during installation
=> really small typo fix

Cargo.lock, crates/images/Cargo.toml, crates/images/src/consts.rs, packages/client/src/core.ts
=> Enable thumbnail support for webp images

Cargo.lock, apps/desktop/src-tauri/Cargo.toml, apps/desktop/src-tauri/src/main.rs
`tauri-plugin-window-state` ez
=> [ENG-1328] Persist window position

interface/app/$libraryId/settings/Setting.tsx, interface/app/$libraryId/settings/client/SpacedriveAccount.tsx, interface/app/$libraryId/settings/client/general.tsx
This adds buttons for port, with a dropdown for default and custom.
=> [ENG-1315] Port buttons

crates/p2p/src/manager_stream.rs
=> [ENG-1331] Fix app startup without IPv6 network stack

interface/app/$libraryId/Explorer/store.ts
Now hidden files work properly, this hot fix can go.
=> Show hidden files false by default

apps/desktop/src/env.ts
=> Use www.spacedrive.com instead of spacedrive.com

apps/landing/src/app/api/slack/webhook/route.ts
=> [ENG-1339] Don't allow releasing if branch with same name already exists

interface/app/$libraryId/Explorer/View/index.tsx, interface/app/$libraryId/location/$id.tsx, interface/hooks/index.ts, interface/hooks/useIsLocationIndexing.ts
Has been modified to when `completed_task_count` is 0 rather than being completed to offer a faster experience and files/folders will just come in.
https://github.com/spacedriveapp/spacedrive/assets/33054370/25d8d29d-3ba3-447e-91aa-3d15e51b7bc9
=> [ENG-1327] Loading indicator if a location is indexing

apps/landing/src/app/api/slack/webhook/auth.ts, apps/landing/src/app/api/slack/webhook/createRelease.ts, apps/landing/src/app/api/slack/webhook/github.ts, apps/landing/src/app/api/slack/webhook/route.ts, apps/landing/src/app/api/slack/webhook/utils.ts, apps/landing/src/env.ts
Refactors the slash command to create a modal that requires inputting both the category and tagline. Will help avoid a situation like last release 💀
=> [ENG-1342] Prompt for tagline and category when creating release

interface/app/$libraryId/Explorer/index.tsx, interface/app/$libraryId/Explorer/useKeyRevealFinder.ts, interface/app/$libraryId/settings/client/keybindings.tsx, interface/hooks/useKeyRevealFinder.ts
Shortcut to reveal in explorer/finder
**Tested on**: Windows & MacOS
=> [ENG-1354] Shortcut to reveal in finder/explorer

apps/landing/src/app/api/slack/webhook/createRelease.ts
=> Individually quote each line of release modal commit message

apps/desktop/src-tauri/src/menu.rs, interface/app/$libraryId/settings/client/account.tsx
We couldn't copy/paste/undo/redo any text within any UI elements, now it works.
- Also did a minor adjustment for account page.
=> [ENG-1361] MacOS fix copy, paste, undo, redo, select all functionality

README.md
changed "Twitter" Logo "𝕏"
Closes #(issue)
This closes https://github.com/spacedriveapp/spacedrive/issues/1691
=> fix: changed "Twitter" Logo "𝕏" in README.md

.github/actions/setup-system/action.yml, .github/workflows/ci.yml, scripts/setup.ps1, scripts/setup.sh
Add `Nasm` to `setup.sh` and `setup.ps1`, as it is now required to compile the `openssl-sys` crate
=> Fix Windows CI

apps/landing/src/app/api/github/webhook/route.ts, apps/landing/src/app/api/releases/[version]/route.ts, apps/landing/src/app/api/releases/route.ts, apps/landing/src/app/docs/changelog/[category]/[tag]/page.tsx, apps/landing/src/app/docs/changelog/data.ts
looks like landing fixed itself but making these changes just in case
=> Urgent landing page fixes

interface/app/$libraryId/Explorer/ParentContextMenu.tsx, interface/app/$libraryId/Explorer/TopBarOptions.tsx
=> [ENG-1240] New folder context menu

apps/mobile/app.json, interface/app/$libraryId/Explorer/ContextMenu/FilePath/CutCopyItems.tsx, interface/app/$libraryId/Explorer/ParentContextMenu.tsx, interface/app/$libraryId/Explorer/TopBarOptions.tsx, interface/app/$libraryId/Explorer/useExplorer.ts, interface/app/$libraryId/settings/client/general.tsx, interface/app/$libraryId/settings/library/nodes.tsx, interface/app/$libraryId/settings/library/tags/CreateDialog.tsx
Add Android permission, organize imports, add toast for tag assign button
=> No placeholder buttons

apps/landing/src/app/api/releases/route.ts, interface/app/$libraryId/settings/resources/changelog.tsx
~~also gotta fix the api route~~
=> Fix changelog size

apps/landing/src/app/docs/Sidebar/Search.tsx, apps/landing/src/app/docs/layout.tsx, apps/landing/src/styles/search.scss
https://github.com/vercel/next.js/issues/13092 =_= this should do it
=> [ENG-1406] Fix search bar take 2

interface/app/$libraryId/Explorer/View/ExplorerPath.tsx, interface/app/$libraryId/tag/$id.tsx
Adds support for tag routes, for explorer path component.
=> [ENG-1167] Explorer path tags route

interface/app/$libraryId/Explorer/View/ExplorerPath.tsx
Fixes initial navigation after a reload from tag routes.
=> [ENG-1417] Explorer path nav fix from tag routes

interface/app/$libraryId/settings/library/tags/CreateDialog.tsx
=> Fix closing tag window

interface/app/index.tsx
=> fix dialogs

interface/app/$libraryId/Explorer/Search/index.tsx
=> [ENG-1439] Align search option internals

interface/app/$libraryId/TopBar/index.tsx
=> [ENG-1440] Move tab bar to below main top bar content

interface/app/$libraryId/Explorer/Search/AppliedFilters.tsx, interface/app/$libraryId/Explorer/Search/index.tsx
=> [ENG-1441] Fix search filters overflow

interface/app/$libraryId/Explorer/View/ListView/index.tsx
Table header gets stuck after search filters bar is closed
=> [ENG-1444] Fix list view observer

interface/app/$libraryId/Explorer/Search/index.tsx, interface/app/$libraryId/Explorer/Search/store.tsx
Kinda dirty but does the job for clearing the search store when we're done searching
=> [ENG-1443] Reset search store on search bar unmount

interface/app/$libraryId/Explorer/Search/Context.tsx, interface/app/$libraryId/ephemeral.tsx, interface/hooks/useZodSearchParams.ts
=> Use raw search params for search data in url

interface/app/$libraryId/Layout/Sidebar/EphemeralSection.tsx, interface/app/$libraryId/Layout/Sidebar/LibrarySection.tsx, interface/app/$libraryId/Layout/Sidebar/SeeMore.tsx, interface/app/$libraryId/Layout/index.tsx, interface/app/$libraryId/index.tsx, interface/app/index.tsx, interface/hooks/useHomeDir.ts
Makes 'Home' the default route if it's available, falling back to 'Network' if not.
Also refactors the `SeeMore` component to use `React.Children` rather than the `items` array, as this allows for JSX to be used directly.
=> [ENG-1452] Default to Home

interface/app/$libraryId/settings/client/keybindings.tsx, interface/hooks/useShortcut.ts
Temporary solution. There will be a v3 later.
=> [ENG-1395] Use data from shortcuts hook

crates/images/src/error.rs, crates/images/src/pdf.rs
Make each pdf thumb task use a separate pdfium instance to ensure no concurrency problems may arise
=> Fix some possible pdf thumb rendering concurrency bugs

interface/app/$libraryId/settings/Setting.tsx, interface/app/$libraryId/settings/client/general.tsx, packages/ui/src/Select.tsx
Corrects sizing of elements, and alignment. Also removed an un-necessary useEffect.
=> [ENG-1456] General UI Tweaks

crates/images/src/pdf.rs
- Workaround an issue in the BGR to RGB conversion in pdfium-render crate
https://github.com/ajrcarey/pdfium-render/issues/119
- Disabled some pdf render configs for better performance
Closes #1816
=> Fix pdf thumbs having incorrect colors

interface/app/$libraryId/Search/Filters.tsx
- Wrapped with a form to support enter on keyboard
- Fixed padding
=> [ENG-1465] Search filters: padding fix and submit

interface/app/$libraryId/settings/resources/about.tsx, interface/app/$libraryId/settings/resources/changelog.tsx
=> [ENG-1464] Fix changelog color for light mode and icon in about

interface/app/$libraryId/settings/client/general.tsx
=> remove fda setting

interface/app/$libraryId/Explorer/ContextMenu/FilePath/Items.tsx, interface/hooks/useKeyMatcher.ts, packages/ui/src/keys.ts
Added more icons and keys in the key matcher hook that we should support + improved types.
=> [ENG-1430] Improve keymatcher hook

interface/app/$libraryId/settings/Sidebar.tsx, interface/app/$libraryId/settings/client/account.tsx, interface/app/$libraryId/settings/client/index.ts, interface/app/$libraryId/settings/client/usage.tsx, interface/components/AuthRequiredOverlay.tsx
=> [ENG-1463] Move statistics to a new usage page

interface/app/$libraryId/Layout/Sidebar/LibrarySection.tsx
=> [ENG-1468] Center "delete saved search" button

interface/app/$libraryId/Search/AppliedFilters.tsx, interface/app/$libraryId/Search/index.tsx
**Demonstration of this change can be seen in the video**
https://github.com/spacedriveapp/spacedrive/assets/33054370/83da7b73-00c1-4f08-8a4b-43669c8bd385
=> [ENG-1470] Search filters masking & fade

interface/app/$libraryId/Explorer/OptionsPanel.tsx, interface/app/$libraryId/Explorer/QuickPreview/index.tsx
=> [ENG-1469] Show slider button

apps/desktop/src-tauri/src/file.rs, core/src/volume/mod.rs
=> Resolve warnings instead of suppressing them

interface/app/$libraryId/settings/library/locations/AddLocationDialog.tsx
Updated it to use Radix instead of the white one that we have.
=> [ENG-1496] Add location checkbox 

apps/web/src/App.tsx, interface/app/$libraryId/Layout/Sidebar/Contents.tsx, interface/app/$libraryId/Layout/Sidebar/index.tsx, interface/app/$libraryId/TopBar/index.tsx, interface/app/$libraryId/settings/Sidebar.tsx
- Hides NavigationButtons on web
- Corrects library picker styling on web
- Handles router events properly on web
=> Unify sidebar styling

Cargo.lock, Cargo.toml, apps/desktop/src-tauri/Cargo.toml, core/Cargo.toml, core/src/lib.rs
Did this to test out - https://devtools.crabnebula.dev
This also means we can now ~~probably~~ (definitely, holly hell Prisma puts out some logs) see rspc and PCR logs which will help with debugging.
=> Upgrade tracing

interface/app/$libraryId/Search/AppliedFilters.tsx, interface/app/$libraryId/Search/Filters.tsx, interface/app/$libraryId/Search/index.tsx
**A simple PR that does the following:**
- Prevent duplicate name/extension queries
- Wrap save search with a form to support pressing enter, on submit closes popover.
=> [ENG-1497] Save search enter key support, no duplicate queries

interface/app/$libraryId/Explorer/FilePath/Thumb.tsx
Resolves file thumb types better, reducing flicker in quick preview
=> Better file thumb handling

Cargo.toml
=> Building dependencies with optimization on dev builds

apps/desktop/src/patches.ts, packages/client/src/index.ts, packages/client/src/rspc-cursed.ts
Fix error when running the mobile app.
Thanks @ameer2468 for pointing it out!
=> Fix mobile app

interface/hooks/useShortcut.ts
=> fix keybinds page

interface/app/$libraryId/Explorer/QuickPreview/index.tsx
Remove from from quick preview thumb image
=> Quick preview: remove border from thumb image

core/crates/sync/src/ingest.rs
Adds a transaction around some important db logic in the sync ingester
=> Use transaction in sync ingest

apps/desktop/src/platform.ts, interface/app/$libraryId/Explorer/TopBarOptions.tsx, interface/app/$libraryId/Search/Filters.tsx, interface/app/$libraryId/Search/index.tsx
**This PR improves the UI of search and the search results.**
- Better scrollbar than default web.
- You can now actually scroll the entire search results, previously scrollbar would get stuck.
- All results are now aligned due to set widths.
- Empty tags state
=> [ENG-1537] Search UI improvements

interface/app/$libraryId/Explorer/FilePath/Image.tsx, interface/app/$libraryId/Explorer/FilePath/Thumb.tsx
=> [ENG-1545] Remove cover prop from img tag

interface/app/$libraryId/overview/Layout/HorizontalScroll.tsx, interface/app/$libraryId/overview/Layout/Section.tsx, interface/app/$libraryId/overview/index.tsx, interface/app/$libraryId/search/AppliedFilters.tsx, interface/app/$libraryId/search/SearchOptions.tsx
This PR adds drag support for search filters.
=> [ENG-1542] Drag support for search filters

interface/app/$libraryId/Layout/index.tsx, packages/client/src/lib/explorerItem.ts, packages/ui/src/Input.tsx
=> [ENG-1547] Fix strange blue line in input

apps/landing/package.json, apps/storybook/package.json, interface/package.json, packages/ui/package.json, pnpm-lock.yaml
New features are great: https://tailwindcss.com/blog/tailwindcss-v3-4
=> update tailwindcss to 3.4

interface/app/$libraryId/overview/StatCard.tsx, packages/ui/src/CircularProgress.tsx
+ some minor improvement to the logic
=> Fix NaN progress on first stats data for StatCard

interface/app/$libraryId/Explorer/View/MediaView/Item.tsx
=> [ENG-1554] Reduce icon size on media view

crates/cache/src/lib.rs
There was a TODO comment to implement `Hash`, `PartialEq`, and `Eq` for the `CacheNode` struct. They can't be `derived` due to the nested types not implementing them, so I've manually written implementations.
For hashing `serde::Value`, it is first converted to an `str` (which does implement `Hash`).
For comparing `Arc<serde_json::Error>`, the inner value is used, not the Arc itself. 
Closes #1963
=> Implement Hash, PartialEq, and Eq for CacheNode

interface/app/$libraryId/Explorer/View/ViewItem.tsx, interface/app/$libraryId/search/AppliedFilters.tsx, interface/app/$libraryId/search/Filters.tsx, interface/app/$libraryId/search/SearchOptions.tsx, interface/app/$libraryId/search/store.tsx
Navigates to `/search` with the appropriate search params when a label is double clicked
=> Add double-click functionality for labels in explorer

README.md, core/src/location/indexer/indexer_job.rs, interface/ErrorFallback.tsx, interface/app/I18n.ts, project.inlang/settings.json
=> Fix plugin

interface/app/$libraryId/overview/Layout/HorizontalScroll.tsx, interface/app/$libraryId/overview/index.tsx, interface/app/$libraryId/settings/client/appearance.tsx
This PR adds a better scrolling experience for themes.
- Attached a listener for window resize aswell for HorizontalScroll component so that arrows don't show if you resize the window.
=> [ENG-1566] Better experience for themes

interface/app/$libraryId/overview/NewCard.tsx, interface/app/$libraryId/overview/index.tsx
This PR fixes the cloud images disappearing after navigating away. I can't explain why this works, it just does.
=> [ENG-1571] - Cloud images disappearing fix

interface/app/$libraryId/Explorer/FilePath/Thumb.tsx, interface/app/$libraryId/Explorer/FilePath/useFrame.tsx, interface/app/$libraryId/Explorer/View/GridView/Item/index.tsx
=> [ENG-1576] Fix label thumb

interface/app/$libraryId/search/index.tsx
=> [ENG-1581] Correct search results icon

interface/app/$libraryId/Explorer/View/index.tsx
=> [ENG-1583] Fix context menu closing when multiple tabs are open

interface/app/$libraryId/TopBar/index.tsx, interface/app/$libraryId/settings/library/locations/IndexerRuleEditor/index.tsx, interface/hooks/useShortcut.ts
- Adds tabs keybinds to shortcuts page.
- Fixes an issue where a user with a potentially older system encountered a bug with object.hasOwn method.
=> [ENG-1582 + ENG-1586] Add tab keybinds to shortcut + object.hasOwn bug fix

core/src/api/locations.rs, core/src/library/library.rs, core/src/library/manager/mod.rs, core/src/location/indexer/indexer_job.rs, core/src/location/indexer/shallow.rs, core/src/location/mod.rs, core/src/object/fs/delete.rs
deleting objects willy nilly is honestly not a great idea, we should be more explicit about it. i haven't removed it for posterity but i don't see us bringing it back.
=> disable orphan remover

apps/mobile/src/components/settings/SettingsItem.tsx, apps/mobile/src/navigation/TabNavigator.tsx, apps/mobile/src/screens/settings/Settings.tsx, apps/mobile/tests/onboarding.yml
This PR implements the new design of settings screen.
=> [MOB-48] Settings screen redesigned

apps/mobile/tests/onboarding.yml
=> mobile ci fix 

Cargo.lock, interface/app/$libraryId/settings/client/general.tsx, interface/app/I18n.ts
=> Fix Chinese language

core/prisma/schema.prisma, core/src/api/files.rs, core/src/api/search/saved.rs, core/src/api/tags.rs, core/src/library/config.rs, core/src/location/indexer/indexer_job.rs, core/src/location/indexer/mod.rs, core/src/location/indexer/shallow.rs, core/src/location/manager/watcher/utils.rs, core/src/location/mod.rs, core/src/object/fs/delete.rs, crates/file-path-helper/src/lib.rs
Extra (but not full) sync support for file paths.
Sync support for saved searches.
=> More sync support for file paths + saved searches

.cargo/config.toml.mustache, Cargo.lock, apps/desktop/src-tauri/src/main.rs, apps/server/docker/Dockerfile, apps/server/docker/entrypoint.sh, core/src/api/files.rs, core/src/api/nodes.rs, core/src/api/search/saved.rs, core/src/cloud/sync/receive.rs, core/src/lib.rs, core/src/library/manager/mod.rs, core/src/location/manager/watcher/utils.rs, core/src/node/hardware.rs, core/src/object/fs/delete.rs, core/src/object/media/media_processor/job.rs, core/src/object/media/media_processor/shallow.rs, core/src/p2p/libraries.rs, crates/ai/Cargo.toml, crates/ai/src/image_labeler/model/mod.rs, crates/ai/src/image_labeler/model/yolov8.rs, crates/ai/src/image_labeler/process.rs, crates/ai/src/lib.rs, crates/p2p/src/discovery/mdns.rs, crates/sync-generator/src/sync_data.rs, interface/app/onboarding/Layout.tsx
- Fix downloading model using an internal rust string representation as path for the model file
- Fix Linux loading onnxruntime shared lib from a hard-coded path
- Fix App should not crash when the AI system fails to start
- Fix sd-server failing to start due to onnxruntime incorrect linkage
- Some extra Clippy auto fixes
- Workaround intro video breaking onboarding for the web version
Closes #2044 #2006 #2001
=> [ENG-1595] Fix some problems with the AI system

apps/desktop/src-tauri/src/menu.rs
=> [ENG-1600] Fix cmd+w not closing window on macOS

interface/hooks/useShortcut.ts
=> [ENG-1602] Prevent default keybind events

core/crates/sync/src/backfill.rs, core/crates/sync/src/lib.rs, core/prisma/schema.prisma, core/src/api/sync.rs, interface/app/$libraryId/debug/sync.tsx, packages/client/src/core.ts
Adds a system for generating sync operations from an existing library's data. It's not resumable or anything and isn't actually integrated into the app nicely but it's a start.
This is 1/3 of ENG-1613.
=> Basic sync operation backfill

core/crates/sync/src/backfill.rs, core/crates/sync/tests/lib.rs, core/prisma/schema.prisma, core/src/api/search/saved.rs, core/src/location/indexer/mod.rs, core/src/location/manager/watcher/utils.rs, core/src/object/media/mod.rs, crates/sync-generator/src/sync_data.rs, crates/sync/src/factory.rs, packages/client/src/core.ts
Enabled sync for media data.
~~Draft for now as the sync generator doesn't support using relations as keys.~~
=> media data sync

apps/mobile/src/components/overview/Categories.tsx
=> Mob: better visually width fitting for categories

core/crates/sync/tests/lib.rs, packages/client/src/core.ts
- Fix core test passing inverted arguments to `sync_db_entry` macro
- Updated `core.ts` frontend definition with some new properties from the core API
=> Fix core test and CI breaking

apps/mobile/src/components/browse/BrowseLocations.tsx, apps/mobile/src/components/browse/BrowseTags.tsx, apps/mobile/src/components/browse/Categories.tsx, apps/mobile/src/components/browse/Jobs.tsx, apps/mobile/src/components/header/Header.tsx, apps/mobile/src/components/layout/ScreenContainer.tsx, apps/mobile/src/components/overview/Categories.tsx, apps/mobile/src/components/overview/Devices.tsx, apps/mobile/src/components/overview/OverviewSection.tsx, apps/mobile/src/components/overview/OverviewStats.tsx, apps/mobile/src/screens/settings/Settings.tsx
**This PR**:  improves the padding and spacing tweaks of screens. Resulting in a much better looking app.
**Example image of overview screen**:
=> [MOB-62] Spacing & padding tweaks

Cargo.lock, Cargo.toml, apps/desktop/src-tauri/src/tauri_plugins.rs, apps/desktop/src/platform.ts, apps/web/src/App.tsx, core/Cargo.toml, core/src/api/mod.rs, core/src/custom_uri/mod.rs, core/src/lib.rs, core/src/p2p/manager.rs, core/src/p2p/operations/mod.rs, core/src/p2p/operations/rspc.rs, core/src/p2p/protocol.rs, interface/app/$libraryId/Layout/Sidebar/sections/Debug/index.tsx, interface/app/$libraryId/debug/index.ts, interface/app/$libraryId/debug/p2p-rspc.tsx, interface/util/Platform.tsx, packages/client/src/core.ts
Did someone say rspc queries and mutations over p2p.
I have hooked it up via Hyper so it supports websocket and HTTP body streaming which is pretty sick.
=> rspc over P2P

interface/app/$libraryId/Spacedrop/index.tsx
=> [ENG-1625] Spacedrop UI correct hover condition & spacing

apps/desktop/src/App.tsx, apps/desktop/src/platform.ts, apps/desktop/src/updater.tsx, interface/locales/by/common.json, interface/locales/de/common.json, interface/locales/en/common.json, interface/locales/es/common.json, interface/locales/fr/common.json, interface/locales/nl/common.json, interface/locales/ru/common.json, interface/locales/tr/common.json, interface/locales/zh-CN/common.json, interface/locales/zh-TW/common.json
=> [ENG-1605] updater i18n

interface/app/$libraryId/Explorer/View/Grid/Item.tsx, interface/app/$libraryId/overview/LocationCard.tsx, interface/app/$libraryId/settings/library/locations/ListItem.tsx, interface/app/onboarding/Layout.tsx
**This PR**: Updates folder icon to the correct one.
=> [ENG-1640] Correct locations folder icon

packages/ui/src/Dropdown.tsx
=> [ENG-1460] Fix dropdown spacing

interface/app/$libraryId/Layout/Sidebar/SidebarLayout/Link.tsx
**This PR**: addresses this issue: https://github.com/spacedriveapp/spacedrive/issues/2145
=> [ENG-1663] Prevent middle-click opening new tab

interface/app/$libraryId/Explorer/QuickPreview/index.tsx, interface/hooks/useShortcut.ts
**This PR**: Closes quick preview on ESC keyboard button.
=> [ENG-1664] Close quickpreview on ESC

apps/landing/src/app/roadmap/items.ts
=> Update roadmap dates

core/src/location/manager/watcher/android.rs, core/src/node/hardware.rs, core/src/volume/mod.rs
Fix Windows build + Clippy auto fix
=> Gate iOS only imports

interface/app/onboarding/Layout.tsx
**This pr does the following**: A better experience is being offered when fading out intro.
https://github.com/spacedriveapp/spacedrive/assets/33054370/9976022d-8d12-4b01-8edd-56f3e9b368eb
=> [ENG-1669] Fade out intro

crates/images/Cargo.toml, crates/images/src/svg.rs
Pretty much the title. The code changes were rather trivial ~~but have yet to be fully tested so I'll keep this as a draft for now.~~
=> [ENG-1668] Update `resvg` and related code

Cargo.toml, core/Cargo.toml, crates/sync/Cargo.toml, crates/sync/src/compressed.rs
Some tests for compressing + uncompressing CRDTOperations
=> Add tests for CompressedCRDTOperation

interface/app/$libraryId/Layout/Sidebar/SidebarLayout/FeedbackButton.tsx
This PR is meant to show error messages when attempting to submit the feedback form.
=> [ENG-1680] Show error messages for feedback form

core/src/location/mod.rs, pnpm-lock.yaml
If the .spacedrive file wasn't created successfully on add location, fail silently and move on
=> .spacedrive fail silent fix

core/src/location/manager/watcher/android.rs
This PR will get location-watcher working for Android, getting it one step closer for actual usability. This is part 2 of the splitting of https://github.com/spacedriveapp/spacedrive/pull/1812, where part 1 is the iOS app (https://github.com/spacedriveapp/spacedrive/pull/2073).
This is the actual PR with the changes. I know it's one file. It's been a journey to get to here.
Closes #1811
=> Working Location-Watcher system for Android app

apps/mobile/package.json, apps/mobile/src/components/header/Header.tsx, apps/mobile/src/navigation/OnboardingNavigator.tsx, apps/mobile/src/navigation/SearchStack.tsx, apps/mobile/src/navigation/TabNavigator.tsx, apps/mobile/src/navigation/index.tsx, apps/mobile/src/navigation/tabs/BrowseStack.tsx, apps/mobile/src/navigation/tabs/NetworkStack.tsx, apps/mobile/src/navigation/tabs/OverviewStack.tsx, apps/mobile/src/navigation/tabs/SettingsStack.tsx, pnpm-lock.yaml
=> Use native navigator on mobile

Cargo.lock, apps/desktop/crates/windows/Cargo.toml, core/src/location/metadata.rs
This should add the hidden file attribute to `.spacedrive` files on Windows. Need to see if this passes in CI as I don't have a Windows machine to test on.
Closes #2215
=> Hide `.spacedrive` file on Windows

.github/workflows/ci.yml, .gitignore, CONTRIBUTING.md, apps/landing/package.json, apps/web/.eslintrc.cjs, apps/web/cypress.config.ts, apps/web/cypress/e2e/1-onboarding.spec.cy.ts, apps/web/cypress/e2e/2-location.spec.cy.ts, apps/web/cypress/fixtures/location.json, apps/web/cypress/fixtures/onboarding.json, apps/web/cypress/fixtures/routes.ts, apps/web/cypress/support/commands.ts, apps/web/cypress/tsconfig.json, apps/web/package.json, apps/web/tsconfig.json, interface/app/$libraryId/Explorer/View/index.tsx, interface/app/$libraryId/Layout/Sidebar/SidebarLayout/Footer.tsx, interface/app/$libraryId/Layout/index.tsx, interface/hooks/useRedirectToNewLocation.ts, interface/package.json, package.json, packages/client/src/hooks/useClientContext.tsx, packages/ui/package.json, pnpm-lock.yaml, scripts/package.json, scripts/test-data.sh
- Add script to download some test files to allows tests to have a stable path for creating locations
- Improve onboarding test
- Add custom Cypress commands for fastOnboarding and deleteLibrary
- Add some documentation related to tests to CONTRIBUTING.md
- Update some deps
- Fix React re-render loop when redirecting to a newly created location
=> New test: Add location

interface/app/onboarding/Layout.tsx
Some users reported experiencing issues, we need to do more testing as Tauri seems to handle videos in a strange way.
=> Remove: video intro

Cargo.lock, apps/desktop/src-tauri/Cargo.toml, core/Cargo.toml
=> Alpha 0.2.7

Cargo.lock, apps/desktop/src-tauri/Cargo.toml, core/Cargo.toml
=> Alpha 0.2.8

apps/landing/src/app/page.tsx, apps/landing/src/components/mdx/Pre.tsx, apps/landing/src/components/mdx/index.tsx, apps/landing/src/styles/prism.css
Just a basic copy button in the code blocks so users can copy commands more easily. 
Inspired by Github's copy button.
Example:
=> Copy button for code blocks

core/crates/sync/src/ingest.rs, core/crates/sync/tests/lib.rs, core/crates/sync/tests/mock_instance.rs
i thought i fixed this issue earlier but actually this fixes it, also added another test + reorganised some test code so that tests focus on testing rather than mocking
=> [ENG-1674] fix request drop test and add write_ops test

interface/app/$libraryId/settings/library/general.tsx, packages/ui/src/Select.tsx
=> [ENG-1696] Fix Asian characters text wrapping

Cargo.lock, apps/desktop/src-tauri/Cargo.toml, core/Cargo.toml, interface/app/$libraryId/favorites.tsx, interface/app/$libraryId/labels.tsx, interface/app/$libraryId/location/$id.tsx, interface/app/$libraryId/recents.tsx, interface/app/$libraryId/saved-search/$id.tsx, interface/app/$libraryId/search/AppliedFilters.tsx, interface/app/$libraryId/search/Filters.tsx, interface/app/$libraryId/search/SearchBar.tsx, interface/app/$libraryId/search/SearchOptions.tsx, interface/app/$libraryId/search/index.tsx, interface/app/$libraryId/search/useSearch.ts, interface/app/$libraryId/settings/library/saved-searches/index.tsx, interface/app/$libraryId/tag/$id.tsx
Reverts spacedriveapp/spacedrive#2257
=> Revert "remove fixed filters"

apps/mobile/src/components/modal/tag/CreateTagModal.tsx, apps/mobile/src/components/primitive/DottedDivider.tsx, apps/mobile/src/components/search/filters/FiltersList.tsx, apps/mobile/src/components/search/filters/Locations.tsx, apps/mobile/src/components/search/filters/SavedSearches.tsx, apps/mobile/src/components/search/filters/Tags.tsx, apps/mobile/src/screens/search/index.tsx
**This PR** places the UI of saved search, they need to be plugged in with DB which I will do in another separate PR.
https://github.com/spacedriveapp/spacedrive/assets/33054370/d39a435c-4961-46aa-bb4a-56ea45c64625
=> [MOB-67] Saved search UI

interface/components/TextViewer/index.tsx
Fixes the infinite text file content scrolling when using quick preview.
=> [ENG-1701] No More Infinite Text File Scrolling

core/prisma/schema.prisma, core/src/api/search/saved.rs, interface/app/$libraryId/favorites.tsx, interface/app/$libraryId/location/$id.tsx, interface/app/$libraryId/recents.tsx, interface/app/$libraryId/saved-search/$id.tsx, interface/app/$libraryId/search/Filters.tsx, interface/app/$libraryId/search/SearchBar.tsx, interface/app/$libraryId/search/SearchOptions.tsx, interface/app/$libraryId/search/context.tsx, interface/app/$libraryId/search/index.tsx, interface/app/$libraryId/search/useSearch.ts, interface/app/$libraryId/search/useSearchExplorerQuery.ts, interface/app/$libraryId/settings/library/saved-searches/index.tsx, interface/app/$libraryId/tag/$id.tsx, packages/client/src/core.ts
Adds a concept of 'search targets' that can be switched between
=> search paths/objects switch

apps/mobile/src/components/drawer/DrawerTags.tsx
=> Correct width for button

Cargo.lock, apps/desktop/src-tauri/Cargo.toml, core/Cargo.toml, core/prisma/schema.prisma, core/src/api/search/saved.rs, interface/app/$libraryId/Explorer/useExplorer.ts, interface/app/$libraryId/favorites.tsx, interface/app/$libraryId/labels.tsx, interface/app/$libraryId/location/$id.tsx, interface/app/$libraryId/overview/index.tsx, interface/app/$libraryId/recents.tsx, interface/app/$libraryId/saved-search/$id.tsx, interface/app/$libraryId/search/AppliedFilters.tsx, interface/app/$libraryId/search/Filters.tsx, interface/app/$libraryId/search/SearchBar.tsx, interface/app/$libraryId/search/SearchOptions.tsx, interface/app/$libraryId/search/context.tsx, interface/app/$libraryId/search/index.tsx, interface/app/$libraryId/search/useSearch.ts, interface/app/$libraryId/search/useSearchExplorerQuery.ts, interface/app/$libraryId/settings/library/saved-searches/index.tsx, interface/app/$libraryId/tag/$id.tsx, interface/hooks/index.ts, interface/hooks/useZodParams.ts, packages/client/src/core.ts, packages/client/src/stores/featureFlags.tsx
Reverts the revert commit + changes how search state is persisted, now with premade options for static, in memory, and search params.
All expected open/close behaviours are gonna need testing, and navigation between routes while search is open and closed.
=> Better search

core/prisma/migrations/20240405185748_add_target_to_saved_search/migration.sql
=> Add missing production migration for search improvements made in #2262

Cargo.lock, apps/desktop/src-tauri/Cargo.toml, core/Cargo.toml
=> Alpha 0.2.11

core/src/api/sync.rs, interface/app/$libraryId/Layout/Sidebar/SidebarLayout/Footer.tsx, packages/client/src/core.ts
Exposes the status of each sync process individually
=> [ENG-1723] better sync status

pnpm-lock.yaml, scripts/package.json, scripts/utils/fetch.mjs
=> Add support for OS level network proxy in `pnpm prep`

.github/workflows/ci.yml, Cargo.lock
I'm going to intentionally malform the `Cargo.lock` file just to test that this works.
=> [ENG-1734]: Check that `Cargo.lock` is up-to-date

.github/workflows/ci.yml, Cargo.lock, apps/server/Cargo.toml, apps/server/src/main.rs, docs/product/getting-started/setup.mdx, interface/app/$libraryId/debug/sync.tsx, packages/client/src/core.ts
Good enough for now so I can stop bringing this up in the context of our docker image.
=> Basic HTTP auth for sd-server

core/src/preferences/library.rs, interface/app/$libraryId/Explorer/useExplorer.ts, interface/app/$libraryId/location/$id.tsx, interface/app/$libraryId/search/useSearchExplorerQuery.ts, interface/app/$libraryId/tag/$id.tsx, packages/client/src/core.ts
Hooks up the tag page to preferences in a similar way to locations
=> Tag preferences

interface/app/$libraryId/Explorer/View/MediaView/DateHeader.tsx, interface/app/$libraryId/Explorer/View/MediaView/index.tsx, interface/app/$libraryId/Explorer/View/MediaView/util.ts
This PR includes a date placeholder and an improved date lookup rather than the old first/last item lookup.
=> [ENG-1741] Improve date header

apps/server/src/main.rs
There was a bug in the scoping of auth checks that was causing authentication to be required when it was actually set to disabled.
=> Fix sd-server auth

interface/app/$libraryId/settings/client/general.tsx
We got so many questions regarding it (through various channels), let's uncomment when it's fully implemented.
Closes #2339
=> Hide networking button

core/src/preferences/library.rs, interface/app/$libraryId/Explorer/useExplorerPreferences.ts, interface/app/$libraryId/location/$id.tsx, interface/app/$libraryId/tag/$id.tsx
Deduplicates the preference handling code into one hook
=> Move preference handling into useExplorerPreferences

core/src/api/search/mod.rs
Resolves an issue where in object search mode, file path filters would overwrite each other rather than being merged, leading to incorrect search results.
=> [ENG-1709] Smarter params merging in search api

interface/app/$libraryId/location/$id.tsx, interface/app/$libraryId/tag/$id.tsx
Was causing infinite rerenders
=> Memoise useExplorerPreference props

interface/app/$libraryId/Spacedrop/index.tsx, packages/ui/src/ContextMenu.tsx, packages/ui/style/colors.scss
**This PR**:  improves the colors of context menu, aswell fixes a minor margin value for Spacedrop dropdown to make the UI visually equal.
=> [ENG-1750] Update context menu colors

core/src/api/mod.rs, core/src/api/p2p.rs, core/src/location/mod.rs, core/src/p2p/manager.rs, interface/app/index.tsx, interface/app/p2p/index.tsx, interface/index.tsx, packages/client/src/core.ts
=> Show errors creating P2P listeners on startup

core/src/api/search/mod.rs
=> Remove indexer rules from ephemeral indexer

apps/mobile/src/components/header/Header.tsx, apps/mobile/src/components/layout/Fade.tsx, apps/mobile/src/components/layout/ScreenContainer.tsx, apps/mobile/src/components/locations/GridLocation.tsx, apps/mobile/src/components/overview/Locations.tsx, apps/mobile/src/components/search/Search.tsx, apps/mobile/src/components/search/filters/FiltersBar.tsx, apps/mobile/src/components/tags/GridTag.tsx, apps/mobile/src/navigation/tabs/BrowseStack.tsx, apps/mobile/src/navigation/tabs/NetworkStack.tsx, apps/mobile/src/navigation/tabs/OverviewStack.tsx, apps/mobile/src/navigation/tabs/SettingsStack.tsx, apps/mobile/src/screens/browse/Tags.tsx, apps/mobile/src/screens/search/Filters.tsx, apps/mobile/src/screens/settings/Settings.tsx
**This PR**:
- runs eslint fix.
- Visual adjustments made previously i.e make search input abit smaller, smaller size of icon of tag etc..
- Includes other previous changes that were made too.
=> [MOB-90] Visual adjustments

apps/server/src/main.rs, core/crates/sync/tests/mock_instance.rs
This fix the CI failure in main
=> Fix core test

interface/hooks/useMouseItemResize.ts
This PR: makes forward increase size through the wheel, backwards smaller.
In otherwords, reverse. This is how Windows does it.
=> [ENG-1762] Reverse mouse resize direction

.github/workflows/server.yml
=> Fix server release again

interface/hooks/useMouseItemResize.ts
Tested on the wrong environment. Quick fix.
=> Windows mouse resize fix

core/prisma/schema.prisma, docs/developers/architecture/sync.mdx, docs/product/guides/database-sync.mdx
Some more detail about how sync works
=> Update sync model docs + add section about actors

interface/app/$libraryId/Layout/Sidebar/DebugPopover.tsx
=> Fix Onboarding breaking due to Sidebar changes made in #2425

CONTRIBUTING.md, interface/locales/README.md
This PR simply updated the `CONTRIBUTION.md` to include a link to `/interface/locales/README.md` which elaborates further on how to contribute to translating Spacedrive.
=> [feat]: update i18n contribution docs

core/src/api/ephemeral_files.rs, core/src/lib.rs, core/src/location/non_indexed.rs, core/src/object/media/ffmpeg_metadata_extractor.rs, core/src/object/media/mod.rs, core/src/object/media/old_thumbnail/mod.rs, core/src/object/media/old_thumbnail/process.rs, crates/ffmpeg/src/thumbnailer.rs, crates/media-metadata/src/ffmpeg/chapter.rs, crates/media-metadata/src/ffmpeg/mod.rs, packages/client/src/utils/index.ts
- Increase thumbnail size to 1024x1024
- Increase webp quality to 60%
- Fix thumbnail reactivity for ephemeral locations for real this time
- Fix negative BigInt conversion being completely broken
=> Improve Thumbnail quality + fixes

Cargo.lock, Cargo.toml
Bump image crate version
Also had to patch pdfium-render to bump its image crate version too, will revert once my bump PR on their repo is merged.
=> Update image crate

interface/app/$libraryId/search/SearchOptions.tsx
Changed so that submenus in search options have a max height.
=> changed search options menu to have max height

interface/app/$libraryId/peer/$id.tsx, interface/app/$libraryId/peer/StarfieldEffect.tsx
Warp effect for Peer screens; Spacedrop not yet implemented, just the frontend effect for now 
- wanted to put push this into the codebase before further changes were made to the peer component. Hoping to implement further transitions/functionality in later PR
=> Warp effect

interface/app/$libraryId/Layout/Sidebar/sections/Locations/ContextMenu.tsx, interface/locales/en/common.json
Added feedback for when user deletes a location
=> added feedback for delete

apps/mobile/src/components/explorer/menu/SortByMenu.tsx, apps/mobile/src/components/header/Header.tsx, apps/mobile/src/components/job/JobContainer.tsx, apps/mobile/src/components/job/JobGroup.tsx, apps/mobile/src/components/layout/Empty.tsx, apps/mobile/src/components/locations/GridLocation.tsx, apps/mobile/src/components/modal/ImportModal.tsx, apps/mobile/src/components/modal/job/JobManagerModal.tsx, apps/mobile/src/components/primitive/Button.tsx, apps/mobile/src/components/primitive/Menu.tsx, apps/mobile/src/components/primitive/Toast.tsx, apps/mobile/src/constants/style/Colors.js, apps/mobile/src/hooks/useFiltersSearch.ts, apps/mobile/src/screens/browse/Browse.tsx, apps/mobile/src/screens/browse/Location.tsx, apps/mobile/src/screens/browse/Locations.tsx, apps/mobile/src/screens/browse/Tag.tsx, apps/mobile/src/screens/browse/Tags.tsx, apps/mobile/src/screens/search/Search.tsx
**This PR**:
- Fixes a minor issue with search
- Visual improvements
- Commented out categories of browse page
- Job manager dropdown menu & clear job
**Todo**:
- More Job Manager improvements
- Remove all jobs button
=> [MOB-99] Job remove & more

Cargo.lock, apps/desktop/src-tauri/Cargo.toml, core/Cargo.toml
=> alpha 0.3.0

Cargo.lock, apps/desktop/src-tauri/Cargo.toml, core/Cargo.toml, core/prisma/migrations/20240531034707_add_node_remote_identity_to_instance/migration.sql
=> Alpha 0.3.1

apps/mobile/src/components/job/Job.tsx, apps/mobile/src/components/job/JobContainer.tsx, apps/mobile/src/components/job/JobGroup.tsx
**This PR does design improvements to Job manager**:
=> [MOB-100] Job manager design improvements

interface/app/$libraryId/Layout/Sidebar/sections/Devices/AddDeviceDialog.tsx, interface/app/$libraryId/Layout/Sidebar/sections/Devices/index.tsx, interface/app/$libraryId/search/SearchOptions.tsx, interface/locales/en/common.json
Modal for adding devices in desktop app
- start of the user flow for device sync, frontend functionality only 
- only enabled in dev mode 
@ameer2468 and I collaborated on this :)
=> Add devices modal

apps/desktop/src-tauri/src/main.rs
=> Fix `xdg-open` for Trash

apps/mobile/src/screens/onboarding/GetStarted.tsx, apps/mobile/src/screens/onboarding/NewLibrary.tsx, apps/mobile/src/screens/onboarding/Privacy.tsx
**This PR**: Simples adds haptics when tapping key buttons for each screen.
=> [MOB-94] Onboarding haptics

apps/mobile/src/components/modal/ImportLibraryModal.tsx, apps/mobile/src/screens/settings/library/CloudSettings/CloudSettings.tsx, apps/mobile/src/screens/settings/library/CloudSettings/Instance.tsx, apps/mobile/src/screens/settings/library/CloudSettings/Library.tsx, apps/mobile/src/screens/settings/library/CloudSettings/ThisInstance.tsx, interface/app/$libraryId/debug/cloud.tsx, interface/app/onboarding/join-library.tsx
**This PR** improves how cloud sync ui looks
=> [ENG-1798] Improve cloud sync ui

interface/app/$libraryId/Explorer/ExplorerPathBar.tsx, interface/app/$libraryId/Explorer/ExplorerTagBar.tsx, interface/app/$libraryId/Explorer/Inspector/index.tsx, interface/app/$libraryId/Explorer/TopBarOptions.tsx, interface/app/$libraryId/Explorer/index.tsx
This PR: Fixes the scrolling experience of Inspector & the toggle button of it.
=> [ENG-1777] Fix inspector scroll

interface/app/$libraryId/Explorer/ExplorerTagBar.tsx
Fix issue with previous tag assign mode update where tags could not be assigned.
=> fixed issue with tag assign mode

apps/landing/src/app/NewBanner.tsx, apps/landing/src/app/page.tsx
=> Landing: 0.3 Alpha

interface/app/$libraryId/Explorer/index.tsx, interface/app/$libraryId/recents.tsx
**This PR**: 
- This fixes the bug of recents page not rendering on intial view at times, and not showing the objects.
=> [ENG-1812] Fix recents page render

apps/mobile/src/components/overview/Categories.tsx, apps/mobile/src/screens/overview/Categories.tsx, core/prisma/migrations/20240705205916_create_object_kind_statistics_table/migration.sql, core/prisma/schema.prisma, core/src/api/libraries.rs, core/src/api/mod.rs, interface/app/$libraryId/overview/FileKindStats.tsx, interface/app/$libraryId/overview/LibraryStats.tsx, interface/app/$libraryId/overview/StorageBar.tsx, interface/app/$libraryId/overview/index.tsx, packages/client/src/core.ts
Introduced caching when calculating kind statistics, and also a way to update them on frontend as soon as they're calculated.
=> [ENG-1813] Introduce caching for Kind Statistics

apps/mobile/package.json, apps/mobile/src/App.tsx, packages/client/src/utils/index.ts, pnpm-lock.yaml
=> Fix `Intl` namespace not existing on mobile

interface/app/$libraryId/Explorer/ExplorerPathBar.tsx
**This PR**: Fixes the issue mentioned above
=> [ENG-1818] Fix missing caret when a file is selected in pathbar

apps/mobile/src/App.tsx, apps/mobile/src/components/job/Job.tsx, apps/mobile/src/components/job/JobContainer.tsx, apps/mobile/src/components/job/JobGroup.tsx, apps/mobile/src/components/settings/SettingsButton.tsx, apps/mobile/src/screens/settings/library/EditLocationSettings.tsx, apps/mobile/src/screens/settings/library/LibraryGeneralSettings.tsx
- Fixes text alignments of text in Job manager.
- Job manager had incorrect job keys, so icons wouldn't be displayed.
- Cleaned up code in relation to the above.
- Improved the Layout by modifying padding/spacing values.
- Missing await for running permissions check.
=> [MOB-113] Job manager layout fix & code cleanups

apps/mobile/src/components/modal/confirmModals/DeleteLocationModal.tsx, apps/mobile/src/components/primitive/Toast.tsx
**This PR**: Improves toasts on Mobile.
- Read more/less button shows when text exceeds a certain height.
- onPress support
Not related, also took the chance to improve a error message when deleting a location.
**Notes**: More will be done in the future - but for now this is sufficient.
https://github.com/user-attachments/assets/5dfeb72a-6fa3-49cd-afaf-f8ae86ec6b05
=> [MOB-87] Improve toasts

interface/app/$libraryId/settings/Sidebar.tsx
=> Hide Sync Tab via Feature Flag

apps/desktop/src-tauri/src/menu.rs, apps/desktop/src/commands.ts, interface/hooks/useKeybindEventHandler.ts
Fixes event emitters for the following events:
- Copy
- Cut
- Paste
- Duplicate
- Select All
=> Fix specific keybinds

Cargo.lock, apps/desktop/src-tauri/Cargo.toml, core/Cargo.toml
=> Alpha 0.4.0

.github/ISSUE_TEMPLATE/bug_report.yml, .github/ISSUE_TEMPLATE/config.yml
This PR updates the bug reporting template to have better formatting and not request so many technical details from users who are just using a prebuilt Spacedrive binary.
=> Update bug report template

CONTRIBUTING.md, apps/landing/package.json, apps/landing/src/app/Downloads/DockerDialog.tsx, apps/landing/src/app/layout.tsx, apps/landing/src/app/page.tsx, apps/landing/src/components/mdx/Pre.tsx, docs/developers/prerequisites/environment-setup.mdx, docs/developers/prerequisites/welcome.mdx, docs/product/guides/cli.mdx, docs/product/guides/importing-photos.mdx, pnpm-lock.yaml
This PR just cleans up and updates small parts of the landing site. 
- Docker modal sizing fixed for mobile
- Matching button looks for copying across the site
- Move to Next.js `v14.2.5`
- Change the banner to `Alpha 0.4 is out` with a link to the release change log.
- Updates to docs for easier copy-pasting commands.
=> Updates to Landing

apps/mobile/src/components/modal/cloud/CloudModal.tsx, apps/mobile/src/components/modal/cloud/EnableCloudModal.tsx, apps/mobile/src/components/settings/SettingsItem.tsx, apps/mobile/src/screens/onboarding/NewLibrary.tsx, apps/mobile/src/screens/overview/Overview.tsx, apps/mobile/src/screens/settings/Settings.tsx, apps/mobile/src/screens/settings/library/CloudSettings/CloudSettings.tsx, apps/mobile/src/screens/settings/library/CloudSettings/Login.tsx, apps/mobile/src/screens/settings/library/SyncSettings.tsx
**This PR**: Makes improvements to how modals look for sync, aswell a reasonable UX flow to reach Cloud page.
- The cloud settings page is not accessibe until Sync backfill operations are started.
- There are now clearer descriptions and text that explains what these features offer and do.
**Video of the flow**:
https://github.com/user-attachments/assets/c6486705-4cd6-4f81-8931-8581a50f19db
=> [MOB-115] Improve sync UX flow

docs/developers/prerequisites/environment-setup.mdx
=> [docs] fixes typo in environment-setup.mdx

core/src/api/jobs.rs
Sometimes after jobs fail they show as "Running" but cannot be removed from the job manager UI (considered as "zombie jobs") 
- temporary fix. Investigation showed that it was a backend issue as the jobs.reports query kept returning these jobs even when removed from the frontend array (i.e something in the backend is causing these jobs to persist?) 
- for this PR the zombie jobs don't show up when job manager is not running. When there is a job running the zombie jobs (temporarily) reappear
*Sorry if this is awful rust code, this was my first time attempting to write Rust. Had some time since was waiting for a reply from Supertokens and gave it a shot*
https://linear.app/spacedriveapp/issue/ENG-1836/fix-jobs-remaining-in-queue-due-to-job-not-found-errors
=> [ENG-1836] Prevent "zombie" jobs from appearing in the job manager

interface/app/$libraryId/peer/$id.tsx
=> Added Windows Control buttons to the TopBar on "Peer" tab

apps/mobile/src/components/explorer/Explorer.tsx, apps/mobile/src/components/explorer/FileItem.tsx, apps/mobile/src/components/explorer/FileMedia.tsx, apps/mobile/src/components/explorer/FileRow.tsx
**This PR**: Improves the UX of object renaming, long pressing the name in Grid & List view will trigger the rename modal.
**Video demonstration**:
https://github.com/user-attachments/assets/b43a6f82-cef0-419c-ae6f-72ef006cc51f
=> [MOB-101] Improve object renaming UX

interface/app/$libraryId/Explorer/Inspector/MediaData.tsx, interface/app/$libraryId/Layout/Sidebar/sections/Devices/AddDeviceDialog.tsx, interface/app/$libraryId/settings/library/locations/AddLocationDialog.tsx, interface/app/$libraryId/settings/library/locations/PathInput.tsx, interface/components/Accordion.tsx, packages/ui/src/CheckBox.tsx, packages/ui/src/Dialog.tsx
**This PR**: Improves how dialogs look, as well as improving the layout of Add Location modal.
**In addition**,
- Accordion component now has an animated height.
- Error message of a location already being added improved.
**Demonstration of changes**:
https://github.com/user-attachments/assets/354bbc48-5a54-4200-82c8-fce007e8a529
https://github.com/user-attachments/assets/d1d1e685-e5c0-418b-ac9a-767d150d0b83
=> [ENG-1694] Dialogs visual improvements

docs/product/getting-started/introduction.mdx
Deleted extra ";" and corrected incorrect use of "its."
=> Fix typos in introduction.mdx

apps/mobile/src/components/explorer/FileRow.tsx, apps/mobile/src/components/locations/GridLocation.tsx, apps/mobile/src/components/overview/Locations.tsx, apps/mobile/src/components/overview/StatCard.tsx, apps/mobile/src/navigation/DrawerNavigator.tsx, apps/mobile/src/screens/browse/Location.tsx, package.json, patches/@react-navigation__drawer@6.6.15.patch, pnpm-lock.yaml
**This PR does the following**,
- After adding a location, drawer was appearing slightly. This has been fixed. Manually applied a solution from https://github.com/react-navigation/react-navigation/issues/11608#issuecomment-1835238896 and had to run `pnpm patch` - as the fix has not been released or merged.
- Fixed the width of tags/names in list view, so that object names don't truncate, when there's actually enough space.
- Progress circle value in overview screen corrected.
- Browse screen, set the weight text of the size of the locations to medium rather than bold.
- Overview screen, location cards, I moved the size of a location next to "Local", like desktop app.
=> [MOB-116] Fix Drawer appearing & visual improvements

README.md
=> Typo for: accesible

docs/product/getting-started/features.mdx
=> Update spelling in `features.mdx`

interface/app/$libraryId/Explorer/index.tsx, interface/app/$libraryId/search/SearchOptions.tsx, interface/app/style.scss
**This PR**: Fixes scrolling for explorer on Windows.
- For some reason, the app windows offers to resize when my mouse is actually over the scrollbar, and not when i'm on the edge of the window. 
**The solution**: Increase size of the scrollbar for Windows. This is to be improved.
=> [ENG-1925] Fix windows scroll

docs/product/guides/command-palette.mdx, docs/product/guides/media-conversion.mdx, docs/product/guides/media-view.mdx, docs/product/guides/quick-preview.mdx, docs/product/guides/search.mdx, docs/product/guides/spacedrop.mdx, docs/product/guides/spaces.mdx, docs/product/guides/tags.mdx
Fill in missing documentation pages on Spacedrive website.
=> [ENG-1881] Update docs 

scripts/setup.sh
* New Solus Linux Build Support
Closes #2780
=> Add Solus Build Support

Cargo.lock, apps/desktop/src-tauri/Cargo.toml, apps/desktop/src-tauri/src/drag.rs, apps/desktop/src-tauri/tauri.conf.json, apps/desktop/src/App.tsx, apps/landing/package.json, interface/app/$libraryId/Explorer/index.tsx, interface/app/$libraryId/Explorer/useExplorerDnd.tsx, interface/app/$libraryId/Explorer/util.ts, interface/app/$libraryId/Layout/index.tsx, interface/hooks/index.ts, interface/hooks/useFileDropEventHandler.ts, interface/package.json, interface/util/events.ts, interface/util/index.tsx, packages/ui/package.json, pnpm-lock.yaml
You can now drag & drop files into Spacedrive as well as drag them out of Spacedrive in all OSes now
=> Drag & Drop into/out of Spacedrive

.github/workflows/release.yml, apps/desktop/src/commands.ts, core/Cargo.toml, core/crates/cloud-services/src/client.rs, core/src/library/statistics.rs, core/src/volume/os.rs, core/src/volume/state.rs, core/src/volume/watcher.rs
Just a set of windows build fixes we discussed in Discord.
As I am not a Rust dev, code smells might be seen here. Feel free to point them out.
=> Fix builds on windows

interface/app/$libraryId/Explorer/util.ts
Added ISO(-like) date format to the date format picker in settings.
Somewhat refactored `generateLocaleDateFormats()`.
Let me know what you think :)
=> Add YYYY-MM-DD HH:mm datetime format
