spacedriveapp/spacedrive

docs/architecture/distributed-data-sync.md
behaviour -> `behavior`
impempent -> `implement`
=> fix: spellings

packages/interface/src/components/file/FileList.tsx, packages/interface/src/components/file/FileThumb.tsx
Before:
After:
This PR also centers thumbnails on both axes.
=> fix(interface): don't shrink thumbs when filename is truncated

docs/product/credits.md
Added a link in `credits.md` to the GitHub contributors page found at: https://github.com/spacedriveapp/spacedrive/graphs/contributors
=> Add credit for GitHub contributors

CONTRIBUTING.md
It was pointing at github/docs issues, probably from some contributing guide boilerplate.
Closes #116
=> Change issues link to point at Spacedrive issues

packages/interface/src/components/primitive/Toggle.tsx, packages/interface/src/screens/settings/ExperimentalSettings.tsx, packages/interface/src/screens/settings/LibrarySettings.tsx
Extracts toggle `value` and `onChange` logic
Also fixes TypeScript build in CI!
Yes, this means that `Toggle`s will no longer check and uncheck by themselves — you'll need to supply them with stateful data at a higher level. This is intentional!
Closes #132
=> extract experimental toggle change logic

CONTRIBUTING.md
The Tauri "getting started" url is out of date.
Updates to: https://tauri.studio/guides/getting-started/beginning-tutorial
closes #136
=> Simple update to Tauri guide url

packages/interface/src/components/primitive/Variants.tsx
Changes the incorrectly spelled ```Varients``` to ```Variants```.
=> Change ```Varients``` to ```Variants```.

package.json, pnpm-lock.yaml
Add a script to check if TS code is valid using the same method CI uses. Running `pnpm typecheck` in the root executes this check.
=> Add a type-check script

.github/scripts/setup-system.sh
I have added the necessary `pacman` commands to the setup script for installing dependencies on Arch Linux. The build works and has been tested with:
```sh
pnpm i
pnpm prep
pnpm desktop dev
pnpm web dev
pnpm landing dev
```
Addresses the Arch Linux part of #77
=> Add Arch Linux commands to setup script

apps/landing/src/components/AppEmbed.tsx
Not entirely sure if this is what the issue meant, let me know, but now the `AppEmbed` component returns null if `isMobile`.
Closes #128
=> Return `null` if using mobile.

.vscode/settings.json
Instead of configuring cosmetic options in the workspace (which syncs for all developers), developers should configure these options in their VS Code user settings.
=> Remvoe rust-analyzer cosmetic options

apps/landing/src/style.scss
Added a fix to speed up the css animation for users without hardware acceleration by adding will-change to .bloom
will-change hints to browsers that the element is expected to change. This will slightly increase memory usage as the browser prepares for the action before it takes place.
Closes Issue #217
=> Fix for CSS animation lag 

apps/desktop/vite.config.ts, apps/landing/src/pages/roadmap.tsx, packages/interface/src/components/file/FileThumb.tsx, packages/interface/src/components/file/Sidebar.tsx, packages/interface/src/components/icons/Folder.tsx
**Problem**
The folder icon uses a gradient which requires an ID so that the path element can use it as a reference when using `fill`. However, we use these SVGs in a lot of places, meaning we have duplicate instances of the same gradient definition. This causes problems in browsers where icons might not render properly from time to time. 
**Solution**
To solve this, I first attempted playing around with the [Shadow DOM](https://developer.mozilla.org/en-US/docs/Web/Web_Components/Using_shadow_DOM) to keep using SVGs directly as React components, but with the benefit of residing inside a fully encapsulated environment where styles and IDs don't leak outside. However, I wasn't very successful with this so I ended up sourcing the SVGs as images to avoid the id collisions.
The icons seem to …
=> fix: disappearing icons

apps/landing/index.html
This theme color showed on Safari (overscroll zone and compact tab-bar background) and was incredibly jarring
No related issue as this is a hotfix patch
=> Hotfix: only use bright pink color for embeds

Cargo.lock, apps/desktop/package.json, apps/desktop/src-tauri/Cargo.toml, apps/desktop/src-tauri/src/menu.rs, apps/desktop/src-tauri/tauri.conf.json
- Refactored menu definitions so each submenu's set of items is a variable of its own, and the submenus are created separately. This allows for easier modification of the menus (such as the conditional adding of development menu items)
- Add debug menu items (under View menu)
- Reload. Only implemented for macOS because there's no reload function provided by Tauri and we have to use the native webview object... doesn't seem worth it to figure out native implementation for other platforms than macOS due to our dev team almost exclusively developing on one platform
- Toggle Developer Tools
- Remove 'jeff' commented-out menu item examples. I assume these were there for API reference previously.
- Removed the linux menu, as what we were doing for that platform before is identical to the …
=> Add debug menu items

apps/landing/src/pages/careers.page.tsx
Made the "Open Positions" header appear in view when clicking the "See Open Positions" button.
Before (ew, bad, wtf!!!):
After (yay! woo! amazin): 
This kinda just bugged me when I clicked the button soooooooooo understandable if rejected :^)
=> Made the open positions header appear in view

Cargo.lock, apps/desktop/package.json, apps/desktop/src-tauri/Cargo.toml, apps/desktop/src-tauri/build.rs, apps/desktop/src-tauri/native/macos/Package.resolved, apps/desktop/src-tauri/native/macos/Package.swift, apps/desktop/src-tauri/tauri.conf.json, apps/desktop/src-tauri/tauri.linux.conf.json, apps/landing/src/vite-env.d.ts, package.json, packages/interface/src/hooks/useCoreEvents.tsx, packages/macos/Package.resolved, pnpm-lock.yaml
Changes:
- Fix main not compiling on macOS due to `swift-rs` issues.
-  The app would crash with an error containing `dyld[17517]: Library not loaded: @rpath/libswiftCore.dylib`.
- Update Tauri to v1
- Ensure consistency between `tauri.config.json` and `tauri.linux.config.json`
- Make CI typechecks pass
Please ensure @jamiepine has reviewed this PR before merging as I changed the app bundle identifier to `com.spacedrive.desktop` as it was both `co.spacedrive.desktop` and `app.spacedrive.desktop` in the existing configuration.
=> fix `@rpath/libswiftCore.dylib` error + etc

packages/interface/src/AppLayout.tsx, packages/interface/src/components/file/FileList.tsx, packages/interface/src/components/file/Inspector.tsx, packages/interface/src/components/layout/TopBar.tsx, packages/interface/src/screens/Explorer.tsx, packages/interface/src/style.scss
Previously inspector had incorrect height and was not scrollable. Now the inspector has a custom scroll bar that only shows when hovering the inspector. It is also small and dark, not to distract.
The inspector is also the correct height for the available space, this required changing the parent divs, so hopefully this hasn't broken anything elsewhere, though the app looks fine.
=> Better Inspector Scroll

CONTRIBUTING.md
Replaced the old Tauri "Your first app" link, that has now been removed from the Tauri docs, with a new link to the getting started page (Prerequisites).
=> Fix CONTRIBUTING.md Tauri Link

apps/web/src/App.tsx
It tries to reconnect after:
1. 1 second
2. 2 seconds
3. 5 seconds
4. 10 seconds (keeps trying this forever)
Each attempted reconnect puts an error in the console, this can be suppressed by adding a `error` event listener to `startWebsocket`.
I didn't suppress it because I think this really should have some way of telling the user that its reconnecting, ideally a toast notification, but for the time being, an error is probably okay. 
Toast notifications wouldn't be too hard to add, the [react-hot-toast](https://react-hot-toast.com/) package is pretty nice, but they aren't too hard to add manually so I didn't want to do that without getting opinions of more people. 
Closes #292
=> Client tries to reconnect when sockets close

packages/interface/src/components/layout/TopBar.tsx
The SearchBar shows now CTRL for the keybind on non-macOS systems.
Closes #295
=> SearchBar Logo fix

packages/interface/src/components/file/Sidebar.tsx
Closes ENG-208. Currently, if there are no tags in the sidebar then there is just the word "Tags" on the side. This PR makes it so "Tags" is only shown if there is at least one tag.
=> Don't show Tags on the sidebar if no tags exist.

packages/interface/src/components/explorer/FileItem.tsx, packages/interface/src/components/explorer/Inspector.tsx
Removes the extra period at the end of a file or folder if it doesn't have an extension.
**before:**
**after:**
Closes #379
=> Only show a period at the end of a filename if it has an extension

.github/workflows/ci.yml, .github/workflows/clippy.yml, .gitignore, Cargo.lock, Cargo.toml, apps/desktop/src-tauri/Cargo.toml, apps/mobile/rust/Cargo.toml, apps/server/Cargo.toml, core/Cargo.toml, core/prisma/Cargo.toml, core/src/api/locations.rs, core/src/encode/thumb.rs, core/src/library/library_manager.rs, core/src/location/indexer/indexer_job.rs, core/src/location/mod.rs, core/src/util/db.rs, packages/.spacedrive
Using our own migration engine is cringe. Since we're using Prisma we can use their migration engine which is much more reliable and cool. Using a prerelease of PCR 0.6.2 we can use the migration engine to alleviate a lot of our migration issues, but it will require some different approaches for developing migrations and changing the schema:
- In development, migrations do not need to be generated. The equivalent of `prisma db push` will be ran on launch to synchronise the database and the Prisma schema. Sometimes this may require resetting the database, which can be done by changing the `false` in `_db_push` to `true` in `core/src/utils/db.rs`. Once schema changes are finalized, migrations should be generated with `cargo prisma migrate dev` as usual.
- In production, the equivalent of …
=> Use PCR for migrations

Cargo.lock, Cargo.toml, core/Cargo.toml, core/prisma/Cargo.toml, core/src/api/tags.rs
PCR 0.6.2 will support selecting specific database connectors to compile, rather than compiling all of them. For `sqlite`, this reduces compile times of PCR by about 30%, which should be a pretty significant amount of the core's compile time. I want us to test it out before releasing to the public.
=> Use feature gated database branch of PCR

apps/landing/src/components/Footer.tsx, apps/landing/src/pages/team.page.tsx
This PR fixes the 404 from hitting "Read more" in the [teams page](https://www.spacedrive.com/team), and the FAQ button in the footer. I'm unsure whether or not `/faq` should be linked to `/docs/product/resources/faq`, but this at least fixes it for now.
There aren't any relevant issues as it's likely just classed as a typo (one can be made though if required).
=> fix incorrect faq URLs

.github/workflows/ci.yml
Changes Prisma client caching to derive its key from anything in `core/prisma`, and the root `Cargo.toml` to account for workspace-wide patches.
=> expand prisma client cache key

apps/landing/src/pages/index.page.tsx, apps/landing/src/renderer/_default.page.server.tsx
Fixed the horizontal scrolling issue present on IOS and Mac by adding overflow-hidden to all pages by adding it to main tag
I do not have an Iphone to test that this does not cause any unintended issues so some further testing should be done before accepting this.
Closes #(issue): [ENG-253] Spacedrive landing page has horizontal scroll on ios and mac #402
=> fixed the overflow

Cargo.lock, core/Cargo.toml, core/prisma/schema.prisma, core/src/object/cas.rs
Feel free to close this PR, it is a breaking change (cas ids/libraries will need to be re-generated).
This removes the `ring` and `data-encoding` dependencies, and changes `SHA256` to `BLAKE3`.
`BLAKE3` has a LOT of performance benefits over `SHA256`, and they can be seen [here](https://github.com/BLAKE3-team/BLAKE3/raw/master/media/speed.svg). These benefits will be extremely helpful as we scale up.
We can always just revert the last two commits - bringing in RustCrypto's `sha2` crate is arguably a lot better than the entire `ring` crate.
=> CAS ID Improvements

core/src/object/cas.rs
A hotfix for bad conflict resolution in 3f2b4cda3841a06fd9846bd17f42bd8a3d04f515.
(I've confirmed that builds do work with this change)
=> hotfix: re-import `cas.rs` from `eng-245`

packages/interface/src/screens/settings/library/LibraryGeneralSettings.tsx
Fixes #429 where the library name would be overidden. Caused by the side effect responsible for checking for changes in the debounced values.
Side note: I was considering adding functionality to close dropdown on click/clickaway, but decided to wait for your input.
=> fix(interface/settings): remove `library` dep when updating general settings

Cargo.lock, core/Cargo.toml, core/prisma/migrations/20221102114916_key_update/migration.sql, core/prisma/schema.prisma, core/src/api/keys.rs, core/src/api/mod.rs, core/src/library/library_ctx.rs, core/src/library/library_manager.rs, crates/crypto/Cargo.toml, crates/crypto/src/crypto/stream.rs, crates/crypto/src/error.rs, crates/crypto/src/header/file.rs, crates/crypto/src/header/keyslot.rs, crates/crypto/src/header/metadata.rs, crates/crypto/src/header/preview_media.rs, crates/crypto/src/header/serialization.rs, crates/crypto/src/keys/hashing.rs, crates/crypto/src/keys/keymanager.rs, crates/crypto/src/lib.rs, crates/crypto/src/primitives.rs, packages/client/src/core.ts, packages/interface/src/components/key/Key.tsx, packages/interface/src/components/key/KeyList.tsx, packages/interface/src/components/key/KeyMounter.tsx
This PR is massive, please criticize it to shreds - it's important that we get this right.
The Key Manager now uses [DashMap](https://github.com/xacrimon/dashmap) in order to provide concurrency and better performance over `HashMap`.
There are a few known bugs/issues:
* The dropdown UI is pretty bad, and doesn't fit in too well with the rest of Spacedrive (and the TS formatting is bad too, I don't know how we format that though)
* The key numbering is volatile, and can/will be confusing
* We have no way to set key names within the UI
* We have no way to view the plaintext key within the UI
* Object/container stats are not attached (this isn't major, as they would all be 0 and therefore wouldn't show anyway)
* The UI offers no differentiation between the default key and normal keys
* There …
=> [ENG-262] Key Manager Integration

apps/desktop/src-tauri/src/main.rs, packages/interface/src/components/os/TrafficLights.tsx
Tested on 14" M1 Pro
Fixes bug on MacOS that prevented title bar from hiding while being in fullscreen mode.
Closes #301
=> fixed traffic lights bar showing all the time

core/src/object/fs/encrypt.rs, crates/crypto/src/keys/keymanager.rs, packages/client/src/core.ts, packages/interface/src/components/dialog/EncryptFileDialog.tsx, packages/interface/src/components/dialog/PasswordChangeDialog.tsx, packages/interface/src/components/key/Key.tsx, packages/interface/src/components/key/KeyList.tsx, packages/interface/src/screens/settings/library/KeysSetting.tsx, packages/ui/src/Select.tsx
There is no issue associated with this PR, as it covers a range of random bugs that I came across during some testing.
The TL;DR:
* Master password changing had a bug where new nonces would be generated with an incorrect length, and master password changing would fail.
* Master password changing `Select` boxes weren't updating in the UI because of `react-hook-form`, so this was fixed.
* The UI when no keys were found was a little bad - the key manager dropdown had a bit of text, but the keys settings page had a huge blank gap. This has been replaced (see images)
* The file encrypt dialog erroneously let the user select a hashing algorithm - this had no purpose whatsoever, as the hashing algorithm is inherited from their selected key. This select box is now disabled, and the contents …
=> Crypto Hotfixes

apps/desktop/src/App.tsx, core/src/api/keys.rs, core/src/library/library_manager.rs, crates/crypto/src/error.rs, crates/crypto/src/keys/keymanager.rs, packages/client/src/core.ts, packages/interface/src/components/dialog/BackupRestoreDialog.tsx, packages/interface/src/components/dialog/DecryptFileDialog.tsx, packages/interface/src/components/dialog/EncryptFileDialog.tsx, packages/interface/src/components/dialog/KeyViewerDialog.tsx, packages/interface/src/components/dialog/MasterPasswordChangeDialog.tsx, packages/interface/src/components/key/Key.tsx, packages/interface/src/components/key/KeyList.tsx, packages/interface/src/components/layout/Sidebar.tsx, packages/interface/src/screens/settings/library/KeysSetting.tsx, packages/interface/src/screens/settings/library/LocationSettings.tsx, packages/interface/src/util/Platform.tsx
This PR improves the key viewer, by providing the algorithm/hashing algorithm used for that key.
It also adds the option to toggle key automounting via the key dropdown, and it offers the user a chance to save a memory-only key to the database.
It further cleans up code in general, and the key dropdown menu items. `save()` and `open()` are now abstracted through `Platform`, and `open({directory: true})` was renamed to a directory-specific function (references to this have been updated).
=> [ENG-315] Key viewer/general improvements

core/src/api/keys.rs, core/src/object/fs/decrypt.rs, crates/crypto/src/header/file.rs, crates/crypto/src/keys/keymanager.rs, packages/client/src/core.ts, packages/interface/src/components/dialog/DecryptFileDialog.tsx, packages/interface/src/components/dialog/KeyViewerDialog.tsx, packages/interface/src/components/explorer/ExplorerContextMenu.tsx, packages/interface/src/components/key/KeyMounter.tsx
This implements password decryption, and offers the user a chance to import the key and content salt into our key manager. This is super helpful for either one-off decryption, or importing lost key/content salt relations. This removes the check for any mounted keys before opening the decrypt dialog, but it disables keymanager-based decryption if no keys are mounted.
I may implement this for encryption too, just as a one-off "encrypt with this password" (this could also have the option to save the key to the key manager). I'm not too sure if this would be worthwhile though, as it's just as easy to create a memory-only key within the key manager.
I have tested this, and it successfully imports the key into the key manager.
This PR also adds the (hex encoded) content salt to the key viewer.
=> [ENG-316] Decrypt with Password

CONTRIBUTING.md
pr to update contributing guide to node 18* since 16 is no longer supported when running "pnpm i".
=> updated contributing.md to node 18

Cargo.lock, crates/crypto-cli/Cargo.toml, crates/crypto-cli/src/main.rs, crates/crypto/src/header/serialization.rs
This adds a small "details" CLI tool as a new crate. This doesn't handle any encryption at all, and only shows us the algorithms/salts/nonces/versions/etc used for the file.
I tried to use a combined library/binary crate, but it would either involve renaming the crate itself, or renaming the library (`sd-crypto` couldn't be used for both). The latter would've required a lot of refactoring, and I'm not too sure the former would've been suitable.
Metadata and preview media also have their details shown, provided they are embedded within the file.
=> [ENG-312] Crypto details CLI tool

core/src/api/keys.rs, core/src/object/fs/decrypt.rs, core/src/object/fs/encrypt.rs, packages/client/src/core.ts, packages/interface/src/components/dialog/DecryptFileDialog.tsx, packages/interface/src/components/dialog/EncryptFileDialog.tsx, packages/interface/src/components/explorer/Explorer.tsx
This fixes a pretty major bug, where files would refuse to encrypt/decrypt/etc if the associated `file_path` didn't have an object/`object_id` attached to it.
The issue only popped up once in a blue moon, but it should now be completely resolved.
~~I'll keep this as a draft until #506 gets merged as it needs `cherry-pick`ing out.~~
This also improves automounting, by allowing the user to access the key manager before all keys are mounted.
=> [ENG-325] Local paths for the context menu

apps/web/src/App.tsx, apps/web/src/env.d.ts
`web` currently uses the `VITE_SDSERVER_BASE_URL` environment variable to know where the server is. This isn't great, since the server can connect over multiple protocols (http and ws) and has many paths.
Instead, we should be providing the _origin_ (ip/hostname + port) and interpolating it into the various protocols and routes.
=> use origin instead of url for web

packages/interface/src/components/explorer/ExplorerTopBar.tsx, packages/interface/src/components/explorer/FileItem.tsx, packages/interface/src/components/jobs/JobManager.tsx, packages/interface/src/components/layout/Sidebar.tsx, packages/interface/src/components/location/LocationListItem.tsx, packages/interface/src/screens/settings/library/TagsSettings.tsx, packages/interface/src/screens/settings/node/LibrariesSettings.tsx
This PR adds tooltips to many buttons that didn't have them before.
List of locations where tooltips were added in the format {location}: {tooltip}
1. Sidebar - Settings icon: "Settings"
2. Sidebar - Jobs icon next to Settings: "Recent Jobs"
3. ExplorerTopBar - Key Icon: "Unlock"
4. ExplorerTopBar - Three Lines: "File Display Options"
5. ExplorerTopBar - Inspector Toggle: Either "Show Inspector" or "Hide Inspector"
6. Library Settings - Database Icon: "TODO" What will this button do? It doesn't do anything currently
7. Library Settings - Edit Icon: "Edit Location"
8. Library Settings - Trash Can: "Delete Library"
9. Location Settings  - Trash Can: "Delete Location"
10. Location Settings - Retry Icon: "Rescan Location"
11. Tags Settings - Trash Can: "Delete Tag"
=> Desktop - Add more tooltips

core/src/location/metadata.rs, core/src/object/fs/encrypt.rs
Removing metadata files that failed to be deserialized, this can happen due to an older version of these `.spacedrive` metadata files, before this feature was actually implemented, or if the file was corrupted.
=> [ENG-333] Handle .spacedrive existing instead of throwing error

core/src/api/keys.rs, crates/crypto/src/error.rs, crates/crypto/src/keys/keymanager.rs, packages/client/src/core.ts, packages/interface/src/components/key/Key.tsx, packages/interface/src/components/key/KeyList.tsx, packages/interface/src/components/key/KeyManager.tsx, packages/interface/src/screens/settings/library/KeysSetting.tsx
This PR adds a key manager mounting queue, and a few routes for checking the mount status of certain keys. It uses a Rust `DashSet` internally (for the hardcoded/externally immutable queue - this one will help protect us against malicious clients and DOS attacks due to memory-hard hashing algorithms).
The Rust queue is used for only one (external) route - checking if the key manager is currently being unlocked. This is used multiple times throughout the app, so a route will likely be best. The `set_master_password()` function also temporarily takes an `invalidate` closure, so we can invalidate the query correctly within the crypto crate. With this, users cannot attempt to unlock the key manager multiple times, no matter where in the app they are (or where they first started the unlock). …
=> [ENG-328] Keymanager mounting queue

apps/desktop/src-tauri/native/macos/Sources/webview.swift, crates/sync/example/web/src/App.tsx, packages/interface/src/components/explorer/FileRow.tsx
reloading wasn't accounted for when upgrading swift-rs
=> Fix webkit reload

package.json, pnpm-lock.yaml
In a team discussion earlier the idea was floated to create some form of `pnpm clean` command — this PR does just that, removing the following:
- root `/node_modules/`
- nested `**/node_modules/`
- rust compilation `/target/`
- swift compilation `**/.build/`
- next.js compilation/cache `**/.next/`
- subdirectories of nested desktop compilation `**/dist/**` (not removing directory because the `.gitignore` in there is purposeful)
=> Add clean command

Cargo.lock, Cargo.toml, apps/desktop/src-tauri/Cargo.toml, apps/mobile/rust/mobile/Cargo.toml, apps/server/Cargo.toml, core/Cargo.toml, crates/crypto/Cargo.toml, crates/ffmpeg/Cargo.toml, crates/file-ext/Cargo.toml, crates/p2p/Cargo.toml, crates/p2p/tunnel/Cargo.toml, crates/sync/example/Cargo.toml
This PR forces all uses of `tokio` to be from the workspace, and the workspace uses `tokio v1.24.2` with the commits listed in [this branch](https://github.com/brxken128/tokio/tree/2mib-io-buffer).
The Linear issue contains more information, but I have tested that things build on Linux.
Windows, MacOS, Android and iOS have yet to be tested, but probably should be before this is merged.
=> [ENG-351] Tokio git patch

Cargo.lock, Cargo.toml
This PR reverts the changes of #552, and bumps our `tokio` version to v1.25.0.
I opted to leave `workspace = true` everywhere, as we re-use `tokio` in pretty much all of our crates and it seems easier this way.
I've tested the changes locally and everything seems to be in working order.
=> remove `tokio` git patch and update to `1.25.0`

apps/mobile/src/screens/settings/library/LocationSettings.tsx, core/prisma/schema.prisma, core/src/api/locations.rs, core/src/library/library_manager.rs, core/src/location/manager/helpers.rs, core/src/location/manager/mod.rs, core/src/location/manager/watcher/mod.rs, core/src/location/manager/watcher/utils.rs, core/src/location/mod.rs, core/src/sync/manager.rs, packages/client/src/core.ts, packages/client/src/hooks/index.ts, packages/client/src/hooks/useCurrentLibrary.tsx, packages/client/src/hooks/useOnlineLocations.ts, packages/client/src/rspc.ts, packages/client/src/utils/index.ts, packages/interface/src/components/layout/Sidebar.tsx, packages/interface/src/components/location/LocationListItem.tsx
Whether a location is online or not isn't really something that belongs in the db - it's directly related to the node's connections at the current moment, whether that's over the network or watching at the current moment.
It also doesn't make sense in the sync system, since online status shouldn't really be persisted.
Instead, locations are tracked in a global `BTreeSet` inside the `LocationManager`, with changes reported via a broadcast channel and subscribed to on the frontend.
=> Move location online status out of database

packages/interface/src/components/layout/Sidebar.tsx
Hey! 
Here is a fix for the dropdown button that is auto-focused when launching app. The fix is a bit hacky, but I saw a similar one [here](https://github.com/spacedriveapp/spacedrive/blob/b94eab8517d53e61ad2ae6016d90462fa9503abc/packages/interface/src/components/key/KeyMounter.tsx#L33-L37), so if you're fine with it, it's working.
Closes #191
=> [Fix] Dropdown focus when app is launching

.github/workflows/ci.yml, Cargo.lock, crates/deps-generator/Cargo.toml, crates/deps-generator/src/main.rs, crates/deps-generator/src/types/backend.rs, crates/deps-generator/src/types/cli.rs, crates/deps-generator/src/types/frontend.rs, crates/deps-generator/src/types/mod.rs, packages/assets/deps/backend-deps.json, packages/assets/deps/frontend-deps.json, packages/interface/src/components/settings/SettingsSidebar.tsx, packages/interface/src/screens/settings/index.tsx, packages/interface/src/screens/settings/info/Dependencies.tsx
This PR adds the `deps-generator` binary, and a basic placeholder page for displaying all of our front/back-end dependencies in-app.
I removed the changes from CI as they weren't working well enough. We can always custom-parse and manually import reports from Fossa, which may be easier if we just update this for each release.
The UI is **_extremely_** basic, and this PR contains the minimum amount of data to make it work. I have attempted to lazy-load the data, I'm not too sure how correct the code is (but it works).
`deps-generator` usage:
* `deps-generator frontend c04897d902c9a55baf14d532f4590bc711f08c16 frontend-deps.json`
* `deps-generator backend Cargo.toml backend-deps.json`
=> [ENG-134] OSS Licenses and Projects

packages/client/src/hooks/useCurrentLibrary.tsx
I'm not sure if this is the correct usage (with relation to `useCallback`), but it does work flawlessly.
=> [ENG-343] Navigate to `/` when library is switched

core/src/api/locations.rs, core/src/object/fs/decrypt.rs, core/src/object/fs/encrypt.rs, core/src/object/fs/mod.rs, packages/interface/src/components/explorer/ExplorerContextMenu.tsx, packages/interface/src/components/explorer/ExplorerOptionsPanel.tsx, packages/interface/src/components/explorer/ExplorerTopBar.tsx, packages/interface/src/components/explorer/FileColumns.tsx, packages/interface/src/components/explorer/FileItem.tsx, packages/interface/src/components/explorer/FileRow.tsx, packages/interface/src/components/explorer/FileThumb.tsx, packages/interface/src/components/explorer/Inspector.tsx, packages/interface/src/components/explorer/VirtualizedList.tsx, packages/interface/src/components/explorer/util.ts, packages/interface/src/hooks/useExplorerStore.tsx
Adds the ability to resize items in the explorer grid view
- Added item resizer
- Fixed explorer store bug
- Refactored file image component
- Fixed explorer thumbnail rendering
- Improved list view, added more columns and column headings
Note: there is a bug where icons do not render in the FileIcon component, images, video and folders are fine, but custom icons require a forced re-render to show (you can trigger it using the context menu). This only happens on list view and in the inspector, grid view is fine.
https://user-images.githubusercontent.com/32987599/221331773-4cadb0af-3570-41d2-b89f-b7b30c2672fd.mov
=> [ENG-379] Explorer item resizer

Cargo.lock, apps/mobile/crates/android/Cargo.toml, apps/mobile/crates/android/src/lib.rs
#590 made swift stuff only build on iOS and macOS, this PR makes android stuff only build for android targets. `cargo build --all` should work on macOS and hopefully other OSes too.
=> platform-restrict android code

.github/actions/generate-prisma-client/action.yaml, core/src/sync/manager.rs, crates/sync-generator/src/lib.rs
Instead of manually matching on sync + model type, we now have the matching done via a generated enum and just manually match on that. Just automating more of stuff we already do.
=> generate + use ModelSyncData enum

apps/desktop/package.json, apps/desktop/src/index.tsx, apps/desktop/vite.config.ts, apps/web/src/index.tsx, apps/web/tailwind.config.js, apps/web/vite.config.ts, core/src/api/mod.rs, core/src/api/p2p.rs, core/src/lib.rs, core/src/p2p/p2p_manager.rs, core/src/p2p/protocol.rs, crates/p2p/src/lib.rs, crates/p2p/src/spaceblock/mod.rs, interface/app/$libraryId/spacedrop.tsx, packages/client/src/core.ts, pnpm-lock.yaml
It ain't pretty but it's working.
Note: The current system can only send files up to 255 bytes and they must be fully UTF-8. These limitations are because I haven't quite got the protocol down-packed for sending the file and wanted to get rspc hooked up. They will be easy limits to remove tomorrow or early next week.
Testing this system:
- `echo "Hello World" > ~/Desktop/demo.txt`
- `cargo run -p server` + `pnpm web dev` (or can use `pnpm desktop dev`)
- In another terminal run: `export PORT=42069 && export DATA_DIR=./sdserver_data2 && cargo run -p server` - this creates the client we are gonna send the file to
- Go to Spacedrop in the UI and use the ugly-looking UI I threw together with a path to the file you created in step one.
=> Basic Spacedrop working with rspc!

.github/scripts/setup-system.sh, crates/ffmpeg/Cargo.toml
This PR fixes a few issues, mostly relevant to Fedora but should also resolve MacOS/brew "keg not found" errors. It removes the need for us to build `ffmpeg` within the script, as it wasn't doing much anyway (we were building ffmpeg `5.0.1`, but our project requires `5.1.0`). MacOS CI time is now shorter by 5-7~ minutes.
This additionally adds the `protoc` compiler to both Fedora and Arch targets.
~~I'm going to test my Fedora changes in a virtual machine, as there's a few parts I'm unsure over (and I think they could be optimized - currently we're pulling in the entire `perl` package set, but building only needs a few of them).~~ - done, changed to a handful of packages instead as that produces a working fully build.
I've also used `shfmt` to format the script.
=> [ENG-430] *Nix setup script improvements

apps/landing/src/pages/careers.page.tsx
Fixes current icons on the  [careers](https://www.spacedrive.com/careers) page.
=> fix careers phosphor icons

.github/actions/setup/action.yml, .github/scripts/setup-system.sh, .github/workflows/cache-factory.yaml, .npmrc, apps/desktop/vite.config.ts, apps/web/vite.config.ts, interface/app/$libraryId/index.tsx, interface/app/$libraryId/settings/client/index.ts, interface/app/$libraryId/settings/node/index.tsx, interface/app/$libraryId/settings/resources/index.tsx, interface/app/index.tsx, interface/package.json, package.json, packages/client/src/utils/keys.ts, pnpm-lock.yaml
Hello,
While working on #621 I noticed that the `pnpm format` command was failing with some files, this PR fix that. I also went ahead and auto-formatted those files and did some more basic changes. If any of the changes are not wanted, just let me know and I will revert them.
Changes:
- Update prettier and plugins to fix compatibility with the new TS `satisfies` syntax
- Add `auto-install-peers` to `.npmrc` (so peers dependencies are installed when setting up the repository)
- Fix formatting for the previously failing files
- ~~Some basic security mitigations (`pnpm audit --fix`)~~
- Simple change in `setup-system.sh` to avoid running a full system update on Arch Linux
=> Fix `pnpm format` command failing with some files

interface/app/$libraryId/Layout/Sidebar/LibrariesDropdown.tsx, packages/ui/package.json, packages/ui/src/ContextMenu.tsx, packages/ui/src/Dropdown.tsx, packages/ui/src/DropdownMenu.tsx, packages/ui/src/index.ts, packages/ui/style/tailwind.js, pnpm-lock.yaml
This PR fixes the issue with long library names in the `LibraryDropdown` menu and the `Manage Library` button navigates to `general` library settings rather than just settings. It also includes a Radix `DropdownMenu`, which uses classes and item internals from `ContextMenu`, that way changes are applied to both components. Could also work on replacing all the current Headless dropdowns with the new Radix one.
=> [Desktop, UI] Fix library dropdown overflow & navigation

interface/app/$libraryId/settings/library/locations/$id.tsx
This PR fixes the issue where sometimes the initial load of the edit location form doesn't reset the form as `isDirty = true`
https://user-images.githubusercontent.com/43032218/226167716-31060b0b-9483-41a3-abf2-f6d4d66ceee4.mp4
=> [Desktop] Fix initial edit location load

core/src/location/error.rs, interface/app/$libraryId/settings/library/locations/AddLocationButton.tsx, interface/app/$libraryId/settings/library/locations/AddLocationDialog.tsx, interface/package.json, pnpm-lock.yaml
Hello,
This PR addresses the issue of adding locations that already have a `.spacedrive` file, either because they belong to other Libraries or because their linked directory has been moved.
I implemented logic to handle both the `NeedRelink` and `AddLibraryToMetadata` errors raised by the backend when adding a new Location. When either of these errors occurs, a form error message is displayed to the user in `AddLocationDialog`, informing them that the location they are trying to add is either from another Library or needs to be relinked:
I decided to use the form's built-in error UI because the user's flow is similar to encountering a validation error when entering incorrect data, so I thought it would be more natural than a confirmation dialog.
If the user continues with adding the …
=> Fix adding Locations that already have a `.spacedrive` file

interface/app/$libraryId/Layout/Sidebar/LibrariesDropdown.tsx, packages/ui/src/ContextMenu.tsx, packages/ui/src/DropdownMenu.tsx, packages/ui/style/colors.scss
Changes made:
- Changed light theme menu colors
- Changed dark theme menu line color to a slightly lighter one
- Slightly increased menu size for a better look
- Added menu item arrow highlighting
- Removed absolute key bind position, that way long labels don't clash with the key bind
- Removed animate prop from the dropdown menu and make it animate by default
Will PR tag related changes after this is resolved.
Closes #638
=> [Desktop] Fix menu colors and arrow highlighting

apps/desktop/src-tauri/src/app_linux.rs, apps/desktop/src-tauri/src/main.rs
Hi,
After investigating the issue I described in #642, I found that the problem was caused by the `axum_shutdown_signal` call in the `app_linux.rs` setup, which I believe was overriding the signal handler set by Tauri. As a result, when the desktop app was closed with CTRL+C, only the `axum_shutdown_signal` logic was executed, terminating both the backend and the thumbnail server, but leaving the Tauri app still running. 
To fix this issue, I replaced the `axum_shutdown_signal` call with a channel that sends a signal when the `ExitRequested` event occurs. This approach shuts down the thumbnail server along with the Tauri app. I have tested this solution, and it seems to be working correctly. However, as my Rust knowledge is limited, I'm not certain if this is the best solution. Please let …
=> Replace thumbnail server shutdown signal with a channel Receiver

interface/app/$libraryId/Explorer/AssignTagMenuItems.tsx, interface/app/$libraryId/Explorer/File/ContextMenu.tsx, interface/app/$libraryId/Explorer/Inspector/index.tsx, interface/app/$libraryId/settings/library/tags/CreateDialog.tsx, interface/hooks/useScrolled.tsx, packages/ui/src/ContextMenu.tsx, packages/ui/src/DropdownMenu.tsx, packages/ui/src/index.ts
Changes made to the explorer item context menu:
- Show "Assign tag" sub menu only when objectData is present
- Added an option to create tags from the "Assign tag" sub menu(upon creation, the tag is assigned to that object)
- Put "Assign tag" sub menu items into a virtual list.
- Moved AssignTagMenuItems component into its own file, as the same component is used in the item inspector
Changes made to the item inspector:
- Show "Add tag" placeholder only when objectData is present
- Added a tag assignment dropdown menu to the "Add tag" placeholder(uses the AssignTagMenuItems component)
Closes #646
=> [Desktop] Menu tag assignment

apps/landing/src/style.scss, apps/landing/src/utils/markdownParse.tsx
**what:**
added the ability to have title icons in slots. the icons I chose are of course not written in stone and can easily be changed.
**how it works:**
as far as I know are there three different slot types (note, info, warning). either a warning icon, or an info icon, is added to the slot title based of the slot type. if the slot type is not note, info or warning (which it probably shouldn't be), an info icon is still added.
**before imgs:**
**after imgs:**
**closes discussion:** 
https://github.com/spacedriveapp/spacedrive/discussions/654
=> added title icons for slots

core/src/object/cas.rs
This PR fixes the `generate_cas_id` sample hashing logic. It updates the sampling loop to account for seeking using a position counter variable, instead of updating it from the previous seek pointer. I have also changed the header and footer hashing calls to limit the size of the buffer. Previously, if I understood the documentation for the hash crate correctly, it would hash unpopulated or remaining data that may be present in the buffer beyond `HEADER_OR_FOOTER_SIZE`.
Closes #670.
=> Fix cas_id sample hashing logic

interface/app/$libraryId/Explorer/SearchBar.tsx, interface/app/$libraryId/Explorer/TopBar.tsx, interface/app/$libraryId/Explorer/TopBarButton.tsx, interface/app/$libraryId/spacedrop.tsx, packages/ui/src/Input.tsx
- TopBar.tsx had multiple components, so I extracted them into their own files.
- Searchbar did not support cmd/ctrl + F, so I added that + escape to unfocus the input.
- Removed PageLayout.DragChildren wrapper around SearchBar in spacedrop.tsx, this was causing a bug where the searchbar would disappear sometimes when you switch routes.Another reason is because PageLayout.Dragchildren isn't necessary and does not affect functionality.
Proposal down the line:
- We should implement a topbar that changes its tools/options based on context, instead of having to render SearchBar multiple times through the app, we can have it all in one place that is dynamic and would change based on the page the user is on (in reference to the tools/options provided)
Video of keyboard support: …
=> ENG-449 - Keyboard support for Search & Component Extraction

.github/scripts/setup-system.ps1, package.json, pnpm-lock.yaml
Hello,
During testing of my QuickPreview implementation (PR #665) on Windows, I encountered some problems setting up the project. This PR addresses those issues by changing the Windows setup script to make it more robust, less redundant, and to fix recent problems caused by major updates to PNPM and LLVM that were breaking installation and compilation on Windows.
These changes include:
- Ensuring Powershell is running as an administrator ~(required by Chocolatey)~
- Retrieving the project directory relative to the script path, instead of using the current directory
- Installing pnpm version 7 (version 8 is incompatible with some dependencies)
- Installing LLVM 15 (LLVM 16 breaks compilation of ffmpeg-sys-next)
- ~Installing Chocolatey if not available~
- ~Updating ffmpeg version from …
=> Improve Windows setup script

interface/app/$libraryId/settings/library/locations/$id.tsx, interface/app/$libraryId/settings/library/locations/AddLocationDialog.tsx, interface/app/$libraryId/settings/library/locations/IndexerRuleEditor.tsx, packages/client/src/rspc.ts, packages/ui/src/forms/Form.tsx
This PR partially implements the `IndexerRuleEditor` component (still lacks the ability to create indexer rules, will be addressed in ENG-384), which allows for editing a location's indexer rules from its settings page. Additionally, I replaced the checkbox list of indexer rules in `AddLocationDialog` with `IndexerRuleEditor` for consistency. I also performed some minor clean-up in the location settings page and improved the error handling for some of its logic.
[indexer_rules.webm](https://user-images.githubusercontent.com/9082460/231084236-3dc40514-5050-437d-a2a5-cfa2fc4aed22.webm)
=> [ENG-291] Location settings

core/src/location/error.rs, core/src/location/mod.rs
This PR removes the check that verifies if a location's path is read-only during creation. This check caused false positives in cases where the users actually has write permissions to the path (I experienced it on both Windows and Linux). Instead, the creation of the `.spacedrive` metadata file can act as a better indicator of write access. Additionally, I implemented a rollback mechanism for location creation when either the `.spacedrive` file fails to be written or the location cannot be added to the library location manager.
=> ENG-460 Location creation fails for some writable directories

core/src/location/file_path_helper.rs, core/src/location/indexer/indexer_job.rs, core/src/location/indexer/mod.rs, core/src/location/indexer/shallow_indexer_job.rs, core/src/location/indexer/walk.rs, core/src/location/manager/watcher/utils.rs
Migrating `size_in_bytes` to `file_path` table from `object` table had some problems before, so we messed up to pass this data on `file_path` creation.
=> ENG-462 Object size is `0` when it shouldn't be

.github/scripts/setup-system.sh, Cargo.lock, core/Cargo.toml, crates/ffmpeg/Cargo.toml
This PR upgrades Spacedrive to use `ffmpeg 6.0.0` via an external brew tap.
I believe this means users will be compiling `ffmpeg`, so that will take a while (and CI will likely take longer). This is hopefully only a temporary solution until `brew` add official support for `ffmpeg` 6.
NOTE: `ffmpeg` will have to be uninstalled if the official package is installed. Additionally, developers on MacOS will either have to install this ffmpeg version manually, or re-run the setup script. Manual installation can be accomplished with these commands:
```
brew tap homebrew-ffmpeg/ffmpeg
brew install homebrew-ffmpeg/ffmpeg/ffmpeg
```
=> update to ffmpeg 6.0.0

interface/app/$libraryId/Explorer/SearchBar.tsx, interface/app/$libraryId/Explorer/TopBar.tsx, interface/app/$libraryId/Explorer/TopBarButton.tsx, interface/app/$libraryId/Explorer/TopBarMobile.tsx, interface/hooks/useToolBarOptions.tsx, packages/ui/src/Popover.tsx
This PR makes the top bar responsive.
**Notes**:
- Used side effects to get the width of the topbar for the sake of collapsing at the right time, rather than using media queries from tailwind for a better user experience.
- There's only 2 cases when it needs to collapse, when the tool count is >= 8 or  6 and at certain widths. No need to go further because thats the maximum amount you can resize the window to.
- Added check icon as an optional prop to top button component, that is the best way to apply this.
- Used the Popover component, rather than DropDown because it's styling is completely off and different, don't want to make un-necessary edits.
**Other notes**:
- Individual buttons are now supported for the Top bar, this allows them to have their own spacing and are away from each …
=> [ENG-458] - Top Bar Responsiveness

Cargo.lock, core/Cargo.toml, core/src/location/file_path_helper.rs, core/src/location/indexer/walk.rs, core/src/location/manager/watcher/utils.rs, core/src/location/mod.rs
This PR fixes a possible error when adding a location that could occur when the core fails to extract a name from its accompanying path. Additionally, I improved the location's name extraction logic by using [`localize_name`](https://docs.rs/normpath/1.1.1/normpath/trait.PathExt.html#tymethod.localize_name) and added an `Unknown` value as the default when all else fails. Besides this, I fixed a possible panic that could occur when the Indexer job fails to retrieve the created/modified date of a path. To solve this, I implemented a `MetadataExt` trait with `created_or_now`/`modified_or_now` that returns the current time when the path time isn't available.
=> [ENG-461] Location creation fails for '/' (root) and 'C:' ([A-Z] drives)

core/prisma/migrations/20230418040228_job_date_completed/migration.sql, core/prisma/schema.prisma, core/src/job/job_manager.rs, core/src/job/worker.rs, core/src/location/indexer/indexer_job.rs, core/src/location/indexer/mod.rs, core/src/location/indexer/shallow_indexer_job.rs, core/src/location/indexer/walk.rs, interface/app/$libraryId/Layout/Sidebar/JobManager.tsx, package.json, packages/client/src/core.ts
Previously for every job, every second we would send an event to the frontend to tell it the job had progressed by one second. This is kinda wasteful of IPC bandwidth which can be very limited when indexing a large location.
Changes:
- Don’t send time updates from the backend
- Store finished time as a timestamp instead of seconds elapsed
- Debounce events before sending them on `WorkerContext {}.events_tx`. Debouncing at the sender in much nicer, imo.
- Disabled Turbo as the runner for `pnpm typecheck` because it's caching when it shouldn't and this could allow bugs to make it though.
Breaking changes:
- I removed the `seconds_elapsed` column so I think a DB reset will be required as all previous jobs will not show up correctly in the UI.
=> Automatic job progress

.editorconfig, core/prisma/migrations/20230210031123_init/migration.sql, core/prisma/migrations/20230417192552_add_default_param_to_indexerrule/migration.sql, core/prisma/schema.prisma, core/src/location/indexer/rules.rs, core/src/location/indexer/walk.rs, core/src/util/seeder.rs, interface/app/$libraryId/settings/library/locations/AddLocationDialog.tsx, interface/app/$libraryId/settings/library/locations/IndexerRuleEditor.tsx, packages/client/src/core.ts
This PR adds a new default indexer rule called `No OS protected`, which is intended to prevent the indexing of OS-protected files. To implement this rule, I had to modify the logic of the `AcceptFilesByGlob` and `RejectFilesByGlob` rules types to accept multiple globs and use a `GlobSet` for matching. The only potential issue with these changes is the `globset_from_globs` function, which creates a new GlobSet for each indexer rule during each directory/file check. While my testing didn't show any noticeable performance impact, the best approach would be to memoize it to execute only once for each indexer rule. However, I couldn't find a simple way to do this in Rust. If anyone has a solution, it would be greatly appreciated. Otherwise, I'll create a low-priority issue to address this …
=> [ENG-286] Set default indexer rules for location

.gitignore, core/src/lib.rs, core/src/library/config.rs, core/src/library/manager.rs, core/src/migrations.rs, core/src/node/config.rs, core/src/util/migrator.rs, core/src/util/mod.rs, packages/client/src/core.ts
Changes:
- Store version as `u32` instead of using the version from the `Cargo.toml`. This is required to fix the next point.
- Run each migration from the current version to the desired version.
- Eg. going from version 0 to version 2 will run version 1's migrations in between. The previous code didn't do this and it was a clear failure in my design for it.
- Basic unit tests for the migrator as of everything in the app we kinda need it to *just work*.
Breaking Changes:
- All databases need to be reset for the app to work as I broke the way the previous system worked.
- If you don't wanna reset it, change `"version": "..."` to `version: 0` in the `node_state.sdconfig` and `libraries/*.sdlibrary` files
=> Eng 488 fix app migrations system

.github/scripts/setup-system.ps1
This PR replaces the system architecture check with a method that has a stable output and does not depend on the system locale being set to English or a Latin language to work.
Partly solves #494.
=> Fix for Windows setup script not working in non-Latin systems

core/src/location/indexer/indexer_job.rs, core/src/location/indexer/mod.rs, core/src/location/indexer/shallow_indexer_job.rs, core/src/util/migrator.rs, interface/app/$libraryId/Layout/Sidebar/JobManager.tsx
Fixing the Job Manager message regarding the path being indexed in the front-end. Also fixing some smaller non-related warning on some tests, just to keep Clippy clean.
=> [Eng 493] Job manager status showing incorrect

Cargo.lock, core/Cargo.toml, core/src/job/job_manager.rs, core/src/job/mod.rs, core/src/lib.rs, core/src/location/indexer/mod.rs, core/src/location/indexer/rules.rs, core/src/location/manager/watcher/utils.rs, core/src/node/mod.rs, core/src/object/file_identifier/mod.rs, crates/file-ext/Cargo.toml, crates/file-ext/src/kind.rs
This PR removes the `int-enum` crate as it's essentially useless. We use `repr(i32)`, and provide associated `i32` values - all the crate did was generating the `match` statements but it's simple enough to do ourselves.
=> remove `int-enum`

core/src/location/error.rs, core/src/location/metadata.rs, core/src/location/mod.rs
Currently, we're not planning to support nested locations, so this PR introduce checks to validate that the location path passed to create function isn't a descendant of any location path previously in the database. Also introducing a fix when tried to add a location path already in database that was giving a relink error instead of conflicting with a location path already on database, this happens because before checking DB, we check the `.spacedrive` file. This part is double checked, as someone could just delete `.spacedrive` file and try to add an existing location, so on location create function we check the database.
=> Checking if new location is nested or already exists

packages/ui/src/Popover.tsx
**This PR toggles the Popover off when the user resizes window, this should be the normal behaviour from a UI point of view.** 
- Also fixes a bug where the popover would be moving to left the corner, because it's parent element would be hidden for different screen sizes.
- Used 2 refs, for the button itself and the popover to guarantee the functionality of this expected behaviour.
=> [ENG-468]: Toggle Popover off on window resize

.gitignore, apps/landing/server/index.ts, core/src/api/libraries.rs, core/src/api/utils/invalidate.rs, core/src/lib.rs, core/src/library/manager.rs, core/src/util/debug_initializer.rs, core/src/util/mod.rs, docs/developers/prerequisites/environment-setup.md
This is ENG-494 and ENG-486.
Changes:
- Fix the broken invalidation system. I forgor a `loop` in a recent PR improving the system.
- Add `sd_init.json` support. This will seed data on startup of the app. Designed to make development quicker so you don't need to keep going through the onboarding UI.
=> Eng 494 adding a location does not update the UI

interface/app/onboarding/master-password.tsx, interface/app/onboarding/new-library.tsx, interface/components/PasswordMeter.tsx, interface/index.tsx, packages/ui/src/Button.tsx, packages/ui/src/Input.tsx, packages/ui/src/forms/FormField.tsx
Minor improvements to some onboarding screens
- Add transitions to the password form
- Fix tab order in the Password form
- Remove unimplemented `import Library` button
- Some minor style changes to button focus and form validation error messages
=> [ENG-492] Onboarding "set password" feels kinda clunky

core/src/api/mod.rs, core/src/job/mod.rs, core/src/object/fs/copy.rs, core/src/object/fs/cut.rs, crates/file-ext/src/kind.rs, interface/app/$libraryId/Explorer/ContextMenu.tsx, interface/app/$libraryId/Explorer/File/ContextMenu.tsx, interface/hooks/useExplorerStore.tsx
This prevents some gnarly file truncation issues when files are copied and moved to the same source and destination.
The paste button is hidden in the UI entirely, and then rest validates that the paths do not canonicalize to the same path on the filesystem.
If a file will be overwritten by a copy action, the file will be skipped. During cuts, an error will be returned if the destination file/directory will be overwritten (in any capacity).
=> [ENG-516] Prevent copies/cuts to the same source/dest

interface/app/$libraryId/Explorer/File/Thumb.tsx, interface/app/$libraryId/Explorer/GridView.tsx, interface/app/$libraryId/Explorer/Inspector/index.tsx, interface/app/$libraryId/Explorer/MediaView.tsx, interface/app/$libraryId/Explorer/QuickPreview.tsx, interface/app/$libraryId/Explorer/util.ts, interface/app/$libraryId/settings/library/locations/IndexerRuleEditor.tsx, packages/client/src/utils/index.ts, packages/client/src/utils/objectKind.ts
This PR is a rework of the `FileThumb` component, with multiple bug fixes:
- Fixed tall and long images being displayed with incorrect dimensions (zoomed)
- Fixed application crashes when selecting any non-image file while the inspector was open (at least on Linux)
- Implemented video rendering when requiring a `FileThumb` with `loadOriginal`
- Fixed the inspector's container cropping the `FileThumb` when selecting tall images
- Correctly implemented `size=0` and allowed for `size=null` in `FileThumb`
- Fixed the video extension pill's incorrect position with portrait video (now it will be correctly positioned regardless of the video's aspect ratio)
- Internalized the `mediaAspectSquare` style introduced by `MediaView` (can be enabled with `cover=true`)
- Changed `ObjectKind` to an enum …
=> [ENG-489] FileThumb has incorrect dimensions for some thumbnails

Cargo.lock, Cargo.toml, core/Cargo.toml, core/src/api/files.rs, core/src/api/jobs.rs, core/src/api/keys.rs, core/src/api/libraries.rs, core/src/api/locations.rs, core/src/api/mod.rs, core/src/api/p2p.rs, core/src/api/sync.rs, core/src/api/tags.rs, core/src/api/utils/invalidate.rs, core/src/api/utils/library.rs, core/src/api/utils/mod.rs, core/src/api/volumes.rs
Change the rspc syntax and library query system
=> Rspc v3 syntax

.github/workflows/release.yml, apps/desktop/src-tauri/tauri.conf.json
`Includes additional gstreamer dependencies needed for audio and video playback. This increases the bundle size by ~15-35MB depending on your build system.`
**This flag is currently only supported on Ubuntu build systems.**
=> [ENG-527] - Bundle gstreamer

interface/app/$libraryId/Layout/Sidebar/Footer.tsx, packages/ui/src/Popover.tsx
Instead of closing the popover when the window resizes, it closes when the triggers width === 0. This PR also fixes the issue with nested popovers.
=> [ENG-553] Fix popover open state

.editorconfig, .eslintignore, .github/actions/cache-rust-deps/action.yaml, .github/actions/setup/action.yml, .github/scripts/setup-system.ps1, .github/workflows/cache-factory.yaml, .github/workflows/ci.yml, .gitignore, .vscode/settings.json, apps/releases/next.config.js, apps/releases/package.json, apps/releases/tsconfig.json, interface/app/$libraryId/Explorer/DismissibleNotice.tsx, package.json, packages/config/eslint/base.js
- Ensure version 15 of LLVM is installed in Windows CI (due to` ffmpeg-sys-next`)
- Use `GITHUB_TOKEN` in setup-system.ps1 to avoid rate-limiting by github api in Windows CI
- Add `yaml` settings to `.editorconfig`
- Create a symbolic link from `.prettierignore` to `.eslintignore`
- Move `eslint` root to package root config
- Enable `fileNesting` to reduce dotfile clutter in vscode
- Pass `--strict` to apps/releases `lint` command to avoid making interactive queries and hanging `pnpm lint`
- Format with `prettier` and `eslint`
- Remove empty interface/hooks/useMediaQuery.ts
- Replace unmaintained `actions-rs/toolchain` with `dtolnay/rust-toolchain`
- Change setup-system.ps1 to avoid installing pnpm in CI
- Change `pnpm/action-setup` to lock only o major versions of the action
=> Fix Windows CI + format

.github/scripts/setup-system.sh
this reverts the setup script back to the official ffmpeg package, now that brew offer support for ffmpeg 6.
update guide for devs:
`brew uninstall --force ffmpeg` (`force` removes other versions, too)
`brew untap homebrew-ffmpeg/ffmpeg` (if this errors, run `brew uninstall x` on the package specified in the error. if you get a "tap not found" or similar error, all is well and you can continue)
`brew install ffmpeg`
for good measure, devs should also run `brew tap`. if `spacedriveapp/deps` is present, run `brew untap spacedriveapp/deps` - if this fails, run `brew uninstall ffmpeg@5.0.1` (or the version specified by the error) and re-run `brew untap spacedriveapp/deps`.
the aforementioned custom tap was around when we were manually compiling ffmpeg 5.0.1, but this is no longer required but …
=> revert back to official ffmpeg package (fast ci)

interface/app/$libraryId/Layout/Sidebar/index.tsx
The nav button now visually aligns with the traffic icons on macOS, not tested for Windows/Linux/Web
Before:
After:
=> [Fix] Nav button alignment

core/src/api/files.rs, core/src/library/library.rs, core/src/location/manager/watcher/utils.rs, core/src/object/preview/thumbnail/mod.rs, packages/client/src/core.ts
This PR changes the recent files query to use the `library.has_thumbnail()` query, similar to how the explorer query checks if a thumbnail exists or not.
This also changes how the file watcher validates if a thumbnail exists (for file changes), and now it should correctly update thumbnails if a media file changes. It additionally removes the old thumbnail after generating a new one.
It also adds a helper function for getting the path of a thumbnail via the CAS ID, as the code is repeated a couple of times throughout the codebase.
=> source `has_thumbnail` correctly for the recent file query

core/src/library/manager.rs, interface/app/onboarding/new-library.tsx
This PR adds validation to prevent libraries with either: entirely empty names, or names that consist of purely whitespaces, from being created. It adds validation in both Rust and TS, and they both work flawlessly.
=> [ENG-592] Prevent libraries with blank names/no names from being created

crates/file-ext/src/magic.rs
This PR converts all extensions to lowercase before attempting to match them. This means that files with uppercase extensions (e.g. `.MOV`) will be identified correctly.
=> [ENG-590] Uppercase file extensions are "unknown"

Cargo.lock, core/Cargo.toml
This PR simply removes `ffmpeg-next` from the core.
It turns out that this crate is not used _anywhere_ within the core, except for some commented (pretty old) code.
=> deps: remove ffmpeg-next from the core

core/src/api/files.rs, interface/app/$libraryId/Explorer/File/ContextMenu.tsx, packages/client/src/core.ts
I spent some time thinking about whether this should only show in the recent files view, or if it should show globally for all recent files (in the explorer, too).
To handle the former, we'd need to use `useLocation()` and check the path, or we'd need to somehow tell the Explorer/context menu that we're viewing it from a recent files perspective.
I ended up just checking if the associated object has an access time, and showing the context menu item based on that - we can't remove a file from recents if it was never there to begin with.
=> [ENG-609] Remove file from recent files

interface/app/$libraryId/Explorer/QuickPreview.tsx
Before large images and videos would break quick preview, rendering outside the viewport. Now they will always fit inside the responsive Quick Preview component.
=> [ENG-599] Fix Quick Preview

apps/landing/package.json, apps/landing/server/index.ts, apps/landing/src/App.tsx, apps/landing/src/pages/blog/index.page.tsx, apps/landing/src/pages/blog/post.page.server.ts, apps/landing/src/pages/blog/post.page.tsx, apps/landing/src/pages/docs/doc.page.server.ts, apps/landing/vite.config.ts, pnpm-lock.yaml
Thanks to `vite-plugin-vercel` we can now take advantage of Vercel's Build Output API which allows us to use almost all of Vercel's offerings, including serverless and edge functions, and ISR. Will we use all of these? Idk. Does it make configuration easier? Yes.
=> Use Build Output API for landing page

core/src/library/library.rs, core/src/library/manager.rs, core/src/location/indexer/shallow_indexer_job.rs, core/src/location/manager/watcher/macos.rs, core/src/location/manager/watcher/utils.rs, core/src/location/mod.rs, core/src/object/mod.rs, core/src/object/orphan_remover.rs
Adds an `orphan_remover` actor that runs in the background and can be triggered by sending a message to the `Library.orphan_remover_tx` channel. It could be argued that this should be a job, but I decided against it since:
1) It's not user-initiated
2) It's code that _could_ just be put in a function and called in different places.
I think an actor is a better choice to reduce db contention and have it performed asynchronously from latency-sensitive file path operations.5
Closes ENG-583
=> Orphan Object Remover

.github/scripts/setup-system.sh
macOS (Ventura? arm?) requires all `dylibs` to be signed to allow a process to launch[¹].
This PR locally signs our ffmpeg `dylibs` with the machine's local certificate in the `setup-system` script after downloading them to work around this issue.
[¹]: https://github.com/tpoechtrager/osxcross/issues/355
=> Fix Spacedrive process being `Killed` during lauch on macOS

Cargo.toml, apps/cli/Cargo.toml, apps/desktop/crates/macos/Cargo.toml, apps/desktop/src-tauri/Cargo.toml, apps/mobile/crates/android/Cargo.toml, apps/mobile/crates/core/Cargo.toml, apps/mobile/crates/ios/Cargo.toml, apps/server/Cargo.toml, core/Cargo.toml, crates/crypto/Cargo.toml, crates/deps-generator/Cargo.toml, crates/ffmpeg/Cargo.toml, crates/file-ext/Cargo.toml, crates/macos/Cargo.toml, crates/p2p/Cargo.toml, crates/prisma-cli/Cargo.toml, crates/sync-generator/Cargo.toml, crates/sync/Cargo.toml, crates/sync/example/Cargo.toml
This makes our license identifier valid (SPDX) and applies it to all of our crates. I added it to every `Cargo.toml` (as well as `repository` and `edition`) just for consistency, so all re-used metadata is correctly declared everywhere.
=> SPDX license and workspace inheritence for re-used metadata

.github/scripts/setup-system.sh, Cargo.lock, apps/desktop/src-tauri/Cargo.toml, core/src/object/preview/thumbnail/mod.rs, crates/heif/Cargo.toml, crates/heif/src/lib.rs
This PR simply disables HEIF images from being viewable on Linux (due to Ubuntu's archaic `libheif` version), and it removes the need for the `png` crate by going directly from raw RGB sequence data -> a `DynamicImage`.
It's arguably not as efficient as going straight to WebP, but it's still world's better than before.
=> HEIF Fixes and Improvements

core/src/location/file_path_helper/isolated_file_path_data.rs
There appears to be no benifit to preserving the file extention casing, especially only in production. Everything works great in dev, but in prod on macOS uppercase extensions are not compatible with Spacedrive, most notably the thumbnailer.
After some light research it appears all modern file systems are case insensitive, though this has only been tested in macOS. 
This PR removes the debug assertion encasing the lowercase coercion.
_Dev VS Prod without this fix_
=> [END-634] Coerce file extensions to lowercase

Cargo.lock, core/Cargo.toml, core/prisma/schema.prisma, core/src/lib.rs, crates/prisma/Cargo.toml, crates/prisma/src/lib.rs
Moves generated Prisma stuff into a separate cate with the aim of improving compile times. Might not help that much but ehh.
=> move prisma codegen into sd-prisma

interface/app/$libraryId/Layout/Sidebar/Link.tsx, interface/app/$libraryId/settings/library/locations/IndexerRuleEditor/RulesForm.tsx
This PR does the following:
- Focus button of sidebar link now looks better
- Tooltip text adjustment for index rules UI
- Removed 'by glob' in index rules UI dropdown when selecting a mode.
**The web version of the focus of a sidebar link is now this, ugly effect is gone**:
**Updated dropdown text**
=> [ENG-642] Minor UI Tweaks 

interface/app/$libraryId/TopBar/TopBarOptions.tsx
**This is a simple change that fixes the following issue demonstrated in this image**:
Clicking elements within the Popover component would trigger the tooltip.
**Result of this change confirming the fix**:
https://github.com/spacedriveapp/spacedrive/assets/33054370/d2fcbd1c-7e6d-470f-aa42-0412f1e0eeec
=> [ENG-661] Tooltip Topbar Bug fix

interface/app/$libraryId/settings/library/locations/AddLocationDialog.tsx, interface/app/$libraryId/settings/library/locations/IndexerRuleEditor/index.tsx
In preps for release, this is a minor UI tweak to the index rules UI. I also added props to allow us to modify the classes when we use the component in other places.
**Screenshots**:
=> [ENG-666] Index rules UI tweak

core/src/api/search.rs, packages/client/src/core.ts
Exposes `include` and `exclude` as `hidden` filters for `search.objects`
=> [ENG-678] Hidden object filtering

core/src/location/indexer/shallow.rs, core/src/object/file_identifier/shallow.rs, core/src/object/preview/thumbnail/shallow.rs
Location watchers aren't sending updates for me but at least the shallow operations can notify the frontend of invalidations now
=> [ENG-688] Invalidate search.paths in shallow operations

apps/desktop/src-tauri/Cargo.toml, apps/desktop/src-tauri/src/main.rs, core/src/p2p/p2p_manager.rs, core/src/util/migrator.rs, interface/ErrorFallback.tsx, interface/app/Spacedrop.tsx
Spacedrop's UI isn't ready to be in anyone hands because we need to keep a high standard in our UI.
Also fixing a bunch of random problems, including better support for people coming from a super old version of Spacedrive.
=> [ENG-694] Remove Spacedrop

Cargo.lock, apps/desktop/src/App.tsx, apps/mobile/src/components/explorer/FileThumb.tsx, apps/web/src/App.tsx, core/Cargo.toml, core/src/api/jobs.rs, core/src/api/locations.rs, core/src/api/mod.rs, core/src/api/search.rs, core/src/custom_uri.rs, core/src/object/preview/thumbnail/directory.rs, core/src/object/preview/thumbnail/mod.rs, core/src/object/preview/thumbnail/shallow.rs, core/src/object/preview/thumbnail/shard.rs, core/src/object/preview/thumbnail/thumbnailer_job.rs, core/src/util/mod.rs, core/src/util/version_manager.rs, interface/app/$libraryId/Explorer/File/Thumb.tsx, interface/app/$libraryId/Explorer/index.tsx, interface/app/$libraryId/Explorer/util.ts, interface/app/$libraryId/location/$id.tsx, interface/app/$libraryId/overview/data.ts, interface/app/$libraryId/search.tsx, interface/hooks/useExplorerItemData.ts, interface/hooks/useExplorerStore.tsx, interface/util/Platform.tsx, packages/client/src/core.ts
This is a simple PR to improve the way we store thumbnails in the data folder. After a nice chat with ChatGPT I discovered why most apps do this, I noticed even Apple apps store files internally in hex-coded folders to prevent directory sizes from growing too large. Since my thumbnail folder is well over 85,000 items and takes a minute to open in Finder it could probably become an issue faster than we'd expect. This is an industry standard format for storing large collections of cached files. 
`calc_shard_hex` takes a cas_id as input, computes a blake3 hash of the filename, and returns the first two characters of the hash as the directory name. Because we're using the first two characters of a blake3 hash, this will give us 256 (16*16) possible directories, named 00 to ff.
This PR also …
=> [ENG-708] Thumbnail sharding

core/src/library/manager.rs, core/src/location/indexer/rules.rs
`default` is now properly set, plus the rules seeder is ran on library load
=> Fix default system rules

interface/app/$libraryId/Explorer/File/DeleteDialog.tsx, packages/ui/src/CheckBox.tsx
This PR updates the delete dialog visually, it was weird having the TODO.
- Also updated the color of checkbox to our accent color.
=> [ENG-718] checkbox bg color accent + delete file dialog tweak

.github/scripts/setup-system.ps1, Cargo.lock, Cargo.toml, apps/desktop/crates/linux/Cargo.toml, apps/desktop/crates/linux/README.md, apps/desktop/crates/linux/src/desktop_entry.rs, apps/desktop/crates/linux/src/handler.rs, apps/desktop/crates/linux/src/lib.rs, apps/desktop/crates/linux/src/system.rs, apps/desktop/crates/linux/tests/cmus.desktop, apps/desktop/crates/macos/Cargo.toml, apps/desktop/src-tauri/Cargo.toml, apps/desktop/src-tauri/src/file.rs, apps/desktop/src/commands.ts, interface/app/$libraryId/Explorer/File/ContextMenu/OpenWith.tsx, interface/util/Platform.tsx
=> [ENG-593] Implement `Open With` for Linux

interface/app/$libraryId/location/$id.tsx
Truncate the folder name when it's too long; otherwise, it's going to a new line, and I have centred the folder icon and the name.
=> added text wrapping with ... when folder name too long

.github/scripts/setup-system.ps1, Cargo.lock, apps/desktop/crates/linux/src/desktop_entry.rs, apps/desktop/crates/linux/src/system.rs, apps/desktop/crates/windows/Cargo.toml, apps/desktop/crates/windows/src/lib.rs, apps/desktop/src-tauri/Cargo.toml, apps/desktop/src-tauri/src/file.rs, apps/desktop/src/commands.ts, interface/app/$libraryId/Explorer/File/ContextMenu/OpenWith.tsx, interface/app/$libraryId/overview/Categories.tsx, interface/util/Platform.tsx, packages/client/src/core.ts
=> [ENG-594] `Open With` Windows + fixes

interface/components/GridList.tsx
When the horizontal scrollbar appears on window resizing, there is a white square on the bottom right corner for the grid list. This change only applies to the grid list. Because you cant horizontally scroll on the grid list due to the items resizing, I disabled the scrollbar entirely. The list view does not have this anymore because theres no horizontal scrollbar.
Closes #855
=> Bug fix: Remove unnecessary horizontal scrollbar on grid list to remove white square

core/src/api/tags.rs
There was a very odd issue with PCR's iterator-based stuff, so I have simplified it a little and got it working.
Tags can now be both assigned and unassigned.
=> Fix tag removal

core/src/api/files.rs, core/src/api/jobs.rs, core/src/job/error.rs, core/src/location/file_path_helper/mod.rs, core/src/location/indexer/indexer_job.rs, core/src/location/indexer/shallow.rs, core/src/location/mod.rs, core/src/object/file_identifier/file_identifier_job.rs, core/src/object/file_identifier/shallow.rs, core/src/object/preview/thumbnail/shallow.rs, core/src/object/preview/thumbnail/thumbnailer_job.rs, core/src/object/validation/mod.rs, core/src/object/validation/validator_job.rs, interface/app/$libraryId/Explorer/ContextMenu.tsx, interface/app/$libraryId/Explorer/File/ContextMenu.tsx
Using `sub_paths` was a bit error prone, as sometimes an empty string was being passed to the backend, because of this now we have a better handling for `''` and also for `'/'` as the later is the location root path. This part was fixed on every job that accepted a `sub_path`.
Aside from this, `ObjectValidatorJob` was kinda broken, so now it is fixed. 
Also found some bugs on rename backend having conflicts with the file watcher. And now it will attempt to rename every file in the case of multiple rename, instead of stopping in the first error
=> [ENG-768 / ENG-769] Regen thumbnails / Generate checksums

crates/ffmpeg/Cargo.toml, crates/ffmpeg/src/error.rs, crates/ffmpeg/src/movie_decoder.rs
If the FFmpeg lib ran into a video that was corrupt, the app would force close without warning. This resolves that.
If a video has subtitles, a thumbnail will not be generated.
=> [ENG-828, ENG-633] Fix corrupt videos force crashing the app

crates/ffmpeg/src/error.rs, crates/ffmpeg/src/movie_decoder.rs
This uses the constant provided by the FFmpeg library, to be more correct.
This does **not** change the probe value, as that is the sole reason the app crashes when FFmpeg runs into an error.
A probe value of 100 means that the video is perfect and has no corruption, and any value less will certainly make the app crash if it runs into a video with either: subtitles, or is corrupt in any way. I have tested this logic briefly, by using a probe score of `<= 80`, and the app force crashed.
The other part of the code did nothing, hence the `TODO`, so it's been removed.
=> [ENG-828-FIX] Make trivial changes to the previous ENG-828 merge

interface/app/$libraryId/Explorer/Context.tsx, interface/app/$libraryId/Explorer/ContextMenu/FilePath/Items.tsx, interface/app/$libraryId/Explorer/ContextMenu/FilePath/index.tsx, interface/app/$libraryId/Explorer/ContextMenu/Location/index.tsx, interface/app/$libraryId/Explorer/ContextMenu/Object/index.tsx, interface/app/$libraryId/Explorer/ContextMenu/SharedItems.tsx, interface/app/$libraryId/Explorer/ContextMenu/index.tsx, interface/app/$libraryId/Explorer/ParentContextMenu.tsx, interface/app/$libraryId/Explorer/QuickPreview/Context.tsx, interface/app/$libraryId/Explorer/View/index.tsx, interface/app/$libraryId/Explorer/index.tsx, interface/app/$libraryId/Explorer/store.ts, interface/app/$libraryId/Layout/Sidebar/JobManager/Job.tsx, interface/app/$libraryId/Layout/Sidebar/JobManager/useJobInfo.tsx
The issue of the wrong items being rendered in the QuickPreview should have been fixed sometime around #1029, but I didn't consider that `QuickPreview` needs to be rendered outside of `Explorer` sometimes. Now we render it inside `View`.
This doesn't address objects only previewing with thumbnails, it's been that way for a while.
=> [ENG-829] Render QuickPreview in Explorer/View

interface/app/$libraryId/Explorer/index.tsx
If there's no items it doesn't really make sense to display the notice
=> Hide DismissibleNotice when no items

interface/app/$libraryId/Layout/Sidebar/Link.tsx
This just adds a check for if the app is running on desktop, and if so then will re-click the navlink as if no keys were pressed.
=> [ENG-798] Override new tab behaviour for NavLink on desktop

packages/client/src/hooks/usePlausible.tsx
I had erroneously missed the `g` flag from our UUID replacement regex, but this fixes it.
Thank you @HeavenVolkoff for the guidance here.
=> [ENG-857] Fix telemetry regex

apps/mobile/src/screens/settings/library/EditLocationSettings.tsx, apps/mobile/src/screens/settings/library/LocationSettings.tsx, core/src/api/locations.rs, core/src/job/worker.rs, crates/file-ext/src/extensions.rs, crates/file-ext/src/magic.rs, interface/app/$libraryId/Explorer/ContextMenu/FilePath/Items.tsx, interface/app/$libraryId/Explorer/ParentContextMenu.tsx, interface/app/$libraryId/location/LocationOptions.tsx, interface/app/$libraryId/settings/library/locations/$id.tsx, interface/app/$libraryId/settings/library/locations/ListItem.tsx, packages/client/src/core.ts
Files with a `mts` extension were always showing as video files, where they could also be code files, as in `.d.mts` files. This way we try to check for `mts` video files magic bytes to be sure. 
I wasn't able to reproduce the bug for `.ts` files, I think this one is solved by recent location watcher improvements.
=> [ENG-850] Wrongly labelled .ts files (as video)

.github/scripts/setup-system.ps1
Added a check for the winget version to ensure it meets the minimum required version. If the winget version is outdated, the script now exits with an appropriate error message.
This is just a commit that addresses this https://github.com/spacedriveapp/spacedrive/blob/5df1d9a091fec792c72fff45ef9acc5afd4a6a2b/.github/scripts/setup-system.ps1#L165
=> Check winget version and require update if necessary

apps/mobile/src/main.tsx, packages/client/src/hooks/usePlausible.tsx
ez, why?
> It just doesn't make sense here. You would need to convert and match all the screen/route names and they just wont work together.
=> [MOB-31] Separate analytics for mobile

core/src/api/libraries.rs, core/src/library/manager.rs, core/src/object/thumbnail_remover.rs
Library deletion was hanging forever due to a deadlock in the `LibraryManager`, we were acquiring a read lock and then tried to acquire a write lock while the read lock was still in scope.
Closes #1102
=> [ENG-794] Library deletion hangs

.github/scripts/setup-system.sh
Occasionally (or always?) on fresh Fedora Workstation installs, the `openssl` package isn't actually present so I've added it as a dependency.
I've also included `clang-devel` as that seemed to fix a major issue I was having, but could be purely coincidental.
=> Include `openssl` and `clang-devel` in the Fedora dependencies

packages/ui/src/Input.tsx
I made modifications to the UI because every text input was suggesting an autocomplete.
However, you can still enable autocomplete by adding `autoComplete="on"` to the respective input fields.
Closes #1152
=> Removed Browsers AutoSuggestions from inputs

interface/app/$libraryId/Explorer/FilePath/Thumb.tsx, interface/app/$libraryId/Explorer/Inspector/index.tsx
Hi!
I gave this a try, let me know what you think :) 
A new "paused" prop on the FileThumb is used to pause and unpause when the quick-view is opened and closed.
Closes #1177
=> [ENG-960] pause inspector thumbnail while quick preview is open

interface/app/onboarding/Layout.tsx, interface/app/onboarding/Progress.tsx, interface/app/onboarding/alpha.tsx, interface/app/onboarding/context.tsx, interface/app/onboarding/creating-library.tsx, interface/app/onboarding/index.tsx, interface/app/onboarding/new-library.tsx, interface/app/onboarding/privacy.tsx, packages/client/src/hooks/useOnboardingStore.ts, packages/ui/src/Button.tsx, packages/ui/src/forms/Form.tsx
Currently, each onboarding page contains its own `useZodForm`, inserts data into `onboardingStore`, and then the `/onboarding/creating-library` route executes the `library.create` mutation in a `useEffect` (eew yucky).
Now, the onboarding `Layout` holds a singular form state that is provided via context to all the sub-routes. The sub-routes then consume this form in their own `Form` components, but none except the final `/onboarding/privacy` route actually call the main `onSubmit` handler, which when called is in charge of navigating to `/onboarding/creating-libraries` (rather than the other way around!).
=> Move onboarding form handling logic to Layout

interface/app/$libraryId/Explorer/QuickPreview/Context.tsx, interface/app/$libraryId/Explorer/View/index.tsx, interface/app/$libraryId/TopBar/Layout.tsx, interface/app/$libraryId/TopBar/Portal.tsx, interface/app/$libraryId/TopBar/index.tsx
Mr Dan Abramov himself has decreed that thou shan't read or write refs during render, thus some of our usages of `createPortal` are sus:
> Don’t read or write ref.current during rendering. If some information is needed during rendering, use state instead.
A normal app would probably get away with it tbh but we use concurrent features so it's reeeeealy not a good idea (reading them as an initial value for `useState` should be fine though).
=> Store portal elements as state instead of refs

.clippy.toml, core/crates/sync/src/ingest.rs, core/crates/sync/src/manager.rs, core/crates/sync/tests/lib.rs, core/src/api/jobs.rs, core/src/api/locations.rs, core/src/api/utils/invalidate.rs, core/src/library/manager/mod.rs, core/src/object/fs/copy.rs, core/src/object/fs/mod.rs, core/src/p2p/pairing/mod.rs, core/src/p2p/pairing/proto.rs, core/src/p2p/sync/mod.rs, core/src/p2p/sync/proto.rs, core/src/preferences/kv.rs, core/src/preferences/mod.rs, core/src/util/mpscrr.rs
When we were duplicating directories, we weren't account for possible files that exist in that directory but weren't indexed to our database, like `.DS_Store` files. It was breaking up the `FileCopierJob`. 
Also solved a bunch of core warning that were getting on my nerves.
=> [ENG-835] Duplicating an empty directory doesn't duplicate nested empty directories

core/src/api/files.rs
Now we check at rspc route if we received just a single file/directory to be removed, just removing it instead of dispatching a job.
Closes #1144
=> [ENG-644] Deleting a single file should be background job

.github/scripts/setup-system.sh
This pull request addresses the issue where actions triggered by non-main branches were being included in the workflow runs.
The code modification ensures that only actions triggered by the main branch are considered for further processing.
=> scripts: filter actions by main branch in workflow runs

interface/app/$libraryId/Explorer/index.tsx, interface/app/style.scss
Hey @brxken128,
I appreciate your observation regarding the missing scrollbar on the Explorer. I've looked into this, and it turns out that the scrollbar is actually present but not easily visible due to its color being the same as the background of the Explorer. However, you can still interact with it by hovering over it and dragging from the right edge to initiate scrolling.
Here are some screenshots - Before Fix:
Screenshot After Fix:
To address this issue, I removed the `custom-scroll` Class that was causing the scrollbar to be constantly visible. Instead, I've added the `overflow-y-auto` Class, which ensures that the scrollbar appears only when needed.
Additionally, I've made some modifications to the CSS file (`.scss`) to ensure that the scrollbar is visible. Previously, it was …
=> [ENG-976] Fixed Missing scrollbar in the Explorer

core/src/api/search.rs, interface/app/$libraryId/Explorer/store.ts, interface/app/$libraryId/ephemeral.tsx, packages/client/src/core.ts
This doesn't actually utilise the query, but just makes it exist.
Whether this will help with making scroll navigation work properly is tbd, but I'm not sure what the best approach is so for now we'll implement whatever the UI needs.
=> [ENG-992] Add `search.pathsCount` route

core/src/api/search.rs, interface/app/$libraryId/location/$id.tsx, interface/app/$libraryId/overview/data.ts, packages/client/src/core.ts
Adds backend capability for search queries to use offset pagination instead of cursor pagination. How this will be used remains to be seen but it's now at least possible.
=> [ENG-1004] Add offset pagination capability to search queries

.github/scripts/setup-system.ps1, apps/desktop/crates/windows/src/lib.rs, apps/desktop/vite.config.ts, core/crates/sync/tests/lib.rs, packages/config/vite/relativeAliasResolver.ts
- Fix Vite `relativeAliasResolver` on Windows
- Add Strawberry Perl installation to setup-system.ps1 (stop rust-analyzer from crashing on Windows)
- Remove unused imports from desktop windows crate
- Add todo for missing sync test match cases
=> [ENG-1027] Fix build on Windows

interface/app/$libraryId/Layout/Sidebar/JobManager/JobContainer.tsx
Quick fix - addresses overflowing and centering tooltip.
=> [ENG-1017] Job name tooltip center

Cargo.lock, core/Cargo.toml, core/src/object/media/thumbnail/mod.rs, crates/heif/Cargo.toml, crates/heif/src/lib.rs, crates/svg/Cargo.toml, crates/svg/src/lib.rs
Introduces a new `sd-svg` crate inspired by `sd-heif` to allow integrating our `Thumbnailer` to parse SVGs:
[resvg](https://github.com/RazrFalcon/resvg) and [tiny-skia](https://github.com/RazrFalcon/tiny-skia) are used to parse and render the SVG and the RGBA data is converted to a `DynamicImage` that will be handled by the `Thumbnailer`
=> [ENG-904] Thumbnail for `svg`

packages/ui/src/Dialog.tsx
A bug was introduced in PR #1279 where a dialog would only close if the form state was valid, however this is not available everywhere so dialogs weren't closing in the vast majority of cases. This fixes that bug.
=> Fix dialog entry

core/src/api/jobs.rs, core/src/location/mod.rs, core/src/object/media/media_data_extractor.rs, core/src/object/media/media_processor/job.rs, core/src/object/media/media_processor/mod.rs, core/src/object/media/media_processor/shallow.rs, core/src/object/media/thumbnail/mod.rs, interface/app/$libraryId/Explorer/ContextMenu/FilePath/Items.tsx, interface/app/$libraryId/Explorer/ParentContextMenu.tsx, packages/client/src/core.ts
Introducing a new `renegerate` param to `MediaProcessorJob` asking for regenerating thumbnails already existing instead of skipping.
=> [ENG-1063] Actually regenerate thumbnails on `Regen Thumbnails` button

apps/desktop/src-tauri/src/main.rs, core/src/library/library.rs, core/src/location/metadata.rs, core/src/location/mod.rs, core/src/p2p/p2p_manager.rs
Removing stale libraries data from libraries that doesn't exist anymore from `.spacedrive` file.
Also minor clippy warnings.
=> [ENG-198] Cleaning up after removing a location

apps/mobile/src/components/modal/job/JobManagerModal.tsx, apps/storybook/postcss.config.js, core/src/api/jobs.rs, core/src/custom_uri.rs, core/src/p2p/p2p_manager.rs, interface/app/$libraryId/Explorer/ContextMenu/FilePath/Items.tsx, interface/app/$libraryId/Explorer/ParentContextMenu.tsx, interface/app/$libraryId/Layout/Sidebar/FeedbackDialog.tsx, interface/app/$libraryId/Layout/Sidebar/JobManager/index.tsx, interface/app/$libraryId/settings/library/locations/AddLocationDialog.tsx, packages/client/src/core.ts, packages/ui/src/Button.stories.tsx
The rspc route returns job reports clustered by library ids, but the frontend isn't able to handle that yet, maybe it will need some UI changes for that, which aren't my strong suit.
For now the frontend just gather and shows up job reports from all libraries together without any indication of from what library that report belongs to.
Some minor clippy warnings
pnpm format
Closes #1162
=> [ENG-941] Jobs running in another library do not appear in the job manager

.gitmodules
Feel free to close this, but multiple people have mentioned that the git submodule for `test-files` has just been messing absolutely everything up - I've experienced it too.
We will sort out a correct test-files setup, either via a CDN, cloning the repo itself or maybe even a quick Google Drive download.
=> fix: remove the git submodule for test-files

interface/app/$libraryId/Explorer/View/GridList.tsx, interface/app/$libraryId/Explorer/View/ListView.tsx, interface/app/$libraryId/TopBar/SearchBar.tsx
After an evaluation, most shortcuts required are all in place. 
But I also added the idea of being able to press 'Esc' to deselect all selected items. This makes using other shortcuts more accessible, instead of having the user to de-select manually first.
=> [ENG-814] Explorer shortcuts: Escape de-selects all selected items

core/src/api/jobs.rs, core/src/object/file_identifier/mod.rs, core/src/object/file_identifier/shallow.rs, core/src/object/media/media_data_extractor.rs, core/src/object/media/media_processor/mod.rs, core/src/object/media/thumbnail/mod.rs, core/src/object/thumbnail_remover.rs
The issue was due to a bug found in the `futures_concurrency` crate, reported at https://github.com/yoshuawuyts/futures-concurrency/issues/155
For the time being, I changed all occurrences of `TryJoin` and `Join` from our codebase to use equivalents from `futures` crate, even though I dislike their ergonomics.
Also fixed some small bugs.
=> [ENG-1076] Opening a sub dir closes the app

.github/workflows/server.yml
Remove `ghcr.io` from the server's docker image name, as the registry is already being appended by `buidah`
=> Fix typo server.yml

.gitignore, core/src/location/file_path_helper/mod.rs, core/src/location/indexer/indexer_job.rs, core/src/location/indexer/mod.rs, core/src/location/indexer/shallow.rs, core/src/location/indexer/walk.rs, core/src/location/manager/watcher/linux.rs, core/src/location/manager/watcher/macos.rs, core/src/location/manager/watcher/utils.rs, core/src/location/manager/watcher/windows.rs, core/src/location/non_indexed.rs
This PR presents a way to calculate directory sizes for all directories in an indexed location in a really lightweight manner, using data about each file size already extracted in the walker for indexer job and shallow indexer. It also takes into account size updates in a directory for files being added through the watcher. 
In case of new or updated files found through indexer jobs or shallow indexers that were using a sub path in a given location, we back propagate the updated size calculations back to ancestor directories.
Now we also dispatch sub path scans for new directories found through the shallow indexer.
Closes #1149
=> [ENG-812] Folder size calculation

Cargo.lock, core/Cargo.toml, core/src/location/file_path_helper/mod.rs, core/src/location/indexer/mod.rs, core/src/location/indexer/shallow.rs, core/src/location/indexer/walk.rs, core/src/object/media/thumbnail/mod.rs
Could't replicate the desired bug, but found a different one. Introduced more aggressive logging of when a file is marked to be updated, explaining why.
=> [ENG-1139] Walker wrongly marking files for update

apps/mobile/modules/sd-core/android/build.gradle
Changed `build.gradle` in the android folder to properly find `llvm-ranlib` for Linux and Windows machines. Windows has not been tested yet. 
Closes #1387
=> Fix mobile core not building on non-darwin machines

interface/app/$libraryId/Layout/Sidebar/WindowControls.tsx, interface/app/$libraryId/TopBar/NavigationButtons.tsx, interface/app/$libraryId/TopBar/TopBarOptions.tsx, interface/app/$libraryId/TopBar/index.tsx, interface/app/$libraryId/settings/Sidebar.tsx, interface/components/DragRegion.tsx
Windows and Linux have a top bar Mac does not hence the need for the drag regions.
=> [ENG-1117] Remove Tauri drag regions on non-macOS platforms

README.md, SECURITY.md, crates/crypto/README.md
Self explanatory. We could probably sign these, but the `security.txt` file is signed which should validate all of the information displayed anyway.
=> [ENG-1165] Add a security policy and notices to the appropriate READMEs

apps/desktop/src-tauri/Cargo.toml, apps/desktop/src-tauri/src/main.rs, apps/mobile/modules/sd-core/core/src/lib.rs, apps/server/src/main.rs, core/src/api/auth.rs, core/src/env.rs, core/src/lib.rs
Backend now requires adhering to the actual OAuth spec, with client ids and secrets and everything.
Shipping client secrets may seem insecure but GitHub do it and from what I can tell it's secure - GitHub do it for their CLI.
The main security vuln I want to protect us from is open redirects. Since we're only using device flow this isn't an issue atm, but in future if we allow external OAuth clients we'll want to either restrict our first-party apps to allow device flow only, or use more custom auth methods like forcing redirecting to a localhost server or using a deeplink (mobile) if a particular client ID is provided.
I think we'll keep using device flow for server deployments no matter what since preventing open redirects on them seems really hard.
=> Use actual oauth clients + ship ids and secrets

interface/app/$libraryId/Layout/Sidebar/index.tsx
When navigating with keyboard, this prevents sidebar scrolling from happening. **This has been tested to ensure that it doesn't affect other functionalities.**
- By default all overflowing elements have scrolling support with keyboard by the browsers, we need to prevent that by targeting the up and down arrow keys.
=> [ENG-1170] - Prevent sidebar scrolling with keyboard

interface/app/$libraryId/TopBar/NavigationButtons.tsx, interface/app/$libraryId/settings/client/keybindings.tsx
This makes you able to navigate backwards and forwards using Meta + [ and Meta + ] - at the sametime we also have support with arrow keys, as most apps **(seems to be native)**.
=> [ENG-1172] - Update navigation keys

.vscode/launch.json, .vscode/tasks.json, apps/desktop/src-tauri/src/main.rs
This PR enables Frontend's dev tools when Spacedrive is compiled in dev mode and a `SD_DEVTOOLS` environment variable in set. Making the dev tools open alongside the app. Very useful for frontend debugging.
=> Enabling frontend dev tools

apps/desktop/src-tauri/src/main.rs, apps/mobile/modules/sd-core/core/src/lib.rs, apps/server/src/main.rs, core/src/env.rs
Our apps will use a special token refreshing strategy employing JWTs that other apps won't be allowed to use, removing the need to ship client secrets with the apps. Client secrets have already been rotated.
=> Remove client secret from apps

interface/app/$libraryId/Explorer/ContextMenu/FilePath/Items.tsx, interface/app/$libraryId/Explorer/View/index.tsx, interface/app/$libraryId/settings/client/keybindings.tsx
- For windows, Enter key now opens the selected folder/item.
- CMD + O to open folder on mac, this was already implemented, but the prev func was no longer needed anymore.
- Open in context menu was opening the item in Finder, but this has now been corrected to open in Spacedrive.
=> [ENG-872, ENG-1177] - Windows enter key opens & Open context menu correction

core/src/api/utils/invalidate.rs, core/src/custom_uri/mod.rs
LRU cache was never invalidated and it broke.
=> [ENG-982] Can't load original after renaming

interface/app/$libraryId/Layout/Sidebar/Contents.tsx, interface/app/$libraryId/Layout/Sidebar/Footer.tsx, interface/app/$libraryId/settings/client/keybindings.tsx, interface/app/style.scss, packages/ui/src/Tooltip.tsx
**This PR does the following:**
- New overview shortcut:  **Shift, Meta/Ctrl,  O**
- Settings page shortcut changed to: **Shift, Meta/Ctrl,  S**
**More will be added in future after the new shortcuts system**
**Fixes**:
- Incorrect symbols were being display for other OSs, i corrected this. This is also for tooltips.
- The keybind page needs 1 more refactor, this will be done in future.
=> [ENG-1189] Overview shortcut + Settings shortcut adjusted

core/src/api/files.rs, core/src/object/fs/copy.rs, core/src/object/fs/cut.rs, core/src/object/fs/mod.rs, interface/app/$libraryId/Explorer/ContextMenu/FilePath/CutCopyItems.tsx, interface/app/$libraryId/Explorer/ParentContextMenu.tsx, packages/client/src/core.ts
During: copying, cutting, duplicating and renaming we now will append the lowest available digit to the file name if it would overwrite the source file.
The only "bug" I have ran into is when renaming say `File (2).jpg` to `File.jpg`, it will increment the name to `File (3).jpg` when it should in fact remain as `File (2).jpg` (as that's the largest available number, but it already exists so it gets incremented.
A preview:
This may need some pretty heavy battle-testing before merge, as it could end up truncating files if it goes wrong (it shouldn't, as the action should only ever happen if the `fs::metadata` call is an `Err` (the file doesn't exist).
=> [ENG-1176] Append `(x)` to the end of files instead of overwriting

interface/app/$libraryId/Explorer/View/GridView.tsx, interface/app/$libraryId/Explorer/View/ListView/util/table.tsx
This hides folder size in Ephemeral locations, grid and list view are handled.
- We currently don't have support to measure sizes of folders in Ephemeral locations.
**Image**:
=> [ENG-1195] Hide folder size in Ephemeral locations

apps/desktop/src-tauri/tauri.conf.json, apps/landing/src/app/api/releases/tauri/[version]/[target]/[arch]/route.ts
Just wanted to do this before release so that we can support release channels without the custom header at some point.
=> Add version to updater endpoint

CONTRIBUTING.md
The dev tools are opened using `CmdOrCrtl+Alt+I` so I updated the `CONTRIBUTING.md` to reflect this.
=> fix: dev tools shortcut

apps/desktop/src-tauri/src/main.rs, apps/desktop/src-tauri/src/updater.rs, apps/desktop/src/App.tsx, apps/desktop/src/commands.ts, apps/desktop/src/updater.tsx
Updater now has to be enabled by the backend else it won't be available in `usePlatform`.
`.deb` detection logic taken from [Tauri's implementation](https://github.com/tauri-apps/tauri/blob/tauri-v1.3.0/core/tauri/src/app.rs#L944).
=> [ENG-1214] Disable updater for `.deb` distrubutions

apps/mobile/src/App.tsx, interface/app/$libraryId/Layout/index.tsx, packages/client/src/hooks/usePlausible.tsx, packages/client/src/hooks/useTelemetryState.tsx
This PR cheekily makes use of the `BuildInfo` bridge query - sorry @oscartbeaumont but I went the Tauri plugin embed route but had no clue how to handle it on mobile or web, so this was just the easiest option. We use it anyway to show the app's commit hash, so it's not as though I specifically made a query to handle it.
The commit hash would probably be easier to manage than the specific app versions anyway, as we can pinpoint *exactly* what state the app was in at the time of a potential error.
Edit: it works!
=> [ENG-428] Embed app version and commit hash for telemetry

core/src/api/files.rs, core/src/api/utils/invalidate.rs, core/src/volume/mod.rs, core/src/volume/watcher.rs
This fixes the issue of not having udevadm inside the docker image, reusing the same code we already have for getting volumes. Tried my hand at fixing the invalidate query macro to return new data.
=> [ENG-1222] `udevadm` doesn't exist in Docker container

apps/landing/posts/october-alpha-release.mdx
There are some small grammatical errors in the [Alpha Release Blog Post](https://www.spacedrive.com/blog/october-alpha-release). This PR fixes them. You can compare the new version and the old version in Grammarly to see if there are any outstanding errors.
No current issue to close.
=> Fix small grammatical errors on the alpha release blog post

interface/app/$libraryId/settings/library/general.tsx
Deconstructing isValid is required to ensure a subscription and updating of the formState.isValid value.
=> [ENG-1249] Library description update fix

core/src/lib.rs, core/src/location/indexer/indexer_job.rs, core/src/location/indexer/shallow.rs, core/src/location/manager/watcher/utils.rs, core/src/location/mod.rs, core/src/location/non_indexed.rs, core/src/object/media/thumbnail/actor.rs, core/src/object/media/thumbnail/mod.rs, core/src/object/mod.rs, core/src/volume/watcher.rs, crates/ffmpeg/src/lib.rs, crates/ffmpeg/src/thumbnailer.rs
This PR introduces new capabilities to our thumbnailer actor, procing thumbnails in batches and with background processing for ephemeral locations, prioritizing the directory the user has opened in the explorer.
=> [ENG-1225] Put brakes on thumbnail generation for ephemeral locations

interface/components/TextViewer/index.tsx
Fixes the text viewer duplicating file content on rerender
issue spotted by [Tim on the Discord](https://discord.com/channels/949090953497567312/1121730047993200640/1161808831647584407)
https://github.com/spacedriveapp/spacedrive/assets/65303441/70c1e8d1-ab65-4c19-a2dc-7bea7b8f0e80
https://github.com/spacedriveapp/spacedrive/assets/65303441/b8eae6bc-ab21-442b-b96b-e3851b597385
Also shrinks the size of the text to fit more content on screen:
=> fix text viewer duplicate content on rerender & shrink font

interface/app/$libraryId/TopBar/NavigationButtons.tsx
- Users reported that the navigation on windows using mouse was navigating 2 routes back and forth. This is due to the useEffect, however, after testing, it seems by default Tauri offers this by default for windows.
Tested on Windows and can confirm it's all good.
=> [ENG-1250] Fix windows mouse navigation

core/src/api/locations.rs, core/src/job/manager.rs, core/src/job/mod.rs, core/src/job/worker.rs, core/src/location/indexer/indexer_job.rs, core/src/location/indexer/shallow.rs, core/src/object/file_identifier/file_identifier_job.rs, core/src/object/fs/copy.rs, core/src/object/fs/cut.rs, core/src/object/fs/delete.rs, core/src/object/fs/erase.rs, core/src/object/media/media_processor/job.rs, core/src/object/media/thumbnail/actor.rs, core/src/object/media/thumbnail/mod.rs, core/src/object/validation/validator_job.rs
This PR solves a race condition between the indexer job and the shallow indexer. When you're trying to index a big location and then open it up in the explorer, it dispatches a shallow indexer, that will find a bunch of directories in the location root directory and then as these directories are "brand new" according to the shallow indexer, it will dispatches a bunch of new scan locations with sub_path actions, with a bunch of new indexer jobs. 
I introduced a way to query the job manager to see if there are running jobs that matches a given predicate. With that I forbid quickRescan rspc route to run while there are running indexer and file identifier jobs running for a given location.
I tried to emit an error toast to the frontend warning the user, but failed hard. Can use some help from …
=> [ENG-1160] Opening a location while indexing causes a lot of jobs to be spawned

core/src/lib.rs, interface/ErrorFallback.tsx
Tried to make the logging configurable from settings but our tracing config is painful cause `tracing-appender`'s crates.io version is sooooo old.
=> Reduce production logs + button on error page for logs

interface/app/$libraryId/Explorer/index.tsx, interface/app/$libraryId/settings/client/keybindings.tsx, interface/util/keybinds.ts, packages/ui/src/keys.ts
The current shortcut isn't like Finder, ctrl + p on windows toggles it, but also triggers printing on windows.
**Now it's**:
MacOS: option, cmd, p
Windows: Alt, Ctrl, p
Tested both platforms.
=> [ENG-1274] Update explorer path bar shortcut + keybindings

interface/app/$libraryId/settings/library/tags/index.tsx
useEffect was triggering a re-render when updating the tag, therefore re-selecting the first tag. Dependancy is not needed for initial selection on page load. Tested and confirmed.
=> [ENG-1272] Tag color picker switches back to first tag when releasing the mouse

core/src/location/indexer/rules/mod.rs
Fix an optional db property being mistakenly required
Closes: #1093
=> [ENG-1268] Fix custom indexer rule crashing location scanning

packages/ui/src/Popover.tsx
This fixes the state toggle for popover keybinds. Now it works.
=> Popover keybind state fix

interface/app/$libraryId/Layout/Sidebar/Contents.tsx, interface/app/$libraryId/Layout/Sidebar/Footer.tsx, interface/hooks/useKeyDeleteFile.tsx, interface/hooks/useKeyMatcher.ts
**This PR focuses on the following**:
- Delete shortcut for Mac. **It is the Del key on windows.**
**Other notes**:
- Improved TS typing of the useKeyMatcher hook to use generics.
- Fixed icons of 2 shortcuts in sidebar.
- useKeyMatchers to get multiple values back instead of one.
**Tested on Windows & Mac**
=> [ENG-1294] Mac - Delete shortcut

core/src/api/files.rs, core/src/location/indexer/shallow.rs, core/src/location/manager/watcher/utils.rs, core/src/location/mod.rs, core/src/object/file_identifier/shallow.rs, core/src/object/media/media_processor/shallow.rs
In most cases we invalidate search.paths and not search.objects, this change makes sure both are always invalided. Our invalidation system is terrible, but that's another PR.
=> [END-1309] Fix explorer query invalidation

Cargo.lock, apps/desktop/src-tauri/Cargo.toml, apps/desktop/src-tauri/src/main.rs, apps/desktop/src-tauri/src/menu.rs, apps/desktop/src/commands.ts, interface/app/$libraryId/Layout/Sidebar/DebugPopover.tsx, interface/util/Platform.tsx
This button adds a "Reload webview" button to the debug popover, which can be used on any platform - beforehand, only MacOS was supported and the action for that was controlled by the menu bar (which is also only usable on MacOS).
This needs:
I followed the Tauri example on how to access/handle the webview for each appropriate platform, and from there used the respective crates and versions required by Tauri to (hopefully) make this feature cross-platform.
Video showing it working on Windows (thank you @ameer2468!) - please excuse the terrible quality and visual artifacts, `kdenlive` wasn't playing nicely:
https://github.com/spacedriveapp/spacedrive/assets/77554505/3cdf05c4-34f2-441c-9bad-6b9b75bbc8ca
=> [ENG-1289] Reload webview support for Windows and Linux

apps/mobile/modules/sd-core/android/build.gradle
This PR updates the Android `build.gradle` file for the `sd-core` module to have the final compiled rust library be linked to the application, which allows it to now call the library. 
Closes #1616
=> Get mobile app to build on Android

.github/actions/setup-rust/action.yaml, .github/workflows/cache-factory.yaml
Runs the cache factory more often so that we have more up-to-date caches. Should improve some CI speed and hopefully improve release workflow speed.
=> [ENG-1314] Re-enable cache factory on all main commits

interface/components/LoginButton.tsx
The letter 'i' is capitalized for "Logging In", but not capitalized for "Log in". This PR makes both of them lower case.
Closes #1618
=> Fix casing switch in "Log in" button

core/src/job/error.rs, core/src/job/mod.rs, core/src/job/worker.rs
Now each job must keep sending progress reports, otherwise the worker will assume it got stuck and terminate it with a timeout error after 5 minutes without progress.
Also made a full overhaul removing the `tokio::select!` macro and using `stream::merge` from futures concurrency in the entire job system. Helped me a lot to solve some race conditions with the timeout feature. 
Will need some fixes in the job manager in the frontend to support failed jobs.
=> [ENG-1308] Jobs shouldn't get stuck forever

core/src/object/fs/copy.rs, core/src/object/fs/mod.rs
Introduced a check for directory duplicate at FileCopierJob, before it was just duplicating each file in the same directory due to this missing check.
=> [ENG-1224] Duplicate folder duplicates files inside

interface/app/$libraryId/Explorer/TopBarOptions.tsx, interface/app/$libraryId/Explorer/View/index.tsx, interface/app/$libraryId/Explorer/useExplorer.ts, interface/app/$libraryId/TopBar/TopBarOptions.tsx, interface/app/$libraryId/ephemeral.tsx, interface/app/$libraryId/network.tsx, interface/app/$libraryId/node/$id.tsx
This PR introduces a new `useExplorer` prop called `layouts`, with which we can control, which layouts should be used per explorer.
Hides media view from the network, ephemeral, and nodes explorer.
Closes #1174
=> [ENG-955] Hide media view on network, ephemeral, and nodes explorer

.cargo/config.toml.mustache, Cargo.lock, Cargo.toml, apps/desktop/src-tauri/Cargo.toml, apps/mobile/modules/sd-core/core/Cargo.toml, core/Cargo.toml
Instruct openssl crates to always use [openssl-src-rs](https://github.com/alexcrichton/openssl-src-rs) to vendor the libssl.3 and statically link against it. This avoids the libssl.1.1 vs libssl.3.0 linking problems in the deb release.
Partial fix for #1512
=> [ENG-1325]  Vendor openssl in tauri

core/src/node/config.rs, crates/p2p/src/manager.rs
The `#[serde(default)]` on `is_enabled` will be `false` cause it's `bool::default` not `Self::default`  🤦
=> [ENG-1332] Fix regression causing P2P to be disabled by default

apps/desktop/src-tauri/tauri.conf.json
Makes Task Manager report the name as Spacedrive rather than 'The universal file manager'
=> Set shortDescription to Spacedrive

core/src/location/indexer/indexer_job.rs, interface/app/$libraryId/Layout/Sidebar/JobManager/JobContainer.tsx
— use tabular-nums on job text its tooltips to reduce jumpiness
- also swap Scanning: and Found: text 
https://github.com/spacedriveapp/spacedrive/assets/65303441/9c6223a6-c8c3-413b-99b9-8e568bfb210c
Closes #1646
=> Job text tabular-nums to reduce jumpiness

interface/app/$libraryId/PageLayout/index.tsx, interface/app/$libraryId/settings/client/SpacedriveAccount.tsx
Stops the account card from shrinking + removes `h-screen` from `PageLayout` since 1) that's just a bad idea and 2) scrollbar hides when there's nothing to scroll
=> Fix account card shrink + overview scrollbar

interface/app/$libraryId/Layout/index.tsx
When going fullscreen on MacOS on an external monitor, the app just goes blank. It only happens when the explorer is visible, not during onboarding or settings. Also doesn't happen if you go fullscreen on the native macbook display and move it over to the external display - it only happens when you fullscreen on an external display with the explorer visible.
I noticed the colour grey shown was not the same as the MacOS bar that displays, and inspect element was not being covered so that ruled out any native Swift/MacOS trickery. When looking at the grey, I noticed it was the same grey used for the corners/border of the app, as that was a bug I had to fix while fixing the fullscreen issue. Conditionally disabling the `frame` class and borders entirely fixes this very odd bug.
=> major fix: hide frame and border if macos is fullscreen

scripts/setup.sh
While I've configured `spacedrive` from sources on Arch Linux, I got message like bellow, even I had both `rustc` and `cargo`:
```
$ ./scripts/setup.sh 
Spacedrive Development Environment Setup
To set up your machine for Spacedrive development, this script will install some required dependencies with your system package manager
Press Enter to continue
Rust was not found. Ensure the 'rustc' and 'cargo' binaries are in your $PATH. https://rustup.rs
Rust was not found. Ensure the 'rustc' and 'cargo' binaries are in your $PATH. https://rustup.rs
Rust was not found. Ensure the 'rustc' and 'cargo' binaries are in your $PATH. https://rustup.rs
```
But when I checked in the code, command checks additionally `rustup` package:
```
if ! has rustup rustc cargo; then
```
So, because on Arch Linux …
=> Improve error message with rustup not found

interface/app/$libraryId/Explorer/ContextMenu/FilePath/Items.tsx, interface/app/$libraryId/Explorer/FilePath/DeleteDialog.tsx, interface/app/$libraryId/Explorer/QuickPreview/index.tsx, interface/hooks/useKeyDeleteFile.tsx
*Prefix: I'm really new to the project but wanted to try to tackle an issue, I'm not familiar with the Codebase, so if this is totally wrong or there is need to change something please let me know. I would really appreciate it if someone would take the time to give some feedback on this.*
Currently, the delete dialog always says that you are deleting a file, even if it is a directory or a mix of items.
To fix this:
The DeleteDialog now accepts two props, which specify the type of files to be deleted.
Based on this information, the wording is adjusted.
Closes #1384
=> [ENG-870] Fix wording for delete dialog

interface/components/AuthRequiredOverlay.tsx
When logging in the first time, sometimes loading can take longer than anticipated. A loading spinner should show, so I added the check for that.
- A simple check for 'loggingIn' improves the user experience and makes it more satisfying.
- Logging out is instant, so no need to include the check for that.
=> [ENG-1362] Logging in loading state improvement

scripts/setup.sh
The libvips package is a system dependency that is not installed by default on Arch-based systems like EndeavourOS. This PR adds the package installation to the setup script for pacman.
Closes #1687
=> Add installation of libvips for arch systems to setup script

Cargo.lock, apps/server/Cargo.toml
This removes the unnecessary `ctrlc` and `tower-http` dependencies from sd-server, which speeds up build times. 
Closes #1693
=> Remove unused dependencies from server

apps/landing/src/app/Downloads.tsx, apps/landing/src/app/HomeCTA.tsx
This is specific to the download links.
https://github.com/spacedriveapp/spacedrive/assets/21004798/70dff798-ceeb-4826-8386-296b6add524a
=> [ENG-1341] Landing download links shouldn't open new page

Cargo.lock, core/src/job/report.rs, interface/hooks/useIsLocationIndexing.ts, interface/hooks/useRedirectToNewLocation.ts, packages/client/src/core.ts
Typescript resolves `any | null` to `any` which means we aren't prompted for null checks leading to bugs.
In a future update, Specta will be modified to fix this but for now, this will work and prevent bugs!
=> [ENG-1367] TypeError: null is not an object

interface/ErrorFallback.tsx, interface/index.tsx
A rendering error would potentially allow the user to get stuck on the error boundary as the "Reload" button would render the same page, hit the same error and rerender the same error boundary. Now we detect if the error boundary is hit after the reload and if that's the case we redirect to "/" to break the cycle.
Before:
https://github.com/spacedriveapp/spacedrive/assets/21004798/2f5115b7-9262-4f3e-bcbb-32ef11133838
After:
https://github.com/spacedriveapp/spacedrive/assets/21004798/71818303-7e6c-41d9-918b-8e34a66ec0a8
=> [ENG-1366] Improve ErrorBoundary so user can't get stuck on it

apps/desktop/crates/macos/src-swift/window.swift, apps/desktop/crates/macos/src/lib.rs, apps/desktop/src-tauri/src/main.rs, interface/app/$libraryId/Layout/Sidebar/index.tsx
This fixes the padding, animation duration and traffic light positioning in regards to the window being fullscreen/non-fullscreen. It turns out our positioning "method" was also the cause of our original issue - we render an invisible menu bar to pad the traffic lights, but the issue is that this menu bar remained in place even after the app was made fullscreen (via the green traffic light). More info can be found in #1582.
The traffic light placement was something I entirely overlooked as I was too busy focused on fixing the bar, borders and then padding to notice they had inadvertently been misaligned - the cause of the issue was also the reason for their alignment, but luckily the challenges that arose from that PR alone caused this one to be quite a simple fix.
There _is_ some minor …
=> fix: traffic light placement when non-fullscreen

Cargo.lock, apps/desktop/crates/macos/Cargo.toml, apps/desktop/src-tauri/Cargo.toml, core/Cargo.toml, core/crates/sync/Cargo.toml, crates/file-ext/Cargo.toml, crates/p2p/Cargo.toml, crates/sync-generator/Cargo.toml, crates/sync/Cargo.toml
This removes the unnecessary `rmp-serde` and `arc-swap` dependencies from `p2p`, as well as the `window-shadows` dependency from `src-tauri` which speeds up build times.
Closes #1725
=> Remove unused dependencies in src-tauri and p2p

core/src/api/nodes.rs, core/src/node/config.rs, interface/app/$libraryId/settings/client/general.tsx
If we pass it to mdns-sd and it's too long we will get a panic :(
The length is dictated by the DNS spec so nothing we have control over.
=> [ENG-1344] Limit node name length

Cargo.lock, Cargo.toml, apps/cli/Cargo.toml, apps/desktop/crates/windows/Cargo.toml, apps/desktop/src-tauri/Cargo.toml, apps/mobile/modules/sd-core/core/Cargo.toml, core/Cargo.toml, crates/deps-generator/Cargo.toml, crates/ffmpeg/Cargo.toml, crates/file-ext/Cargo.toml, crates/images/Cargo.toml, crates/media-metadata/Cargo.toml, crates/p2p/Cargo.toml, crates/p2p/src/discovery/mdns.rs, crates/p2p/src/manager.rs, crates/p2p/src/spacetime/connection.rs, crates/sync-generator/Cargo.toml, crates/sync/Cargo.toml
Upgrade all Rust dependencies.
New features:
- IPv6 support for mDNS
- Fix some Rustsec issues
=> [ENG-1399] Upgrade Rust workspace + IPv6 mDNS

crates/p2p/src/spacetime/connection.rs
This removes `#[allow(deprecated)]`, and replaces `ConnectionHandler::Error` with `StreamUpgradeError<io::Error>`.
Closes #1732
=> Replace deprecated ConnectionHandler::Error

apps/landing/src/app/docs/Sidebar/Search.tsx, apps/landing/src/app/docs/layout.tsx
Something was wrong with style caching so the search bar was white on the first-load interestingly, this pr fixes that issue
=> Fix search bar

apps/desktop/src-tauri/src/tauri_plugins.rs, core/src/lib.rs, core/src/location/file_path_helper/mod.rs, core/src/location/indexer/mod.rs, core/src/location/indexer/walk.rs, core/src/location/manager/watcher/utils.rs, core/src/object/file_identifier/file_identifier_job.rs, core/src/object/file_identifier/shallow.rs, core/src/object/media/media_processor/shallow.rs, core/src/object/media/mod.rs
This PR introduces some changes trying to preserve an object from being unlinked on file_path updates. Also some watcher fixes and improvements.
=> [ENG-1360] Not always unlink objects from file_paths on update

Cargo.lock, Cargo.toml
Today's Tokio release include this fix (https://github.com/tokio-rs/tokio/issues/6133), which can potentially explain some mysterious jobs hanging that some users reported to us at the first alpha launch.
=> Update tokio's version

Cargo.lock, crates/images/Cargo.toml, crates/images/src/pdf.rs
This reverts the changes made in PR #1460. It ended up being an unnecessary set of changes that did not fix the underlying issue and made PDF thumbnail performance way worse. The correct fix for the mentioned issue was implemented in https://github.com/bblanchon/pdfium-binaries/pull/138. Also updated `pdfium-render`.
=> [ENG-1359] Revert "Fix pdf thumb crashing app (#1460)"

core/src/object/file_identifier/mod.rs
- Clarifies error that occurs when attempting to read the metadata from an on-demand file
- Involves issue #1721 but does not solve it
Current Error:
```
2023-11-01T19:29:02.533749Z ERROR sd_core::object::file_identifier: Failed to extract file metadata: FileIOError {
path: "C:\\Users\\xxxxx\\OneDrive\\Document.docx",
source: Os {
code: 362,
kind: Uncategorized,
message: "The cloud file provider is not running.",
},
maybe_context: None,
}
```
New Error:
```
2023-11-01T15:58:27.994181Z ERROR sd_core::object::file_identifier: Failed to extract metadata from on-demand file: FileIOError {
path: "C:\\Users\\xxxxx\\OneDrive\\Document.docx",
source: Os {
code: 362,
kind: Uncategorized,
message: "The cloud file provider is not running.",
},
maybe_context: None,
}
```
=> Clarify error that occurs when getting the hash of an on-demand file

apps/desktop/src-tauri/src/main.rs, crates/crypto/src/lib.rs
Fixes Clippy Warnings:
>warning: this could be a `const fn`
- Fixed by adding `#![allow(clippy::missing_const_for_fn)]` to `crates/crypto/src/lib.rs`
>warning: unused variable: `state`
- Fixed by adding an underscore before `state` in `apps\desktop\src-tauri\src\main.rs`
>warning: unused `std::result::Result` that must be used
- Fixed by handling the result using `.expect("Unable to reload webview");`
Closes #1775
=> Fix Clippy Warnings

interface/app/$libraryId/Explorer/Search/AppliedFilters.tsx, interface/app/$libraryId/Explorer/Search/Context.tsx, interface/app/$libraryId/Explorer/Search/index.tsx, interface/app/$libraryId/Explorer/Search/store.tsx, interface/app/$libraryId/Explorer/Search/util.tsx, interface/app/$libraryId/Layout/Sidebar/Contents.tsx, interface/app/$libraryId/Layout/index.tsx, interface/app/$libraryId/TopBar/SearchBar.tsx, interface/app/$libraryId/TopBar/index.tsx, interface/app/$libraryId/index.tsx, interface/app/$libraryId/settings/node/libraries/CreateDialog.tsx, interface/app/onboarding/Layout.tsx, interface/app/onboarding/context.tsx, interface/app/route-schemas.ts, interface/hooks/useKeybindEventHandler.ts, interface/hooks/useShortcut.ts, interface/hooks/useZodSearchParams.ts, pnpm-lock.yaml
Stores search state (query + filters) in search params so they persist across tabs.
`isSearching` has been replaced with a check for if a `search=` search param exists.
TODO:
=> [ENG-1436] Store search state in search params

.github/actions/setup-rust/action.yaml, CONTRIBUTING.md, core/Cargo.toml, core/src/api/search/object.rs, core/src/api/search/saved.rs, rust-toolchain.toml, scripts/setup.sh
This PR pins rust to 1.73 to avoid an internal compiler error present in version 1.74 due to https://github.com/rust-lang/rust/issues/117976
=> Pin rust to 1.73 (Workaround Internal Compiler Error)

core/src/object/media/thumbnail/actor.rs
This PR introduce a check to skip batches with size 0 erroneously sent to be processed
=> Thumbnailer channel with capacity 0 bug

interface/app/$libraryId/settings/node/libraries/DeleteDialog.tsx, interface/app/onboarding/new-library.tsx
This just navigates the user to `/` once a library has been deleted - this will either display onboarding if there are no other libraries available, or display an alternate library. Currently the app goes blank until the webview has been reloaded.
=> fix: app going blank when the last library is deleted

apps/landing/src/app/api/slack/webhook/createRelease.ts
Sends the release created message in the channel that `/release` was invoked from, rather than as an ephemeral reply.
=> Send release message in channel

apps/server/docker/Dockerfile, apps/web/src/App.tsx
- ~Replace `useOperatingSystem` from `App.tsx` to directly using the 'browser' value, as we can't access `usePlatform` yet and the frontend crashes due to it.~ (Already fixed on main)
- Remove `libav*` deps from server docker, they are not needed anymore
- Replace debian with distroless for the runtime base image in server docker
- Add missing `SpacedriveInterfaceRoot` in `web/App.tsx`
=> Small improvements to sd-server

apps/landing/src/app/Downloads/Platform.tsx
=> Fix landing icon sizes

interface/app/$libraryId/Explorer/FilePath/Thumb.tsx, interface/app/$libraryId/Explorer/Inspector/index.tsx, interface/app/$libraryId/Explorer/QuickPreview/index.tsx, interface/app/$libraryId/Explorer/View/GridList.tsx, interface/app/$libraryId/Explorer/util.ts
`FileThumb` uses a lot of `useEffects` for synchronising state which can be replaced with some `useMemo` and some better types.
This fixes some instances of thumbnail flicker when resizing and scrolling.
=> Reorganise file thumb renderer to use more memos

apps/landing/src/app/NavBar/MobileDropdown.tsx, packages/ui/src/Dropdown.tsx
I fixed this click range as well as the centered style
Closes #1868
=> fix(landing):Fixed the style of the mobile navigation bar menu bar

apps/desktop/src/App.tsx
Forgot to include this change which ignores history events produced by suspense and form events
=> Only handle idle history events

interface/app/$libraryId/Explorer/View/ViewItem.tsx, interface/app/$libraryId/Search/AppliedFilters.tsx, interface/app/$libraryId/Search/SearchBar.tsx, interface/app/$libraryId/Search/index.tsx, interface/app/$libraryId/Search/useSearch.ts, interface/app/$libraryId/location/$id.tsx, interface/app/$libraryId/tag/$id.tsx
A couple of things are happening here: Search and filters are being stored in search params so they save across navigations, and the entire state of the location explorer is being reset when navigating to a different folder by keying it on `path`.
=> [ENG-1503] Close search bar when navigating into folder

pnpm-lock.yaml, scripts/package.json
Sometimes `pnpm prep` fails on Linux due to a bug in [`archive-wasm`](https://github.com/spacedriveapp/archive-wasm). This PR update it to the latest version, which contains a fix for this issue.
=> Fix `pnpm prep` on Linux

crates/p2p/src/spacetime/stream.rs
This PR adds timeouts to several `.await`s in `crates/p2p/src/spacetime/stream.rs` that had `TODO: timeout` comments.
Closes #1906
=> Add missing timeouts

Cargo.lock, apps/desktop/src-tauri/Cargo.toml, apps/desktop/src-tauri/src/main.rs, apps/desktop/src-tauri/src/tauri_plugins.rs, apps/desktop/src/platform.ts
Given the explorer only slows down on media-heavy locations, and the MOV tags always render my theory is that we are hitting the HTTP connection limit for the image files. This PRworkarounds that by setting up many servers and randomly load balancing between them.
I don't know how much of a difference this will make but given it's so little code it's probs worth just shipping.
~~The code will need a bit of work before I would be comfortable merging it but this should be good for testing if this actually makes a difference.~~
=> Multiple HTTP servers

interface/RoutingContext.tsx, interface/hooks/useZodRouteParams.ts, interface/index.tsx
Previously `useZodRouteParams` used `useParams`. This means anytime any URL parameter changes it will cause the component to rerender, regardless of if those params were used within the Zod schema.
We pull the library ID from the URL using this hook and you can see a lot of unnecessary component re-renders due to the "inefficiency" of this hook.
This improved implementation is setup to only rerender if the params change *and* the result of the Zod schema changes.
This is done through what is basically a reimplementation of `useParams`.
**I think in practice this change won't make a major difference** but at least it reduces extra work for very little code changes.
=> Improve `useZodRouteParams`

.gitignore, apps/landing/src/app/Footer.tsx, apps/landing/src/components/Footer.tsx, apps/mobile/src/components/browse/BrowseLocations.tsx, apps/mobile/src/components/browse/BrowseTags.tsx, apps/mobile/src/components/browse/Categories.tsx, apps/mobile/src/components/browse/Jobs.tsx, interface/app/demo.solid.tsx, interface/app/index.tsx, interface/package.json, packages/client/src/hooks/useFeatureFlag.tsx, packages/config/base.tsconfig.json, packages/config/eslint/base.js, packages/config/eslint/react.js, packages/config/eslint/solid.js, packages/config/package.json, packages/config/vite/index.ts, packages/config/vite/narrowSolidPlugin.ts, packages/config/vite/relativeAliasResolver.ts, pnpm-lock.yaml
This PR configures Vite to allow React and SolidJS JSX transforms within a single package.
This is done through the use of the `.solid.tsx` file extension to dictate a file should be treated as SolidJS.
This PR also configures ESLint to detect common SolidJS problems such as destructuring. This should help us prevent bugs making it through, especially during the migration when we will be context switching between frameworks a lot.
HMR works on all files bar the entrypoint which is exactly the same behaviour as React, although will likely be a bit annoying during the migration.
=> SolidJS Build Infrastructure

interface/app/$libraryId/Explorer/FilePath/LayeredFileIcon.tsx
Layered file icons are now lazy loaded, so a suspense around them is needed to avoid app-wide suspends
=> Add suspense to LayeredFileIcon

apps/desktop/src-tauri/tauri.conf.json
**This change should hide title here**:
This config value only applies to MacOS. Issue can be seen in the image below.
=> [ENG-1532] Hide window title on macos

apps/mobile/src/components/browse/BrowseLocations.tsx, apps/mobile/src/components/header/Header.tsx, apps/mobile/src/components/inputs/Search.tsx, apps/mobile/src/components/layout/Fade.tsx, apps/mobile/src/navigation/tabs/BrowseStack.tsx, apps/mobile/src/screens/Locations.tsx, apps/mobile/src/stores/searchStore.ts
- Locations screen added.
- Fade component improved and adjusted to accomodate more options and needs.
- A temporary search system that uses it's own store just to make the design work, i'll architect something in the future when all screens are done. **This is to share state between the search component and all screens.**
- Header component now has a navBack prop to navigate back to the previous page. **I can extract this value as an arguement from the `header: () =>` but there is no need to do that.**
- A inputs directory with a Search component.
**Future improvements**:
- Organize screen directories with their child screens, e.g. Browse -> Locations screen, and also Browse -> Location.
- A proper search system when designs are implemented.
- Code cleanup …
=> [MOB-50] Locations screen

apps/desktop/package.json, apps/desktop/src/platform.ts, pnpm-lock.yaml
Change the URL getter to use consistent hashing.
This means the request for a resource will always be routed to the same backend webserver.
We use multiple webserves to ensure we aren't hitting HTTP connection limits when loading all the images in the explorer.
=> Fix QuickPreview video playback

interface/app/$libraryId/Explorer/FilePath/Original.tsx, interface/app/$libraryId/Explorer/FilePath/Thumb.tsx, interface/app/$libraryId/Explorer/QuickPreview/ImageSlider.tsx
**Quick preview fixes:  here are the following issues that have been addressed**:
- When you switched videos using the slider, videos wouldnt't play. So, a key value has been set to make sure React recognizes that a component update has happened therefore a re-render needs to happen so the newly selected video plays.
- Video controls only show when videos current time is > 0 - when you switched between videos the video controls would span the entire width of quick preview before the video even loaded, making the UI look strange.
- Tooltip fixed, if a name is a singe word that is long, it would overflow.
=> [ENG-1536] Quick preview fixes: Tooltip, video switching, and media controls flash

apps/desktop/src-tauri/src/main.rs
=> [ENG-1535] Fix MacOS window title showing

core/src/job/report.rs
This field `is_background` is unused and deprecated. Removing it would simplify `JobReport` (an already large struct) and improve readability.
Closes #1937
=> Remove deprecated is_background from JobReport

CONTRIBUTING.md
Closes #1781 
The `CONTRIBUTING.md` now lists build dependencies according to their respective OS systems. This extends support to similar systems where the setup scripts:
- `./scripts/setup.sh`
- `./scripts/setup.ps1`
are not supported and makes traversing through the build dependencies more accessible.
Additionally for detailed reference to the setup scripts, if the user wishes to directly see what build dependencies are, they have been referenced (links) in the updated changes.
The changes also reference links to the official Tauri setup docs as most of the build dependencies involve them.
=> Listed build dependencies according to setup scripts in CONTRIBUTING.md

core/src/api/backups.rs
There are two instances in `core/src/api/backups.rs` where `String` is used as a path type, when `PathBuf` could be used instead. This PR makes the replacement.
Closes #1959
=> Use PathBuf instead of String for paths

Cargo.lock, crates/p2p/Cargo.toml, crates/p2p/src/spacetunnel/identity.rs
`Identity` should be zeroized when no longer in use. This PR adds a `derive(ZeroizeOnDrop)` to `Identity`.
Closes #1961
=> Add missing zeroize to Identity

Cargo.lock, Cargo.toml
- Fix rolling release distros that are already using OpenSSL > 3.0
=> Update prisma-client-rust to fix compiling from source on Linux

core/src/api/cloud.rs
This moves the AWS S3 client into a `OnceCell` so that it is only initialized once, then reused.
I wasn't able to test this (because I don't have access to the team's AWS instance), so someone on the team will need to test before merging.
Closes #1966
=> Optimization: reuse AWS S3 client across procedure calls

interface/app/$libraryId/TopBar/NavigationButtons.tsx
Due to recent changes - this is no longer needed.
=> Windows: Remove os check for mouse nav

Cargo.lock, apps/desktop/src-tauri/Cargo.toml, core/Cargo.toml, interface/package.json, pnpm-lock.yaml
On launch (at least on MacOS), the app will produce an error regarding Solid, Vite and `solid-refresh`. Navigating to `interface`, and running `pnpm i solid-refresh` fixes the issue.
I have tested this on a fresh clone, and it had the error, but this resolves the issue.
=> Fix app from not starting due to missing `solid-refresh` and bump version to `0.2.0`

apps/server/Cargo.toml, interface/app/$libraryId/Explorer/View/GridView/Item/index.tsx, interface/app/$libraryId/Explorer/View/ListView/useTable.tsx
not implemented nicely but it'll do
=> [ENG-1529] Round thumbnails for labels

interface/app/$libraryId/Explorer/FilePath/RenameTextBox.tsx, interface/app/$libraryId/Explorer/View/Grid/index.tsx, interface/app/$libraryId/Explorer/View/index.tsx, packages/ui/src/Dialog.tsx
This PR prevents explorer interaction when a dialog is open, this addresses the issue of not being able to press 'Enter' on your keyboard when focus is active on a button.
=> [ENG-1564] Delete dialog keypress 

interface/app/$libraryId/Explorer/View/ViewItem.tsx
atm double clicking a label will open all files which belong to that label, not great behaviour
=> only navigate on label double click

core/src/cloud/sync/receive.rs, core/src/library/manager/mod.rs
Uses the in-memory instance list when receiving cloud operations, rather than doing a db query each time.
Also adds to the instance list when a new instance is detected.
=> use in memory instances during cloud receive

apps/desktop/src-tauri/tauri.conf.json
This config option seems to be crashing the installer for a lot of Windows users, and I am not 100% why I enabled anyway, so revert it.
__Rationale__:
According to this log, from an affected user:
https://github.com/spacedriveapp/spacedrive/issues/1994#issuecomment-1909596918
The problem steams from the `CreateUpdateTask` action present in tauri's Wix template:
https://github.com/tauri-apps/tauri/blob/tauri-v1.5.3/tooling/bundler/src/bundle/windows/templates/main.wxs#L282-L307
Which tries to execute this Powershell script:
https://github.com/tauri-apps/tauri/blob/tauri-v1.5.3/tooling/bundler/src/bundle/windows/templates/install-task.ps1
That fails for a lot of our users for some reason.
However, this is a non-default behavior that I enabled in the AI PR for some reason (maybe by mistake): …
=> Remove `enableElevatedUpdateTask` from Wix installer config

apps/desktop/src-tauri/src/main.rs, apps/mobile/modules/sd-core/core/src/lib.rs, apps/server/src/main.rs, core/src/lib.rs, core/src/util/clear_localstorage.rs, core/src/util/mod.rs
This will 1) reset the onboarding progress on each app load, so that prior information isn't retained and 2) reduce the amount of app crashes/blank pages that happen due to invalid `localStorage` configurations.
For web, I think this will have to be handled in the TS side of things, but for desktop we can do this. I'm not sure if the TS approach will be suitable for desktop also, we can probably do some testing in due course (this works great though).
I've tested this on Linux so far and it works, and I don't see why the other platforms wouldn't work either, but I will be testing shortly just to validate.
=> [ENG-1540] Remove `localStorage` if no libraries are created

Cargo.lock, interface/app/$libraryId/settings/library/locations/$id.tsx, packages/client/src/cache.tsx
=> Fix Location Settings (due to Normalised Cache bugs)

apps/mobile/src/components/browse/BrowseLocations.tsx, apps/mobile/src/components/browse/BrowseTags.tsx, apps/mobile/src/components/browse/Categories.tsx, apps/mobile/src/components/browse/Jobs.tsx, apps/mobile/src/components/explorer/Explorer.tsx, apps/mobile/src/components/header/Header.tsx, apps/mobile/src/components/settings/SettingsItem.tsx, apps/mobile/src/navigation/tabs/BrowseStack.tsx, apps/mobile/src/screens/Locations.tsx, apps/mobile/src/screens/browse/index.tsx, apps/mobile/src/stores/explorerStore.ts
**This pr does the following**:
- Header UI for location and tag screens.
- Explorer menu toggle.
- UI tweaks and adjustments for a better visual look **(More coming for android in a diff PR)**.
- Empty states for locations and tags.
**Images**:
=> [MOB-47] Location screen and header updates

core/src/cloud/sync/mod.rs, core/src/cloud/sync/send.rs
Reading from memory is much faster than scanning through db rows (which is done on app startup), we just need to ensure that the db and in-memory values are being updated together.
=> [ENG-1548] use in-memory instances when sending messages to cloud

apps/mobile/src/components/browse/BrowseTags.tsx, apps/mobile/src/components/browse/Categories.tsx, apps/mobile/src/components/browse/Jobs.tsx, apps/mobile/src/components/header/Header.tsx, apps/mobile/src/components/settings/SettingsItem.tsx, apps/mobile/src/navigation/TabNavigator.tsx, apps/mobile/src/navigation/tabs/BrowseStack.tsx, apps/mobile/src/screens/Locations.tsx, apps/mobile/src/screens/Tags.tsx, interface/app/$libraryId/overview/StatCard.tsx
- Fixed a focus tab nav bug when navigating between screens that are within the same stack.
- Improved the colors of cards and now the app looks way better.
- All tags screen has been added.
- Title of screens increased in size for a better visual look.
**Images**:
=> [MOB-53] All tags screen - visual improvements - and more

interface/hooks/useKeyMatcher.ts
Use real OS that way we don't have ctrl+x on the macOS web version, but instead, cmd+x. Also fixes some keybinds on web.
=> [ENG-1604] Change key matcher to use real OS

.github/workflows/release.yml
Fix base64 call in macOS release workflow
=> Fix macOS release workflow

interface/app/$libraryId/Explorer/View/Grid/Item.tsx, interface/app/$libraryId/TopBar/NavigationButtons.tsx
**This pr restores the previous fix for this issue**: when mouse is over a file/folder/object, you wouldn't be able to navigate backwards/forwards for Grid view specifically.
- As also, according to [mdn ](https://developer.mozilla.org/en-US/docs/Web/API/MouseEvent/button) I added buttons 3 and 4 for better support of nav forwards and backwards.
- Also blocked this from happening when running Spacedrive on browser, otherwise it would navigate twice.
=> [ENG-1612] Fix mouse nav forwards and backwards

.prettierignore, CONTRIBUTING.md, apps/mobile/modules/sd-core/android/build.gradle, apps/mobile/modules/sd-core/android/build.sh, scripts/setup.sh
When building for Android, many errors pop up when using Rust's cargo build with Gradle Daemons. Errors ranging from building but not uploading the latest `.so` file to JNI Merging issues. Therefore, I moved the build script away from `org.mozilla.rust-android-gradle:plugin:0.9.3` into a custom `.sh` build script like the iOS `build_rust.sh` script. 
The following changes are happening to `setup.sh` due to the introduction of `cargo ndk` into the build so that we can build for the android build targets. 
I've tested it on my android location-watcher testing branch, so please let me know if any issues occur on your own machine. However, from my testing, I have found this new script to be more consistent due to it working directly from the File System instead of through Gradle.
=> New Android Build Script

apps/mobile/src/components/modal/ImportModal.tsx, apps/mobile/src/components/modal/confirmModals/DeleteLocationModal.tsx, apps/mobile/src/components/modal/confirmModals/DeleteTagModal.tsx, apps/mobile/src/components/modal/location/LocationModal.tsx, apps/mobile/src/components/modal/tag/CreateTagModal.tsx, apps/mobile/src/screens/onboarding/GetStarted.tsx
**This PR**: invalidates queries for when you add/delete locations and tags in order to reflect UI updates immediately.
- Also confirmation modal when deleting a location.
=> [MOB-60] locations & tags query invalidation on updates

apps/mobile/src/components/browse/BrowseTags.tsx, apps/mobile/src/screens/Locations.tsx, apps/mobile/src/screens/Tags.tsx, apps/mobile/src/screens/onboarding/GetStarted.tsx, apps/mobile/src/screens/settings/library/TagsSettings.tsx
**This PR adds empty states for tags and locations screens**:
=> [MOB-59] Empty UI for locations and tags screen

core/src/p2p/sync/proto.rs
This resolves a TODO comment in `core/src/p2p/sync/proto.rs`:
```
// TODO: Using `decode::Error` instead of `io::Result`
```
Closes #2077
=> Improve error handling by using decode::Error instead of io::Result

.cargo/config.toml.mustache, .github/actions/setup-pnpm/action.yml, .github/actions/setup-rust/action.yaml, .github/actions/setup-system/action.yml, .github/workflows/cache-factory.yaml, .github/workflows/ci.yml, .github/workflows/mobile-ci.yml, .github/workflows/release.yml, .github/workflows/server.yml, .prettierignore, Cargo.toml, apps/mobile/modules/sd-core/ios/build-rust.sh, scripts/preprep.mjs
- Replace archived actions-rs/clippy-check with maintained fork actions-rs-plus/clippy-check
- Replace redhat-actions/push-to-registry with updated fork Eusebiotrigo/push-to-registry
- Point redhat-actions/buildah-build and softprops/action-gh-release to current master to fix Node.js deprecation
- Made some change to the iOS build_rust script and Mobile CI to build the app and lib for the same arch as the host machine when using iphone_simulator
- Made some changes to make cache-factory faster and avoid failing so much
- Add trigger to run cache-factory on pull requests when there are changes to itself
=> Update github actions due to nodejs 16 deprecation

core/crates/sync/src/backfill.rs, core/src/api/cloud.rs, core/src/api/libraries.rs, core/src/api/sync.rs, core/src/library/config.rs, core/src/library/manager/mod.rs, interface/app/$libraryId/debug/sync.tsx, packages/client/src/core.ts
Integrates the backfill system with the sync operation emitting toggle, so that existing libraries can go from no sync -> backfill + generation enabled with 1 button.
=> [ENG-1613] Enable sync operation generation with backfill

apps/desktop/src/updater.tsx
Not sure if this will fix the updater toast showing on first launch but it's certainly better logic than before
=> [ENG-1598] Don't show update toast if no previous version

interface/app/$libraryId/Explorer/Inspector/index.tsx
=> [ENG-1460] Fix inspector path overflow

.github/workflows/release.yml, .github/workflows/server.yml
- GitHub CI don't support shortened commit SHA
=> Fix Release and Server actions

packages/client/src/hooks/useClientContext.tsx
Makes the library list query happen alongside retrieving the cached value, if there is one
=> fetch library list alongside retrieving cache

interface/app/$libraryId/Explorer/FilePath/utils.ts
Black bars cause the image to resize, which triggers the resize watcher and causes a loop of constant resizing. The solution isn't the best but does the job.
Closes #2150
=> [ENG-1662] Fix thumb black bars

interface/app/style.scss
This shows the scrollbar of explorer on Windows. Should be safe as I have run tests.
Also shows on other pages, confirmed and compared the experience with MacOS to make sure they are the same.
=> [ENG-1661] Windows explorer scrollbar

core/crates/sync/src/backfill.rs
adds pagination to the sync backfill so that hundreds of thousands of records aren't loaded into memory at once.
test with the 'enable sync' button in the sync debug page after indexing a bunch of files.
=> paginate sync backfill

core/src/lib.rs
Forgot to remove `let level = 'debug'` from the code. Oops!
=> Revert Tracing-Subscriber filter level

apps/mobile/src/screens/settings/library/EditLocationSettings.tsx
Currently, `reidentify_objects` does not work on iOS or Android for fullRescan. So, this just keeps it false with a `FIXME` message until it's patched and fixed. 
Otherwise, it'll make it so users can't `fullRescan` locations on the mobile applications, and production doesn't show any errors when it fails.
=> Make `fullRescan` button work on mobile

crates/p2p-block/src/lib.rs
Resolves a TODO comment: `// TODO: Out of range protection on indexed access` by using `Vector.get()` and returning an `Error`, instead of directly indexing the vector and panicking.
Closes #2186
=> p2p-block: check for out-of-bounds indexing

interface/app/$libraryId/Explorer/View/Grid/DragSelect/index.tsx, interface/app/$libraryId/Layout/Sidebar/sections/Devices/index.tsx
**This PR**: Prevents drag selection with mouse-side buttons.
Emulates the behaviour of Finder & Windows Explorer.
=> [ENG-1683] Prevent mouse-side buttons from drag selection

.cspell/project_words.txt, apps/landing/src/app/roadmap/items.ts, apps/landing/src/app/roadmap/page.tsx, docs/product/getting-started/setup.mdx, docs/product/guides/interface.mdx
Made a lot of improvements to the roadmap
=> Roadmap updates

core/src/p2p/events.rs
Previously it required a node restart to work.
=> Fix node rename with P2P

interface/app/$libraryId/Explorer/View/DragScrollable.tsx, interface/app/$libraryId/Explorer/index.tsx, interface/app/$libraryId/PageLayout/index.tsx, interface/app/$libraryId/TopBar/Context.tsx, interface/app/$libraryId/TopBar/Layout.tsx, interface/app/$libraryId/TopBar/Portal.tsx, interface/app/$libraryId/TopBar/index.tsx, interface/app/$libraryId/ephemeral.tsx
a general rule of react hmr + fast refresh is to not export components in the safe file or you can get errors during hmr like this
source
https://github.com/ArnaudBarre/eslint-plugin-react-refresh
=> fix topbar hmr

core/src/api/cloud.rs, core/src/cloud/sync/receive.rs, core/src/library/manager/mod.rs
in pulling cloud library and instance information, timestamps should be upserted rather than overwritten to 0
=> upsert sync timestamp rather than overwrite

apps/mobile/modules/sd-core/core/src/lib.rs
So, `.unwrap()` can cause issues when the core dies by throwing a panic. So, by moving to a `match` instead, we can stop the panic from occurring and get a proper error in the console/logs.
=> Remove the `.unwrap()` from the mobile core

core/src/p2p/manager.rs
Resolves a TODO comment in `core/src/p2p/manager.rs`: 
```
// TODO: Make private
pub quic: QuicTransport,
```
Closes #2233
=> Make quic field of P2PManager private

interface/app/$libraryId/TopBar/index.tsx, interface/app/$libraryId/search/SearchBar.tsx
^
Keep in mind the search input is not rendered at all times **(Ephemeral locations)**. Hence the approach.
=> [ENG-1693] Prevent default webview search

core/crates/sync/src/ingest.rs, core/crates/sync/src/lib.rs, core/crates/sync/src/manager.rs, core/src/api/cloud.rs, core/src/api/sync.rs, core/src/cloud/mod.rs, core/src/cloud/sync/ingest.rs, core/src/cloud/sync/mod.rs, core/src/cloud/sync/receive.rs, core/src/cloud/sync/send.rs, core/src/library/library.rs, core/src/library/manager/mod.rs, interface/app/$libraryId/Layout/Sidebar/SidebarLayout/Footer.tsx, packages/client/src/core.ts
Adds a `sync.active` subscription that indicates whether sync send, receive, or ingest is currently active.
A sample UI is implemented in the sidebar footer but it we can put it wherever.
=> [ENG-1691] Sync status subscription

apps/landing/src/app/page.tsx
Change the hover tool tip text on the Landing Page for the image carousel from `Hover on the image above to see how the app works!` to `Hover to see more`.
=> Update Hover Text on Landing Page

apps/landing/src/app/roadmap/items.ts, docs/product/getting-started/setup.mdx
Currently, Spacedrive's Docker Server does not support authentication methods. So, adding a warning about it on the setup page.
=> Add Warning for SD Docker Container

interface/app/$libraryId/favorites.tsx, interface/app/$libraryId/labels.tsx, interface/app/$libraryId/location/$id.tsx, interface/app/$libraryId/recents.tsx, interface/app/$libraryId/saved-search/$id.tsx, interface/app/$libraryId/search/AppliedFilters.tsx, interface/app/$libraryId/search/Filters.tsx, interface/app/$libraryId/search/SearchBar.tsx, interface/app/$libraryId/search/SearchOptions.tsx, interface/app/$libraryId/search/index.tsx, interface/app/$libraryId/search/useSearch.ts, interface/app/$libraryId/settings/library/saved-searches/index.tsx, interface/app/$libraryId/tag/$id.tsx
Removes `fixedFilters` in favour of `defaultFilters`, which are only used when search is being focused. Will allow multiple filters of the same type to be added since there's no more merge logic.
=> remove fixed filters

.github/workflows/ci.yml
Avoid CI failing in main due to `dorny/paths-filter` step sometimes failing to read the merged PR branch by ignoring it and  running Clippy and Rust format anyways
=> Don't fail CI job if  `dorny/paths-filter` step fails

interface/app/$libraryId/Layout/CMDK/index.tsx, interface/app/$libraryId/TopBar/index.tsx, interface/hooks/useShortcut.ts
**This PR**: 
- Fixes using space in command palette
- Fix navToSettings shortcut/new tab. Both were being triggered due to similar keys.
- Also added a condition so that it does not open when quick preview is open, otherwise you can't close quick preview.
=> [ENG-1702] Fix space for command palette

interface/app/$libraryId/settings/library/locations/ListItem.tsx
**This PR**: sets a fixed width for location size for better visual consistency. 
**Also:**
- Removes `Size:` text - it should be obvious that it is the size. It's like putting **Status:** next to 'Connected'
- Added a tooltip when the size is truncated.
- Reorganized the layout.
=> [ENG-1704] Location fixed width sizing

Cargo.lock, apps/desktop/src-tauri/Cargo.toml, apps/desktop/src-tauri/src/main.rs
Jamie reported Spacedrive being broken on his laptop after us fixing desktop.
I have a feeling it's due to the original problem I hit which caused me to patch `tauri_plugin_window_state`.
Removing that patch is what fixed his desktop build so we are in a catch-22.
I think we should prefer our app opening then preserving window state.
I wanna confirm this fixes Jamie's laptop and if so I can probally throw together our own window state code.
=> Drop Tauri Plugin Window State

.prettierignore, apps/landing/src/app/page.tsx, apps/landing/src/app/roadmap/items.ts, apps/landing/src/components/mdx/Pre.tsx, apps/landing/src/components/mdx/index.tsx, apps/web/cypress/support/commands.ts, interface/app/$libraryId/Explorer/View/ListView/index.tsx, interface/app/$libraryId/Layout/Sidebar/store.ts, interface/components/TextViewer/index.tsx, interface/hooks/useShortcut.ts, scripts/utils/fetch.mjs
- Adjust fetch call to enable `autoSelectFamily` and `allowH2` so `pnpm prep` can function correctly on some specific network environments (Ex: corporate networks with proxies)
- ESLint/Prettier auto format
=> Fix pnpm prep fails to download native-deps on some specific network env

apps/mobile/scripts/run-maestro-tests.sh
Sometimes Mobile CI fails because a specific tests couldn't complete a specific step for some unknown reason. Add a single retry for failed tests to workaround this
=> Implement test retry for Mobile CI

.github/actions/setup-rust/action.yaml, core/prisma/schema.prisma
**For main and release tags:** Fail CI if changes to db schema are not reflected in a migration for prod builds
**For PRs:** Add an error msg to `schema.prisma` file if a migration was not created to reflect changes made to it, but do NOT fail CI
=> CI now checks if a migration is missing

.github/actions/setup-pnpm/action.yml, .github/actions/setup-rust/action.yaml, CONTRIBUTING.md, core/prisma/migrations/20240409210455_improve_job_errors/migration.sql
- Fix CI: Downgrade runner python to version 3.11 to fix `node-gyp` breaking due to changes in python 3.12
- Fix migration check not always failing when it should on main
- Fix check due to GitHub using `refs/heads/gh-readonly-queue/main/` as ref when merging a PR from merge-queue to main
- Fix missing migration error message being showed when it shouldn't
- Filter out empty migrations files when testing if a migration is missing
- ~Add migration due to changes made in #2161~
=> Fix CI (due to python 3.12 update) + Fix migration CI check

interface/app/$libraryId/search/useSearchExplorerQuery.ts
order settings weren't being passed through to queries
=> pass through query ordering options

docs/product/resources/faq.mdx
The old domain no longer redirects and is some sort of gross news placeholder site. See also #1852
=> Fix Tauri link

core/Cargo.toml, core/src/api/ephemeral_files.rs, core/src/api/files.rs
^ Because the trash crate is not made to work on mobile OSes.
=> Disable `trash` crate on mobile

core/crates/sync/src/backfill.rs, core/crates/sync/src/manager.rs
When backfilling sync operations, we need to pause generating timestamps until backfill is complete in order to ensure that backfill operations have a lower timestamp than newer operations that are queued to occur after generating timestamps. This PR implements that by locking sync timestamp generation behind a semaphore that's used both when writing realtime operations and backfilling.
=> [ENG-1740] Add sempahore for generating sync operation timestamps

.github/actions/setup-pnpm/action.yml, .github/workflows/ci.yml, CONTRIBUTING.md, apps/server/docker/Dockerfile, package.json
This fix the incompatibility with Python 3.12, which is getting worse due to distros and macOS (brew) updating it and breaking `pnpm i` with pnpm < 9.
=> Update pnpm to version 9

.github/actions/setup-pnpm/action.yml, CONTRIBUTING.md, apps/landing/src/app/Downloads/Platform.tsx, apps/landing/src/app/api/releases/desktop/[version]/[target]/[arch]/route.ts, package.json
AppImage doesn't work with Ubuntu < 22.04 based distros, Arch Linux etc.
Related: https://github.com/spacedriveapp/spacedrive/issues/2039
=> Replace Appimage with deb

interface/app/$libraryId/Explorer/View/index.tsx
Fixes a bug where if you select items on the grid view and switch to media view, then toggle quick preview and the selected items from the grid view are not available on the media view, quick preview won't open but if you switch back to grid view it will open on its own. This is more of a temporary solution until we make quick preview not rely on currently available items.
=> [ENG-1753] Only open quick preview when items are selected

core/src/api/search/mod.rs
We don't need to be adding relation filters if none are provided
=> Ignore empty object/filepath search filters

apps/desktop/src-tauri/src/main.rs, apps/server/src/main.rs, core/src/api/search/mod.rs, core/src/node/config.rs, core/src/p2p/manager.rs, core/src/p2p/operations/spacedrop.rs, crates/p2p-block/src/block_size.rs, crates/p2p-block/src/lib.rs, crates/p2p-block/src/sb_request.rs
Properly implement the block size calculation for `sd-p2p-block`.
This should make Spacedrop faster for bigger files.
=> Block size

core/crates/sync/src/ingest.rs, core/crates/sync/src/manager.rs, core/src/cloud/sync/ingest.rs, core/src/p2p/sync/mod.rs, crates/sync/src/compressed.rs
Sync operations belonging to the same record will now be ingested together, according to a few rules based on what is in the batch:
- A delete: All other messages will be ignored
- Create + >0 Update: Overwrites the create's data with the updates
- \>0 Update: Updates are applied at once using a fake Create op
This is helpful since in the case of Deletes it allows less work to be done, and in the case of Updates we can reuse some of the queries used in conflict resolution, reducing the amount of back and forth with the db.
=> Batch ingest sync operations

apps/desktop/src-tauri/src/main.rs, core/src/api/files.rs, core/src/api/p2p.rs, core/src/api/search/mod.rs, crates/crypto/src/keyring/linux/secret_service.rs, crates/p2p-block/src/block.rs, crates/p2p-block/src/sb_request.rs, crates/sync/src/compressed.rs, scripts/utils/fetch.mjs
- Increase `pnpm prep` connection timeout to 5min, to better handle downloading native deps under flaky network conditions
- Fix `cargo test` and cache-factory CI
- Clippy and fmt
=> Fix `cargo test`  & improve `pnpm prep` native deps download

apps/mobile/src/components/browse/BrowseLocations.tsx, apps/mobile/src/components/browse/BrowseTags.tsx, apps/mobile/src/components/header/DynamicHeader.tsx, apps/mobile/src/components/header/SearchHeader.tsx, apps/mobile/src/navigation/SearchStack.tsx, apps/mobile/src/navigation/tabs/BrowseStack.tsx, apps/mobile/src/navigation/tabs/NetworkStack.tsx, apps/mobile/src/navigation/tabs/OverviewStack.tsx, apps/mobile/src/navigation/tabs/SettingsStack.tsx
**This PR**: Provides and creates a few different headers to accomodate and fullfill different purposes.
- The styling has been duplicated on purpose to allow for design iterations as needed, instead of wrapping all different headers with the same style.
- Instead of manually setting "title" for different routes, now many screens simply use the `route` object for cleaner code, however in some cases like in SettingsStack, title can be provided manually since the names of the `route` themselves are not desired.
I think this is good for now - as it offers the level of flexibility we need to iterate the design of each header + support better understanding of our headers.
=> [MOB-89] Separate headers

.github/workflows/cache-factory.yaml, .github/workflows/ci.yml
Hey! 🙂
I want to contribute the following changes to your workflow:
- Avoid executing  scheduled workflows on forks
- Use names for run steps
- Define permissions for workflows with external actions
- Steps should only perform a single command
- Use commit hash instead of tags for action versions
These changes are part of a research Study at TU Delft looking at GitHub Action Smells. [Find out more](https://ceddy4395.github.io/research/gha-smells.html)
Closes #2411
=> Fix potential github action smells

core/src/api/search/mod.rs
PCR's `and` combines every param into one entry, rather than ANDing them individually. This works around it.
=> AND search params together properly

interface/app/$libraryId/Explorer/View/ViewItem.tsx
Specifies a location to navigate to when double clicking an explorer item, rather than just setting search params
=> Fix folder double click

.github/workflows/cache-factory.yaml, .github/workflows/ci.yml, apps/mobile/src/components/header/DynamicHeader.tsx, apps/mobile/src/components/header/Header.tsx, apps/mobile/src/components/header/SearchHeader.tsx, apps/mobile/src/components/layout/ScreenContainer.tsx, apps/mobile/src/navigation/tabs/BrowseStack.tsx, apps/mobile/src/navigation/tabs/NetworkStack.tsx, apps/mobile/src/navigation/tabs/OverviewStack.tsx, apps/mobile/src/navigation/tabs/SettingsStack.tsx, apps/mobile/src/screens/settings/Settings.tsx, core/src/api/files.rs, core/src/api/locations.rs, core/src/api/search/mod.rs, interface/app/$libraryId/Explorer/View/ViewItem.tsx, interface/app/$libraryId/debug/sync.tsx, packages/ui/src/Dialog.tsx
- Auto lint and format
- Revert some mistake made to CI in #2412 and revert locking actions versions to commits hashes
> While I agree with the intent of the mentioned PR (making Github CI actions less vulnerable to sudden changes), I am not sure hard-coding their commits SHAs is the best solution, especially considering the constant updates some of these actions receive to continue working properly under GitHub CI, which would require a non ideal amount of work from us to keep up to date if we had to keep updating commits hashes. I would like to revisit this whenever we have time to implement some sort of system that automatically manages dependencies version update such as renovatebot.com. Also the PR only changed a couple of CI actions to use commit hashes, and I think we should keep …
=> Auto format/lint and revert some changes made to CI

interface/app/$libraryId/search/SearchBar.tsx
**This PR**: when executing a search from overview page or pages that are not location related. The input loses focus.
With this change, the input will auto focus/remain focused when navigating to search.
=> [ENG-1769] keep input focused when search

Cargo.lock, Cargo.toml, apps/desktop/src-tauri/Cargo.toml, core/Cargo.toml
- ~Update BLAKE3 to 1.5.1~
- ~Remove~ Fix usage of BLAKE3 fork https://github.com/brxken128/blake3 as it is not available anymore. A backup was made here: https://github.com/spacedriveapp/blake3. ~However the changes included in the fork were not essential, so it was removed to allow updating to the last version of BLAKE3~. (The changes were required, revert back to using our backup repo)
- Auto format Cargo.toml's
=> Fix BLAKE3

apps/mobile/src/components/overview/CategoryItem.tsx, apps/mobile/src/hooks/useFiltersSearch.ts, apps/mobile/src/screens/overview/Categories.tsx, apps/mobile/src/screens/search/Search.tsx, apps/mobile/src/stores/searchStore.ts
**This PR**: Clicking on categories will now redirect to search.
- By default search page will now render all files - i found the UX to be alot more nicer this way. "I see all my files, let's filter for what I need".
- I moved input search values into the hook to centralize search + better code. 
- Handling global search if no locations selected.
=> [MOB-79] Categories search redirect

apps/mobile/src/components/explorer/menu/SortByMenu.tsx, apps/mobile/src/components/primitive/Menu.tsx
**This PR**: sort by text is un-necessary, will be clear to users, found this to be a common approach. Also a minimal animation for sorting menus.
=> Mob: remove sort by text

core/crates/heavy-lifting/src/file_identifier/tasks/extract_file_metadata.rs, core/src/api/locations.rs, core/src/api/search/mod.rs
Clippy warns about the size of these two variants being way too big compared to their siblings, so, as a potential performance improvement, it's better to `Box` them, which makes the enum lighter.
=> Box heavy data inside enum

core/src/api/p2p.rs, core/src/p2p/operations/spacedrop.rs, crates/p2p/src/lib.rs, crates/p2p/src/peer.rs
1. Creates an enum for Spacedrop errors called `SpacedropError`
2. Changes the return type of `spacedrop()` from `Result<Uuid, ()>` to `Result<Uuid, SpacedropError>`
3. Uses the error messages in `core/src/api/p2p.rs` instead of `"todo: error"`
Closes #2468
=> Create SpacedropError enum for spacedrop() errors

Cargo.lock, crates/p2p-tunnel/Cargo.toml, crates/p2p-tunnel/src/tunnel.rs
1. Creates the `TunnelError` enum
2. Modifies `Tunnel.responder()` and `Tunnel.initiator()` to return `Result<Self, TunnelError>` instead of `Result<Self, &'static str>`
Closes #2478
=> Improve Tunnel error handling

core/src/p2p/manager.rs, crates/p2p/src/quic/transport.rs
1. Creates the `QuicTransportError` enum
2. Changes the return types of `QuicTransport.spawn()`, `QuicTransport.set_ipv4_enabled()`, `QuicTransport.set_ipv6_enabled()`, and `QuicTransport.setup_listener()` to use `QuicTransportError` instead of `String` as the error variant of their `Result`. 
Closes #2481
=> p2p: improve error handling for QuicTransport

.github/actions/setup-rust/action.yaml, Cargo.toml
Config the dev profile for faster debug builds. That's a simple change, but I found it to be quite good for dev workflow.
A clean `pnpm tauri dev` went from 5m to 3m20s (better, but I'm certain we can improve), and it's even better when during small iterations of changes-and-check, or change-and-test (when the incremental changes start doing its thing).
The downside of these changes is that we lose the debug symbols (**only in debug builds, this does not affect release builds**)
=> Faster debug builds

.npmrc, apps/desktop/src-tauri/Cargo.toml, apps/mobile/src/components/overview/StatCard.tsx, interface/app/$libraryId/Explorer/Inspector/index.tsx, interface/app/$libraryId/overview/StatCard.tsx, package.json, packages/client/src/lib/humanizeSize.ts, packages/client/src/utils/index.ts
- Fix humanizeSize returning value as original (which was simply plain wrong), replace it with the original bytes
- Restore plural to humanizeSize, but only when converting object to string
- Fix float number to BigInt conversion in humanizeSize possibly causing an error (now it truncates the value)
- Remove unused profile.release from `apps/desktop/src-tauri/Cargo.toml`, repo's main Cargo.toml profile overrides it
- Update `packageManager` and remove conflicting `engineStrict` entry from package.json
- Remove `prefer-symlinked-executables` from `.npmrc`, linked bug was fixed
=> Fix front-end error when selecting multiple files with inspector open

apps/desktop/src-tauri/capabilities/default.json, core/crates/sync/src/ingest.rs, interface/app/$libraryId/settings/Sidebar.tsx, interface/app/$libraryId/settings/library/sync.tsx
Only cloud stuff is hidden behind the `cloudSync` feature now. This also fixes the backend feature flag dialog, since the dialog permission wasn't granted.
=> Make sync ingest setting public

core/crates/indexer-rules/src/lib.rs
https://github.com/spacedriveapp/spacedrive/pull/2459 introduced this snippet that does nothing, this allocation isn't used nor is necessary.
=> Remove unnecessary allocation

apps/mobile/src/components/modal/AddTagModal.tsx, apps/mobile/src/components/search/filters/FiltersBar.tsx, apps/mobile/src/components/search/filters/Tags.tsx, apps/mobile/src/screens/browse/Location.tsx
**This PR**: Fades out selected tags when there's many and you scroll + empty location state
=> [MOB-97] Fade select tags and empty location state

core/src/api/tags.rs
This PR makes it so tags cannot be created with the same name, stopping duplicate tags from existing. The front-end doesn't exist and this PR adds backend functionality. 
This is the error now from the backend when trying to create a duplicate tag:
```
Error executing operation: ErrResolverError(Error { code: Conflict, message: "Tag with the same name already exists", cause: None })
```
=> No Duplicating Tags

apps/desktop/crates/macos/src-swift/window.swift, apps/desktop/crates/macos/src/lib.rs, apps/desktop/src-tauri/src/main.rs, apps/desktop/src-tauri/tauri.conf.json
- Disable app nap on app launch on macOS, as this was negatively affecting file indexer when the app window was in the background
- Remove version from tauri.conf.json so tauri fallback to the version defined in Cargo.toml
- Probably fix updater asking to update when you already have (same problem as above)
=> Disable AppNap for macOS and fix app version in deb

Cargo.lock, core/crates/prisma-helpers/src/lib.rs, core/crates/sync/src/backfill.rs, core/prisma/schema.prisma, core/src/custom_uri/mod.rs, core/src/library/manager/mod.rs, core/src/p2p/manager.rs, core/src/p2p/operations/library.rs, core/src/p2p/operations/mod.rs, core/src/p2p/protocol.rs, core/src/p2p/sync/mod.rs, crates/p2p/crates/tunnel/Cargo.toml, crates/p2p/crates/tunnel/src/tunnel.rs, crates/sync/src/factory.rs, crates/sync/src/model_traits.rs, docs/developers/p2p/protocols.mdx
This PR implements the ability to serve the contents of files over P2P. This is used within the app for quick preview.
It's worth noting that files and thumbnails are handled differently and this PR does not cover thumbnails (refer to #2524 for it).
Not for merge: Although the P2P code in this PR works an issue with sync is breaking it in the real world. Will fix in a follow up PR.
=> Serve files over p2p

core/crates/sync/README.md, core/crates/sync/src/db_operation.rs, core/crates/sync/src/ingest.rs, core/crates/sync/src/manager.rs, core/crates/sync/tests/mock_instance.rs, core/src/cloud/sync/ingest.rs, core/src/p2p/sync/mod.rs
Cached sync operations from the cloud need to be deleted after they're processed, otherwise they'd build up over time.
=> [ENG-1776] Delete cloud ops after they've been ingested

core/crates/file-path-helper/src/lib.rs, core/src/api/utils/invalidate.rs, core/src/location/manager/mod.rs, core/src/p2p/operations/rspc.rs, crates/sync-generator/src/lib.rs
I found 4 instances of `#[allow(unused)]` and 6 instances of `#[allow(dead_code)]` across 5 source files, where the code was not actually dead or unused. This PR removes the usage of these unnecessary attributes.
=> Cleanup: remove unnecessary #[allow(dead_code)] and #[allow(unused)] attributes

apps/desktop/src-tauri/src/main.rs, core/src/lib.rs
Tries to capture and display the backtrace when the system crashes.
Note tho, that in the current state, it seems that tauri is somehow messing with the backtrace, so if the `core` crashes, it only captures an empty backtrace - I'm still not sure why, and I will investigate more later.
But with this added code, we at least start capturing the stacktrace, and when we figure out the tauri issue or move the `core` to a daemon architecture, it will emit the stacktrace.
As an example, if we create `core/src/bin/a.rs`:
```rust
use sd_core::Node;
fn main() {
let _guard = Node::init_logger("./").unwrap();
panic!("ops");
}
```
and run the application `RUST_BACKTRACE=1 cargo run`, it will emit the backtrace:
<details>
<summary>Collapsed</summary>
```sh
2024-05-24T16:53:29.496031Z ERROR sd_core: …
```
=> Display captured backtrace when available

apps/mobile/src/components/modal/inspector/ActionsModal.tsx, apps/mobile/src/components/modal/inspector/FileInfoModal.tsx, apps/mobile/src/components/modal/inspector/RenameModal.tsx
**This PR does the following:**
- Date accessed mutation was not running, it had a missing await since it's async. Date accessed values were null, until this change was done.
- Renaming objects now considers extensions, a case that I missed, should have been done from before.
- Added Accessed value to File info modal.
**Note**:
_Need to work on showing updated values without having to close and re-opening Inspector._
=> [MOB-105] Rename with extension & add await

Cargo.lock, apps/desktop/crates/linux/Cargo.toml, apps/desktop/crates/linux/src/env.rs, apps/desktop/src-tauri/Cargo.toml, apps/desktop/src-tauri/tauri.conf.json, core/Cargo.toml, core/src/api/tags.rs, core/src/library/manager/mod.rs, core/src/object/tag/mod.rs, scripts/setup.sh
- Don't statically compile dbus in order to prevent its symbols from tainting Nvidia driver when it tries to load the system's dbus library, [_more info_](https://internals.rust-lang.org/t/global-symbols-from-statically-linked-system-libraries/19954).
- Inject `WEBKIT_DISABLE_DMABUF_RENDERER=1` envvar when running on Linux with Nvidia graphics to workaround this bug: https://github.com/tauri-apps/tauri/issues/9304
closes #2541
=> Fix nvidia on linux segfault

crates/crypto/src/types.rs
This constructs the `GenericArray` directly, instead of using an iterator. 
And resolves a TODO comment.
=> Streamline conversion from Key to GenericArray

Cargo.lock, Cargo.toml, core/Cargo.toml, core/src/lib.rs
This PR fixes the issue of getting logs from the rust core on Android. Currently, when building for Android, logs will stop showing up after the `Spacedrive Online!` message.
Now, logs will go to `adb logcat` instead of the logfile. Please run `adb logcat | grep -i com.spacedrive.app` when looking at logs, in order to only see logs from the Spacedrive Rust core.
=> [MOB-72] Tracing logs not working on Android

interface/app/$libraryId/Explorer/Inspector/index.tsx, interface/app/$libraryId/Layout/Sidebar/JobManager/Job.tsx
**This PR**: 
- Simply fixes icons of job manager, key names have changed since improving jobs PR was merged.
- Removed un-necessary classname from inspector, after testing, it isn't needed + was giving error messages in console.
=> [ENG-1808] Fix job manager icons

Cargo.lock, Cargo.toml, core/crates/heavy-lifting/src/job_system/error.rs, core/crates/heavy-lifting/src/job_system/job.rs, core/crates/heavy-lifting/src/media_processor/helpers/thumbnailer.rs, crates/task-system/src/system.rs, crates/task-system/src/worker/runner.rs, rust-toolchain.toml
Catching panics when running tasks and jobs. Also introducing a `catch_unwind` when generating thumbnails as a quick workaround until https://github.com/image-rs/image/issues/2230 is fixed upstream.
=> [ENG-1809] Make core more resilient to crashes

interface/app/$libraryId/overview/StatCard.tsx, packages/client/src/lib/humanizeSize.ts
**This PR**: 
- Fixes the broken rendering of devices graph & progress value of the devices graph in Overview page.
- Improves progress color values, included yellow and dark orange.
**The bug is shown in the following video**:
https://github.com/spacedriveapp/spacedrive/assets/33054370/e46491dc-fd48-4f9f-81c3-2bedc2b86bed
**The issue fixed**:
https://github.com/spacedriveapp/spacedrive/assets/33054370/c787d629-cb06-4600-947d-037901acd863
=> [ENG-1610] Fix overview devices graph render

interface/app/$libraryId/overview/StatCard.tsx, packages/client/src/lib/humanizeSize.ts
Better than previous approach^
=> Quick sizing handling fix

interface/app/$libraryId/Explorer/index.tsx, interface/app/$libraryId/recents.tsx
We are reverting 1812 due to the issue existing within all explorer related routes, and not just recents page.
=> Revert ENG-1812

core/crates/heavy-lifting/src/file_identifier/job.rs, core/crates/heavy-lifting/src/file_identifier/mod.rs, core/crates/heavy-lifting/src/file_identifier/tasks/identifier.rs, core/crates/heavy-lifting/src/file_identifier/tasks/object_processor.rs, core/src/api/libraries.rs, packages/client/src/core.ts
Now we're properly identifying directories and empty files, assigning objects to both of them, even though we can't process then to generate a cas_id.
=> [ENG-1814] Assign objects to directories on File Identifier Job

interface/app/$libraryId/Explorer/View/GridView/index.tsx, interface/app/$libraryId/Explorer/View/index.tsx, interface/app/$libraryId/Explorer/useExplorer.ts, interface/app/$libraryId/favorites.tsx, interface/app/$libraryId/location/$id.tsx, interface/app/$libraryId/recents.tsx, interface/app/$libraryId/tag/$id.tsx
**This PR**:  Fixes initial rendering of explorer by making sure the initial rendering is successful and not blank.
- Also fixes updating gap values when "show tags" is toggled, previously it would take a few toggles for Explorer to update, now it's instant.
=> [ENG-1816] Fix explorer rendering

.gitattributes
This PR revamps our `.gitattributes` file to more properly show language statistics on the repository and hide diffs for files generated by codegen in PRs and commit diffs.
- `linguist-*` attributes are specifically used by GitHub to control how files contribute to its statistics and PR/commit diff views. ([docs](https://github.com/github-linguist/linguist/blob/master/docs/overrides.md#summary))
- `-diff` marks a file as "binary" which further signifies to Git that the diff will tend to be 'messy' and not desirable for human review. In the case of lockfiles and some generated code, I use this attribute on top of Linguist rules. ([docs](https://git-scm.com/docs/gitattributes#_marking_files_as_binary))
=> Revamp `.gitattributes` for statistics and better PR diffs

apps/desktop/package.json, pnpm-lock.yaml
A recent update to `@tauri-apps/cli` changed the schema for `tauri.conf`, which is breaking our builds. This PR downgrades `@tauri-apps/cli` to the latest working version: `2.0.0-beta.20`
=> [ENG-1821] Fix build failing due to new schema validation in @tauri-apps/cli

core/src/location/manager/watcher/utils.rs, core/src/old_job/mod.rs
Also fixing errors on watcher, we must not generate thumbs and extract media data for duplicates
=> Fix a panic on old job system

interface/app/$libraryId/Layout/Sidebar/SidebarLayout/index.tsx, interface/hooks/useShortcut.ts
**This PR**: Fixes shortcuts conflicting with each other of toggling sidebar and navigate back.
- The new shortcut of toggling sidebar is CMD/CTRL + S
=> [ENG-1830] Change sidebar toggle shortcut

apps/mobile/src/components/drawer/DrawerLibraryManager.tsx, apps/mobile/src/components/explorer/Explorer.tsx, apps/mobile/src/components/explorer/FileMedia.tsx, apps/mobile/src/components/explorer/FileThumb.tsx, apps/mobile/src/components/primitive/FeatureUnavailableAlert.tsx, apps/mobile/src/components/settings/SettingsItem.tsx, apps/mobile/src/screens/settings/Settings.tsx, apps/mobile/src/screens/settings/info/Debug.tsx
- Media view thumbnails improved, now gaps are correct and equal across different devices.
- Alert and less opacity for coming soon routes & Lock button in sidebar.
- In Debug page, within settings, box color was weird.
=> [MOB-114] Improve Media View thumbnails and coming soon alerts

patches/@oscartbeaumont-sd__rspc-tauri@0.0.0-main-dc31e5b2.patch, pnpm-lock.yaml
Fixes the following issue by updating the API used in the following patch to use the latest API due to the underlying package being updated.
=> Update `rspc-tauri` patch to use updated Tauri API

interface/app/$libraryId/Explorer/QuickPreview/index.tsx, interface/app/$libraryId/TopBar/index.tsx, interface/hooks/useShortcut.ts
Added QOL shortcuts to quick preview 
- Shortcuts CMD and +/CMD and - added for zoom in/zoom out respectively. 
- Pinch support added for trackpad. 
Closes #(issue)
https://linear.app/spacedriveapp/issue/ENG-1806/quick-preview-add-zoom-shortcuts-and-pinch
=> [ENG-1806] Add zoom shortcuts and pinch to quick preview 

interface/app/$libraryId/Explorer/View/ViewItem.tsx
Fixes bug where clicking explorer item with a mouse would cause the native context menu to open instead of the Spacedrive context menu.
=> [ENG-1791] Fix right-click sometimes opening native context menu

Cargo.lock, apps/desktop/src-tauri/Cargo.toml, core/Cargo.toml
We will be releasing 0.4.1, this PR bumps the Spacedrive Core and Desktop versions to match
=> Bump version to 0.4.1

apps/desktop/package.json, apps/storybook/package.json, apps/web/package.json, crates/sync/example/web/package.json, interface/package.json, package.json, pnpm-lock.yaml
Fixes weird binary issue with esbuild versions clashing across deps.
=> Update to vite `^5.2.0`

scripts/fix-deb.sh
Workaround tauri using cargo.toml name for executable when packaging `.deb`
Closes: #2647
=> [ENG-1838] Fix Debian executable name

interface/app/$libraryId/Explorer/QuickPreview/index.tsx, interface/app/$libraryId/search/SearchOptions.tsx
Co-authored-by: Lynx <iLynxcat@users.noreply.github.com>
Fixes bug where pressing escape with both search and quick preview open causes both to close. 
- now, only quick preview closes 
https://linear.app/spacedriveapp/issue/ENG-1707/pressing-esc-closes-quick-preview-search
=> [ENG-1707] Fix bug causing both quick preview and search closing with esc

interface/app/$libraryId/settings/client/keybindings.tsx, packages/ui/style/colors.scss
- Use rgb(235,235,235) for the brightest text color in dark mode (Closes #2417)
- Increase keybind text size in settings for better legibility (before/after):
Fixes #2417
=> Dim pure white text & increase keybind text size in keybind list

Cargo.lock, crates/images/Cargo.toml
Use a fork of pdfium-renderer including the required fix while a new version isn't released
Related:
https://github.com/ajrcarey/pdfium-render/pull/155
=> Fix pdf thumbnails

Cargo.lock, apps/desktop/src-tauri/Cargo.toml, apps/desktop/src-tauri/src/main.rs, apps/server/docker/Dockerfile, core/Cargo.toml
- Change version to 0.4.2
- Don't call specta export on prod releases
- Install prisma before trying to use it when building server
=> Fix 0.4.2 release

apps/landing/src/app/page.tsx
**This PR**:
- Shows latest alpha version dynamically instead of hard coding.
- Changelog link based on the version.
**Image**:
=> [ENG-1860] News banner with latest alpha version & changelog link

interface/app/$libraryId/overview/StatCard.tsx, packages/client/src/lib/humanizeSize.ts
**This PR**: Fixes the progress value of device storage
Tested on Windows & MacOS with TB, GB, and various values. 
Works well.
=> [ENG-1866] Overview: fix storage progress device value

interface/app/$libraryId/TopBar/TopBarOptions.tsx, interface/app/$libraryId/overview/index.tsx
**This PR addresses this issue**: https://github.com/spacedriveapp/spacedrive/issues/2689
- Resizing the window, should no longer hide the Windows OS window options.
=> [ENG-1874] Always show windows top bar options

Cargo.lock, crates/images/Cargo.toml
R̶e̶v̶e̶r̶t̶ ̶#̶2̶6̶6̶6̶ ̶a̶n̶d̶ ̶b̶u̶m̶p̶ ̶p̶d̶f̶i̶u̶m̶-̶r̶e̶n̶d̶e̶r̶ ̶v̶e̶r̶s̶i̶o̶n̶.̶
W̶i̶t̶h̶ ̶o̶u̶r̶ ̶c̶u̶r̶r̶e̶n̶t̶ ̶f̶o̶r̶k̶,̶ ̶w̶e̶ ̶r̶e̶c̶e̶i̶v̶e̶ ̶a̶ ̶l̶o̶t̶ ̶o̶f̶ ̶e̶r̶r̶o̶r̶s̶ ̶r̶e̶l̶a̶t̶e̶d̶ ̶t̶o̶ ̶l̶i̶n̶k̶i̶n̶g̶,̶ ̶a̶n̶d̶ ̶t̶h̶e̶ ̶o̶r̶i̶g̶i̶n̶a̶l̶ ̶c̶r̶a̶t̶e̶ ̶m̶e̶r̶g̶e̶d̶ ̶o̶u̶r̶ ̶c̶h̶a̶n̶g̶e̶s̶ ̶(̶t̶h̶a̶n̶k̶s̶ ̶@̶H̶e̶a̶v̶e̶n̶V̶o̶l̶k̶o̶f̶f̶!̶)̶
@HeavenVolkoff: Updated custom fork and increased the minimum required pdfium api, now that native_deps ships the latest pdfium lib. Unfortunately, we still need a custom fork due to upstream [adding a hard limit on chono version <= 0.4.31](https://github.com/ajrcarey/pdfium-render/blob/bc1195b23a777325afea96a5fc895e9f3db381c6/Cargo.toml#L26), which is incompatible with some of our dependencies which require newer versions
=> Update pdfium-render version

interface/app/$libraryId/settings/Layout.tsx
Closes #2529 
Simple fix, was a bit harder figuring out just *where* to put this logic lol. But it just takes the same height of the topbar and puts it as top-padding for the settings selection window's. Checks to see if it's windows os and more than 1 tab (as that's where the bug happens)
I'm not fully sure if these two logics can be combined. I don't think it can? But would love to be told I'm wrong, and learn that it can be. :)
```${os === 'windows' && 'mt-6'} ${os === 'windows' && ctx.tabs.length > 1 && 'pt-9'}```
The result of the fix.
=> fix windows multiple tab spacing

.cspell/project_words.txt, core/src/library/manager/mod.rs, core/src/library/manager/pragmas.rs
This PR optimizes SQLite performance by configuring key PRAGMA settings, including:
•	Enabling Write-Ahead Logging (journal_mode = WAL) for improved concurrency.
•	Setting synchronous = NORMAL to balance durability and performance.
•	Increasing memory-mapped I/O size to 512MB for faster database access.
•	Limiting the journal file size to 64MB to prevent excessive disk usage.
•	Setting the cache size to 10,000 pages (~40MB) for faster reads.
These changes aim to enhance database performance, especially in environments with concurrent transactions.
=> Add SQLite pragmas to optimize performace

apps/mobile/src/hooks/useEnableDrawer.ts, apps/mobile/src/navigation/DrawerNavigator.tsx, apps/mobile/src/navigation/SearchStack.tsx, apps/mobile/src/navigation/TabNavigator.tsx, apps/mobile/src/navigation/tabs/BrowseStack.tsx, apps/mobile/src/navigation/tabs/OverviewStack.tsx, apps/mobile/src/navigation/tabs/SettingsStack.tsx, apps/mobile/src/screens/browse/Browse.tsx, apps/mobile/src/screens/browse/Locations.tsx, apps/mobile/src/screens/network/Network.tsx, apps/mobile/src/screens/overview/Overview.tsx, apps/mobile/src/screens/settings/Settings.tsx, apps/mobile/src/screens/settings/library/LocationSettings.tsx
- You can now swipe from inner screens of stacks to navigate back to the initial route of that stack or the previous screen of that stack.
- The Drawer will now only open on the initial screens of the stacks, i'm using a hook which has been applied to 4 of those screens that enables Drawer Swiping (this can be improved).
- Pressing on a location in settings will take you to edit location page instead.
=> [MOB-123,122,121] Fix & improve navigation issues

interface/app/$libraryId/Explorer/ContextMenu/SharedItems.tsx, interface/app/$libraryId/Explorer/Inspector/index.tsx, interface/components/ColorPicker.tsx, packages/ui/src/Dialog.tsx
- Add tag context menu shows in quick preview.
- Pressing + New Tag will now show the dialog properly while quick preview is open.
- Quick view -> Quick Preview in context menu.
**images**:
=> [ENG-1897,1900,1901] Quick add tag fix & more

Cargo.lock, Cargo.toml, apps/desktop/src-tauri/Cargo.toml, apps/desktop/src-tauri/src/main.rs
This PR changes the global allocator to mimalloc. In our tests, it performed better than the default allocator, making Spacedrive less intense in memory terms.
Note tho, that this PR doesn't fix our current issue with memory leaking, but it contributes to a better experience overall.
=> Use mimalloc as the global memory allocator

core/crates/file-path-helper/src/lib.rs
We're using the raw Windows API to read the file index ("inode"), but forgetting to close the handle after reading the metadata causing a leak of file handles.
This PR fixes the issue by manually closing the handle.
It will be better to use `MetadataExt::file_index` in the future once it gets stabilized.
Closes #2725
=> Close file handle after getting its index (windows)

core/crates/heavy-lifting/src/media_processor/helpers/thumbnailer.rs
When generating thumbnails, we may crash if the file is invalid, e.g. has an invalid width or height.
The application shouldn't crash, but report the invalid file as a non-critical error and keep processing the remaining files.
This PR does that by not calling the [`Encoder::encode`](https://github.com/jaredforth/webp/blob/4e7616a0a62bc4a78a9c63cfd3040fdd6757f92b/src/encoder.rs#L70), which `.unwrap`s, but rather calling `Encoder::encode_simple` and handling its result.
Closes #2736
=> Handle thumbnail encoder error

interface/app/$libraryId/Explorer/Inspector/MediaData.tsx, interface/app/$libraryId/Explorer/Inspector/Note.tsx, interface/app/$libraryId/Explorer/Inspector/store.tsx
Notes in the Inspector work now... not that anyone noticed they didn't 🥲
- Ensure note value updates when prop data changes.
- Fixed a rendering bug in MediaData caused by separate metadata functions leading to inconsistent updates. Replaced them with a single renderMetadata function for better consistency.
- Added a Valtio store in Note.tsx to cache note values across files, prioritizing cached values unless the backend value changes.
=> Fix Inspector notes

interface/app/$libraryId/Explorer/util.ts
This PR switches the date format example from 1 Jan 2024 (where 01/01/2024 could mean MM-DD-YYYY or DD-MM-YYYY) to one less confusable (15 Jan 2024)
08:51 was chosen because 08 allows explicit visibility of zero-padding, 51 was just random and felt right
Closes ENG-1931
=> Change sample date

apps/mobile/modules/sd-core/core/Cargo.toml
Android builds fail to compile due to weird dependency linking issues. This PR fixes that, and we now have working Android builds again.
=> Fix Android builds failing to compile

Cargo.lock, Cargo.toml, apps/mobile/modules/sd-core/ios/build-rust.sh, core/crates/cloud-services/Cargo.toml, core/crates/cloud-services/src/client.rs, core/crates/cloud-services/src/error.rs, core/crates/cloud-services/src/p2p/new_sync_messages_notifier.rs, core/crates/cloud-services/src/p2p/runner.rs, core/crates/cloud-services/src/sync/receive.rs, core/crates/cloud-services/src/sync/send.rs, core/src/api/cloud/devices.rs, core/src/api/cloud/mod.rs
Version 0.13.0 of quic-rpc had some breaking changes that we need to fix to also update cloud services schema.
=> Update quic-rpc and cloud services schema

Cargo.lock, apps/desktop/src-tauri/Cargo.toml, core/Cargo.toml
This PR bumps the version to 0.5.0 since that's officially the version being worked on in `main`.
=> Bump version to 0.5.0

pnpm-lock.yaml, scripts/package.json
This PR adds `node-gyp` as a dependency in `scripts`, fixing an issue where if `node-gyp` isn't globally installed the install command for `registry-js` (a dependency of `os-proxy-config`) would fail, forcing other install and postinstall scripts to be forcefully aborted with it.
=> Add `node-gyp` dependency to `scripts`

crates/media-metadata/src/exif/flash/data.rs
Resolves this TODO in `crates/media-metadata/src/exif/flash/data.rs`:
`// TODO(brxken128): This can be heavily optimized with bitwise AND`
=> Optimize Option<Flash>::from(FlashValue) using bitwise AND
